ProcessMaker/screen-builder

src/components/renderer/form-button.vue
src/form-builder-controls.js

They submit button can now be used as an approve or reject button with a name and value to submit with it.

button now has name and value

---

src/components/vue-form-renderer.vue

We need to bind the name of the element to the component so that child elements have easy access. This will be used by the File Downloader in order to specify which file should be displayed/downloaded on the renderer.

Easily pass name of element to child

---

package-lock.json
package.json
src/components/editor/multi-column.vue
src/components/inspector/color-select.vue
src/components/renderer/form-multi-column.vue
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue
src/form-builder-controls.js
src/mixins/HasColorProperty.js

- Add a control to select colors
- Add properties bgcolor and color for the controls
- Add the additional properties to the form templates.
Color choose:
Design mode:
Preview:
Implements: #52

Implements color properties in form builder controls #52

---

package-lock.json
package.json
src/components/custom-css.vue
src/components/renderer/form-text.vue
src/components/vue-form-renderer.vue
src/form-builder-controls.js
vue.config.js

Fixes #55 
Allows you to use the field name as the wrapper ID for custom css, for example an input with the field name `foo` can be used like `#foo { font-size: 40px }` in the custom css.
Also added a specific css class name field for text box since it doesn't have a field name
Also added Monaco editor as part of this PR

Set the wraper ID to the field name so CSS can use it

---

src/components/index.js

When using the latest `develop` (`0.7.0`) in modeler, an error with thrown due to a missing import:
```
Uncaught ReferenceError: ImageUpload is not defined
```
This PR fixes that issue.
Related issue: https://github.com/ProcessMaker/modeler/issues/221 (Inspector Accordion).

Import missing ImageUpload component

---

src/components/editor/multi-column.vue
src/components/renderer/form-multi-column.vue
src/components/vue-form-renderer.vue

Fixes #88 
Brings back the missing IDs on rendered elements so the custom CSS editor can use them

Add ids to elements so custom css can use them

---

src/components/computed-properties.vue
src/components/vue-form-renderer.vue

- Support for javascript expression
- Add a icon for the simple expression
Fixes: #78 
Example of javascript expression (Note: Do not require **return** statement)
Example of simple expression:
Result:

Add javascript expression - Computed Properties

---

src/components/renderer/form-button.vue
src/form-builder-controls.js

Fixes #98. For whatever reason, the word **value** caused a lot of issues. Changing it to **fieldValue** _seems to_ have solved them.

Fix to submit buttons not saving value

---

package.json
vue.config.js

Currently, bootstrap was included in the bundle output. This PR makes it an external dependency so it plays well with the environment where it's used (to avoid conflicts with bootstrap versions). This change is required for the `switch` property on the `b-form-checkbox` component to actually show a switch (required for https://github.com/ProcessMaker/modeler/pull/278).

Make bootstrap an external/peer dependency

---

src/components/vue-form-renderer.vue

This PR changes the javascript evaluation in computed properties to use new Function and using .**bind**() function to put the data context into **this**. This way the properties should be referenced as follows:
```
return this.a + this.b
```

Implement javascript evaluation for computed properties

---

package-lock.json
package.json
vue.config.js

This fix includes the same changes as https://github.com/ProcessMaker/vue-form-builder/pull/103, but with bootstrap still specified in `devDependencies`.
**Description of changes:**
Externals (https://webpack.js.org/configuration/externals/#root):
> The externals configuration option provides a way of excluding dependencies from the output bundles. Instead, the created bundle relies on that dependency to be present in the consumer's environment. This feature is typically most useful to library developers, however there are a variety of applications for it.
Dependencies (https://docs.npmjs.com/files/package.json):
With bootstrap in `devDependencies`, npm will ensure its installed when developing, and since it’s listed under `externals` in the webpack config, it won’t be bundled with the …

Make bootstrap a peer dependency

---

package-lock.json
src/components/custom-css.vue
src/components/vue-form-builder.vue
src/global-properties.js

Fixes #135 
Adds a css selector attribute on the outermost div for elements called "selector" that's set in the inspector. The custom css editor can reference these with `[selector='my-selector'] { ... }`

Add a css selector attribute to all form elements

---

package-lock.json
package.json
src/App.vue
src/components/computed-properties.vue
src/components/custom-css.vue
src/components/inspector/color-select.vue
src/components/inspector/container-columns.vue
src/components/inspector/options-list.vue
src/components/renderer/form-button.vue
src/components/renderer/form-record-list-static.vue
src/components/renderer/form-record-list.vue
src/components/renderer/form-text.vue
src/components/vue-form-builder.vue
src/main.js

Fixes #137 
Known issue: errors from our frontend validation library, validatorjs, are not translated. [They mention there is some support](https://github.com/skaterdav85/validatorjs#language-support) but its not vue-i18next. Maybe this can be fixed with custom messages but we would have to manually add all of them

Add translation support to vue-form-builder

---

package-lock.json
package.json
src/components/vue-form-builder.vue
src/main.js
src/undoRedoModule.js

Fixes #139.
This PR add undo/redo functionality (identical to the modeler) per page in the screen builder. VueX modules are utilized to re-use the same undo/redo logic that's used in the modeler.

Add undo/redo functionality

---

src/App.vue
src/components/renderer/form-text.vue

Fixes #151.
How to test:
1. Select `Preview` and add some data under `Data Input`, e.g. `{ "name": "Rob" }`.
2. Select `Editor`, drag a `Text` component onto the form, and select it.
3. In the `Inspector`, add something like `Hello, {{name}}.` for `Text Content`.
4. The component in the `Preview` window should show `Hello, Rob.`, instead of just `Hello, .`
5. Repeat steps 2-4 above for the `Rich Text` component.
Blocked until https://github.com/ProcessMaker/vue-form-elements/pull/33 is merged and published. That PR is required to add the interpolation to the `Rich Text` component.

Add config data interpolation for form-text component

---

src/components/vue-form-builder.vue

- Removes the "Drag an element here" card from the draggable area until a better solution can be implemented
Closes #170.

Removing “drag element here” card

---

src/components/vue-form-builder.vue

Fixes #174.
Ensures the bug, [as described in the issue](https://github.com/ProcessMaker/spark-screen-builder/issues/174#issuecomment-494938340), is no longer present.
The issue was that `draggable` was cloning the control element to use as the preview in the form elements list, and the cloned element was a list group item. List group items, by default, only render with a bottom border if they are at the bottom of the list, and also only have rounded top and bottom borders if they are at the top or bottom of the list, respectively.
**Video of fix:**
https://www.dropbox.com/s/lwvg986iqb1zoci/bottom-border-fixed.mov?dl=0

Fix bottom border on dragging form control 

---

src/App.vue

- Preview Inspector uses the full height of the card
- Data input / preview take 50% of the inspector container
https://drive.google.com/open?id=1XECBNU_X86rXZcLReKm7eHUL5bn73QrH
Fixes #172 , #171

Preview Inspector UI

---

src/components/editor/multi-column.vue
src/components/renderer/form-multi-column.vue
src/components/vue-form-builder.vue

- Multi-column element did not have the classes attached
**Screen Builder Stand Alone**
https://drive.google.com/open?id=16C_oWwyEPobwM_jvxYdUF0n6DqUbyWSz
**Spark Screen Builder**
https://drive.google.com/open?id=10Q-MLnN0Bhx5iY1aJEI2UO2BelIaoJHq
In type display, multi-column is broken in this branch, but is fixed in this PR https://github.com/ProcessMaker/spark/pull/1852
Fixes #182

Add selected state to multi-column

---

src/App.vue
src/components/vue-form-renderer.vue

**How to Test**
- Create new form page
- On `default page` (first form) drag a navigation component and set destination to any other page than the default page
- Click Preview, navigate to another page
- Toggle between builder and preview
**Expected**
- Toggling between preview and builder, the first form page will be set as the first one visible 
**Stand Alone**
https://drive.google.com/open?id=1IT2t5Ne6_CqU3xxX6BrWWo9pMZE_FKj7
**Spark Screen Builder**
Will address in this issue (https://github.com/ProcessMaker/spark/issues/1881) and have its own separate PR(https://github.com/ProcessMaker/spark/pull/1883) in spark repo.
Fixes #205

Preview Page Will Start with First Form

---

src/App.vue
vue.config.js

**Changes**
- removed form text area component 
- use monaco editor instead
**To Test**
- Navigate to the preview view
- type an json object
**Expected**
- JSON has formatting and syntax highlighting 
**Screen Capture**
https://drive.google.com/open?id=1cmEBK2WghffeV1wtonTrHq8iOA2galZO
- Spark application has a separate PR(https://github.com/ProcessMaker/spark/pull/1885) in the spark repo to use the Monaco Editor
Fixes #173

Replace textarea component for monaco editor 

---

package-lock.json
package.json
src/components/editor/index.js
src/components/index.js
src/components/inspector/index.js
src/components/renderer/form-record-list.vue
src/components/renderer/index.js
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue
vue.config.js

This PR fixes issues brought up with the latest QA build:
1. The form doesn't load in the preview page initially (it only loads after making a change in the builder).
2. The first option in a radio group doesn't appear to be visually selected anymore, even though the 1st option is set by default when submitting the form.
3. Fixes #214.
**The accompanying PR on spark is here:** https://github.com/ProcessMaker/spark/pull/1893.
**The accompanying PR on vue-form-elements is here:** https://github.com/ProcessMaker/vue-form-elements/pull/43.
For no. 1 above. the problem was solved by setting the config object to the default config from the `screen` prop on initial load. Before it was only "copying" the form config to the preview page when a change was made (hence why the preview appeared blank …

Fix preview and radio group checked state

---

package-lock.json
package.json
src/components/vue-form-builder.vue
src/main.js
vue.config.js

Moved a handful of dependencies over to peer dependencies, updated imports, and adjusted `vue.config.js`.
Removed `dependencies` since this package is exported as a library bundle and there is no need for consumers to install additional dependencies that won't be used.
Build on `develop` branch:
```
File                                Size                Gzipped
dist/vue-form-builder.umd.min.js    3040.37 KiB         911.77 KiB
dist/typescript.worker.js           8064.23 KiB         671.20 KiB
dist/vue-form-builder.umd.js        7304.11 KiB         1536.99 KiB
dist/vue-form-builder.common.js     7303.62 KiB         1536.79 KiB
dist/css.worker.js                  1433.25 KiB         143.76 KiB
dist/editor.worker.js               404.04 KiB          28.44 KiB
dist/vue-form-builder.css …
```

Reduce bundle size

---

package-lock.json
package.json
src/components/editor/multi-column.vue
src/components/renderer/form-multi-column.vue

Fixes #226.
Video of fix: https://www.dropbox.com/s/er8mjfufbor9x3g/rich_text_interpolation_working.mov?dl=0.
When testing, make sure to run `npm i` (or `npm ci`), `npm run build-bundle`, and `npm link` on this branch, and then `npm link @processmaker/spark-screen-builder ` on the latest spark develop branch.

Fix interpolation inside rich text element

---

src/App.vue
src/components/vue-form-renderer.vue
src/global-properties.js
tests/unit/CustomCss.spec.js

- The fix for the text-colour bug requires changes in the spark repo. There is a PR in spark repo for it (https://github.com/ProcessMaker/spark/pull/1955)
- Adding a custom class threw an error, the validation was not properly working
- Fix custom css styles,
- styles were not being applied to the design view but only the preview 
**Spark Video Demo - Text Color Fix**
https://drive.google.com/open?id=15tSnFtkOju6pN3BPFcfiBIJ3nFjiyl-2
**Spark Video Demo - Custom Css Fix**
https://drive.google.com/open?id=1nZPsd_oxCWNzdVkfGUqM88qcY8O80tLo
Fixes #223

Fix text color select & custom css

---

src/components/editor/multi-column.vue
src/components/renderer/form-multi-column.vue

Another bug was exposed, when the Rich Text was rendered in the multi-column, the inspector config values did not update with the rendered Rich Text. Fixed in this PR.
https://drive.google.com/open?id=1hiW-QKc9EPirj-Y8UZHu8CB9fdcOR_sA
Fixes #217

Multi-column renders Rich Text component

---

src/components/editor/multi-column.vue
src/components/vue-form-builder.vue

Fixes #221.
Video of fix: https://www.dropbox.com/s/0rynwuzcsiq345x/dragging_improved.mov?dl=0.
The functionality for dragging elements into/out of nested draggable lists (table / multi-column) was already correctly implemented. However, due to styling changes, the relative sizes of elements, and the fact that they can change, made it difficult to line up the drop / swap targets to allow dragging into a nested list.
This PR modifies the properties of the draggable lists to make it easier to interact with nested lists. The descriptions of these options is listed here: https://github.com/SortableJS/Sortable#options.
The [SortableJS example](http://sortablejs.github.io/Sortable/#nested) mentions the following, which has been implemented in this PR:
> NOTE: When using nested Sortables with …

Adjust draggable options for nested lists

---

src/components/vue-form-builder.vue

Fixes #254.
Gif of fix (with file-upload component):
Screenshots of fix:

Adjust mask to cover 100% of element

---

vue.config.js

Externals was not correctly set up for peer dependencies. This PR fixes that; it is now set up in the same was as in https://github.com/ProcessMaker/spark-modeler/pull/433.

Fix externals

---

src/components/vue-form-renderer.vue

Fixes #252.
This PR ensures that when a variable name contains a value that would be an invalid path name for [vue-deepset](https://github.com/bhoriuchi/vue-deepset), that it's set as a string name / object property, e.g.:
```
foo.bar => { "foo": { "bar": "some value" } }
foo.000.bar => { "foo.000.bar": "some value" }
```
Video of fix: https://www.dropbox.com/s/kbtmtnvqjc1x7qr/var_name_working.mov?dl=0.

Prevent error when invalid variable name set 

---

src/components/computed-properties.vue
vue.config.js

**How to test**
- Click Calc Button
- Click `Add property` button on modal
**Expected**
No console errors
Adding `typescript ` to the list of languages is required because typescript and javascript have distinct colourizers, but share the same implementation for the language smarts .
https://drive.google.com/file/d/1e0twQBNRaY1NFUjaUHQ90ggVgZCmTZZP/view
Fixes #246

Fix calc field undefined error.

---

src/components/computed-properties.vue
src/components/custom-css.vue

Prevents click-away on Calcs and CSS modals
https://drive.google.com/open?id=1p81FAr67IEkMnb_J2I0LT3zDTHyTGEHt
Fixes #248

Prevent clickaway on modal

---

src/form-builder-controls.js

Fixes #250.
This PR adds readonly attributes to form inputs: `Line Input` and `Textarea`.
This PR requires changes in `vue-form-elements`: https://github.com/ProcessMaker/vue-form-elements/pull/47.
Video of fix: https://www.dropbox.com/s/vsc8nvdrg5t63y7/readonly_working.mov?dl=0.

Add readonly props to inputs

---

src/components/inspector/page-select.vue
src/components/vue-form-builder.vue
src/form-builder-controls.js

Fixes #249.
This PR removes the Configuration accordion, and replaces it with Variable and Design accordions. The Variable accordion contains a specified list of form types that correspond to variable data, while the Design accordion contains all the other (design) fields.
Video of fix: https://www.dropbox.com/s/s256p0rvucvaz69/var_reorg_working.mov?dl=0.

Replace config accordion with variable and design

---

src/form-builder-controls.js

The original validation bug `"The undefined must be a string" appears when adding a Textarea` could not be replicated, however, there is no validation error when adding a Textarea and inputting a string into the 'Rows' field instead of an integer. This PR adds the proper validation error for the 'Rows' field.
closes #307

Fix Textarea Validation Message

---

src/VariableDataTypeProperties.js

Fixes #330. The currency data type will no longer appear in the dropdown.
Screenshot of fix:

Remove currency datatype

---

src/form-builder-controls.js

Fixes #335.
Screenshot of fix:

Update rich text content label

---

src/App.vue
src/components/vue-form-builder.vue

Added mouseover text for the following buttons:
- Save Screen
- Add Page
- Edit Page
- Delete Page
_(we'll probably need a separate commit on PM4 core to add the title strings to the en.json file for future translation)_

Added missing button mouseover text

---

src/components/inspector/options-list.vue

Resolves #381 
- When clicking twice a radio button option, the default option is reset.

Allow the possibility of removing de default Option in select lists and radio button groups

---

src/components/accordions.js
src/components/vue-form-renderer.vue
src/form-builder-controls.js
src/form-control-common-properties.js

Resolves #384 
Bootstrap does not introduce special considerations for disabling Select, radio groups, checkbox.
- Add disabled property in Select, Radio Groups, Date Picker, checkbox.

Read Only Controls

---

src/components/vue-form-builder.vue

Fixes #387 
Fixes https://github.com/ProcessMaker/package-collections/issues/116
If the custom inspector field does not exist in accordion.js, it will add it to the 'Configuration' accordion by default. This at least gets us the inspector controls back. We should make a separate issue to allow packages to specify accordion(s) to use for their custom inspector fields.

Add fields not specified in accordions.js to configuration by default

---

src/components/inspector/options-list.vue

This PR removes the standard `textarea` being used for editing the JSON Data in Data Sources and replaces it with the Moncao Editor. 
closes #405

Add monaco json editor/402

---

src/components/vue-form-builder.vue

This PR fixes the `The undefined field is required` bug when creating a new page. 
closes #377

Fix 'The undefined field is required' error when creating a new page.

---

src/components/computed-properties.vue

Resolves #423 
Css class was fixed to use a better height for the box.
Before the change:
With the correction

Calculated Field Javascript Size

---

src/components/inspector/options-list.vue

This PR fixes an issue for the Data Source type Data Object Name from being cleared when saving and or selecting another element.
Dependent on [#111](https://github.com/ProcessMaker/vue-form-elements/pull/111) in vue-form-elements.

prevent data name from being overwritten in data source

---

package-lock.json
src/components/inspector/options-list.vue
src/components/vue-form-renderer.vue
src/form-builder-controls.js
tests/unit/ConditionalHide.spec.js
tests/unit/VueFormBuilder.spec.js

The purpose of this pull request is to remove the Data Type dropdown from the Checkbox inspector.
**Acceptance Criteria** 
The checkbox inspector panel does not contain DataType Dropdown.
Fixes #440

Remove Datatype dropdown 

---

src/form-builder-controls.js
tests/unit/VueFormBuilder.spec.js

The purpose of this pull request is to remove the datatype down from the inspector.
**Acceptance Criteria.**
The text area inspector should not contain the datatype select.
Fixes #438

Textarea Element: Remove Dataype dropdown

---

src/components/inspector/options-list.vue
tests/unit/OptionsList.spec.js

Fixes #441.
Before:
After:
Note the slight change in the "_Edit as JSON_" and "_Edit as Option List_" buttons. I've changed them to actual buttons (they were links before) and used the Font Awesome _code_ icon: https://fontawesome.com/icons/code?style=solid. This looks slightly better and is more accessible.

Remove value and content fields for Select List when "Edit as JSON" is selected

---

src/components/watchers-synchronous.vue

closes #459, https://github.com/ProcessMaker/processmaker/issues/2638
Allow hide modal watcher error

Failed Watcher Cannot Complete

---

src/components/computed-properties.vue

- Fixes an issue where the actions slot was not displaying in the list of computed properties
- Imports and uses vuetable instead of outdated b-table component
- Fixes minor UI issues
Closes #471.

Quick fix to Computed Properties actions slot

---

src/components/inspector/options-list.vue

Resolves #482 
A default value is used if the component doesn't have a dataName option configured

Imported screen with Select List control freezes when editing the SelectList

---

package-lock.json
package.json

Resolves #487 
Updates expr-eval to the latest version. This version has support for expressions like:
var1[0]=="a"
indexOf(var1, "a") > 0

Upgrade of expr-eval to version 2.0.2

---

src/components/inspector/options-list.vue

Resolves #489 
In commit 65b64c132c3e250badbce1789b843c2c05057172 the importing of Monaco editor was deleted. This line has been restored and no more errors are generated and the Monaco editor correctly formats JSON strings

Select List - Error generated when using "Edit as JSON" 

---

src/VariableDataTypeProperties.js
src/components/renderer/form-masked-input.vue
src/form-builder-controls.js

- Remove the 'Type' dropdown under the Input Configurations.
- Add the 'Password' option to the 'Data Type' dropdown.
- Add a FormInput and change the Data Type to Password.
- Render the form.
Input is masked. 
closes #496

FormInput: Add Password option to the Data Type dropdown

---

src/components/vue-form-builder.vue

Fixes #512 
Fix for supporting old screens was adding validation to key name on all elements, even the ones that shouldn't have them (submit button, image)

Only update old validation if the key already existed

---

src/App.vue
src/components/editor/loop.vue
src/components/renderer/form-loop.vue
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue
src/form-builder-controls.js

Fixes #354 
Requires: https://github.com/ProcessMaker/processmaker/issues/2812

Add loop control

---

src/components/renderer/form-loop.vue
src/form-builder-controls.js

Fixes #534 
- If data is present for a loop control, use its length as the number of loops to render. If not, use the value set in the inspector.
- Wrap each loop iteration in a `form` tag to isolate radio buttons. They have the same name attribute so the browser will otherwise treat them as the same input value.

Determine number of times to loop from existing data

---

src/components/basic-search.vue
src/components/inspector/data-mapping.vue
src/components/watchers-form.vue
src/components/watchers-list.vue
src/components/watchers-popup.vue

- Standardizes the Watchers list using our standard table component and search bar
- Converts the Watcher form into an accordion to better organize the information
- Improves text labels based on feedback from stakeholders
- Adds helper text to all form fields
- Confirms prior to deleting a Watcher
- Requires https://github.com/ProcessMaker/processmaker/pull/2841 in core
Closes #533.

Watcher UI overhaul

---

src/components/editor/loop.vue
src/components/editor/multi-column.vue
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue

Fixes #572 
There were a number of container elements missing the custom selector name. This PR adds them.
It also adds the css wrapper class to the builder so CSS changes can be seen in real time in the editor, not just the preview.

Add custom css selector names to additional components

---

src/components/renderer/form-record-list.vue

- Add validation to the Add Record Modal fields.
<a href="https://www.loom.com/share/f14d23dfd3f8490b91a6da0f554652f5"> <p>24 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/f14d23dfd3f8490b91a6da0f554652f5-with-play.gif"> </a>
- Create a screen with a Record List inside
- Create a page with required fields
- Associate this page to the Record List
- Associate this screen to a task in a process
- Run a case
If the Record List page has a required field before adding the record, it validates the required field, preventing adding of empty rows.
closes #550

Fix record list validation

---

src/components/renderer/form-record-list.vue

Fixes #573 
Fields (columns) are not actually reactive when editing the structure so we need to explicitly call normalizeFields when the schema changes. See https://github.com/ratiw/vuetable-2/issues/369

Run normalizeFields on vuetable when table fields change

---

src/components/renderer/form-nested-screen.vue
src/components/vue-form-builder.vue
src/form-builder-controls.js

Resolves #562 
Resolves #561 
The scope variable was removed from nested screen to make easier the user work with variables in nested screens.
Example using tabs and share information between nested and parent screen
Screens:
Main: 
[Company.json.txt](https://github.com/ProcessMaker/screen-builder/files/4262714/Company.json.txt)
Nested:
[Company details.json.txt](https://github.com/ProcessMaker/screen-builder/files/4262717/Company.details.json.txt)

Remove scope variable from Nested Screen

---

src/components/watchers-form.vue

Remove the 'filters' parameter from the 'Source' select when calling the GET method on the 'Data Connector' & 'Script' API.
<a href="https://www.loom.com/share/14bddb0e188b4f379599ac4802d29142"> <p>27 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/14bddb0e188b4f379599ac4802d29142-with-play.gif"> </a>
- Use the [ProcessMaker/#2907](https://github.com/ProcessMaker/processmaker/pull/2907) branch
- Install the Data Source package
- Create 11+ Data Connectors and or Scripts
- Create a new screen
- Add a new watcher select the 'Source' tab.
- Select the 'Source' select list. 
All configured  Data Connectors and or Scripts should be displayed. 
**Dependency** …

Fix Data Connector & Scripts per page limit in the Watcher 'Source' select

---

src/components/renderer/form-record-list.vue
src/components/vue-form-renderer.vue

- Display the 'Add Record' modal form/page when a Record List is in a Multicolumn
- Prevent the submit button from validating Record List form/page in a Multicolumn
- Remove duplicated code.
<a href="https://www.loom.com/share/8d4a4a93b9694048813ed4208fd8e6df"> <p>26 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/8d4a4a93b9694048813ed4208fd8e6df-with-play.gif"> </a>
- Add a configured Record List with a required field to a Multicolumn
- Run a process
- Complete the process WITHOUT adding a new record.
The task is successfully completed.
- Run the process again
- Add a new record and complete the process
The task is successfully completed. …

Fix RecordLists in Multicolumns

---

src/components/vue-form-builder.vue
src/form-builder-controls.js

Fixes #570 
Adds validation if the columns do not add up to 12
Known issue: Custom validatorjs rules do not translate

Add custom validation for multicolumn

---

src/components/renderer/form-nested-screen.vue
src/components/vue-form-renderer.vue

Fixes #566.
The `form-nested-screen` component keeps track of the titles of the screens that were rendered and passes that array down to its child `vue-form-renderer` components. When a nested screen appears for the 2nd time, rendering of that screen is prevented and a warning is displayed.

Fix infinite loop with nested screens

---

src/App.vue
src/components/watchers-form.vue
src/components/watchers-list.vue
src/components/watchers-popup.vue
src/main.js

Fixes #593 
Requires https://github.com/ProcessMaker/package-data-connectors/pull/54
- Service task was failing when no request id was present. See above PR link
- When using a data connector for a watcher, the endpoint was not required. If one was not selected, the service task would fail in the background. This PR adds validation.
- Also fixes the cancel button not reverting changes
- Also fixes validation not running when editing (was only validating on create)
- Also adds ability to do basic watcher development in the standalone app

Fix validation when adding and editing watchers

---

src/App.vue
src/components/vue-form-renderer.vue
src/components/watchers-list.vue
src/main.js

Fixes #565 
If the screen is nested in another screen, this adds a `screen-{id}` prefix for any custom css
This means any css declarations made inside the child screen will only effect the child screen, while also inheriting any CSS from the parent screen (which I believe is the desired behavior)
For Example:
Parent CSS: `label { font-style: italic; }`
Child CSS: `label { color: blue; }`

Scope css inside nestead screens

---

src/components/renderer/form-nested-screen.vue
src/components/vue-form-renderer.vue

Add validation to the Nested Screen component
<a href="https://www.loom.com/share/d782b2ce71e642ea951fbb8f71c8433d"> <p>Edit Screen - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/d782b2ce71e642ea951fbb8f71c8433d-with-play.gif"> </a>
- Import below process
[Nested Screens.json.txt](https://github.com/ProcessMaker/screen-builder/files/4278599/Nested.Screens.json.txt)
- Run the process
- Try to submit the form with no data. 
- Fill out the 'Non Nested' input and submit the form
- Fill out the 'Email' input with an invalid email and submit the form
- Fill out all form fields.
**Expected Behavior** 
The form does not submit when there are validation errors.
closes #605

Add Validation for the Nested Screens component

---

src/components/renderer/form-record-list.vue

A Record List `config` variable defaults to the `$parent.config`. However when a Record list is nested within a `Multicolumn` or `Loop` component, this `$parent.config` is set to the component's config object instead of the `$root` config. 
This PR updates the `config`  variable to the `$root.children[0].config` in a cleaner way when a Record List is nested within a Multicolumn or Loop component. 
- Add a configured Record List within a Multicolumn or Loop component
- Run a process
- Select the `Add Record` button
The configured record list form appears in the Modal.
Ref [#582](https://github.com/ProcessMaker/screen-builder/issues/582#issuecomment-594490189)

Fix Record List in Multicolumn & Loop Component

---

src/components/renderer/form-multi-column.vue
src/components/renderer/form-record-list.vue
src/components/vue-form-renderer.vue

- Reconfigures how the Modal data is being rendered within a Record List. 
- Removes the function that sets variable `formConfig` data  within a record list 
- Passes the `formConfig` variable from form renderer into the record list.
Closes the reopened tickets #582 & #548

Reconfigure  how the modal form data is retrieved in a record list

---

src/form-builder-controls.js

The issue occurs when adding a File Download control, saving the screen, and refreshing.  The RecordList Control was overwriting the File Download inspector configurations after refreshing because they shared the same `editor-control`. This PR prevents the File Download inspector configurations from being overwritten by updating the RecordList `editor-control` key value to `RecordList.` 
<h2>Before</h2>
<a href="https://www.loom.com/share/e6fc964315ca4d84b2afb459807dce8a"> <p>Edit Screen - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e6fc964315ca4d84b2afb459807dce8a-with-play.gif"> </a>
<h2>After</h2>
<a href="https://www.loom.com/share/02f47d20fea74f7989518d29524a480b"> <p>11 March, 2020 - Loom Recording - …

Fix recordlist editor-control config

---

src/components/editor/loop.vue
src/components/editor/multi-column.vue
src/components/vue-form-builder.vue

Add the ability to duplicate a control.
<a href="https://www.loom.com/share/7d6548b5fc9b4a2ca8dd75cc8c14b322"> <p>Edit Screen - ProcessMaker - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/7d6548b5fc9b4a2ca8dd75cc8c14b322-with-play.gif"> </a>
- Create a new screen and add configurations
- Select the duplicate button within the control's header.
- Control is duplicated along with all the configurations. 
- Ability to update the duplicated control configurations.

Duplicate Control

---

src/components/renderer/form-masked-input.vue

<h2>Change</h2>
Add conditional to check if the currency symbol & code are set.
- Create a Form screen
- Add a line input control
- Configure the control to use the `Currency` data type, and use a currency that does not have a symbol, like JPY or EUR
- Save the screen, reload the page, and go to the preview
`null` Does not appear as the currency prefix 
closes #637

Fix Currency Null Amount

---

src/form-builder-controls.js

Fixes #655 
Needs https://github.com/ProcessMaker/vue-form-elements/pull/176
Adds min and max date settings to inspector with validations. Can use mustache syntax

Add min/max settings to date picker

---

src/components/inspector/options-list.vue

Resolves #653 
The option to switch the use of returning keys or objects is enabled for all datasources

Add the option to switch between returning objects or values in SelectList 

---

src/App.vue
src/components/computed-properties.vue
src/components/custom-css.vue
src/components/inspector/column-setup.vue
src/components/renderer/form-record-list.vue
src/components/vue-form-builder.vue
src/components/watchers-popup.vue

Resolves #669 
The property header-close-content="&times;" was added to interactive <b-modal>s used in the UI.

Modal Close Buttons Hidden

---

package-lock.json
package.json
src/form-builder-controls.js

Add an`Render HTML from Variable` checkbox in the inspector panel.
<h3>To Test</h3>
- Add a Textarea control, set the variable name and enable the `rich text` option.
- Add a Rich Text control, in standard mustache syntax input the above Textarea variable name into the content field. `{{ var_name }}`, enable the `Render HTML from Variable` option.
- Switch to Preview Mode, In the Textarea input text and set the Heading to H1.
**Expected Results**
The Rich text control renders the same content and heading.
**Dependency:**
https://github.com/ProcessMaker/vue-form-elements/pull/182
Closes #676

Rich Text Control: Render HTML from Variable checkbox

---

src/components/editor/loop.vue

I changed the `v-model` prop to use the provided alternative `list` as per [vuedraggable docs](https://github.com/SortableJS/Vue.Draggable#list).
Fixes #681

Fix dragging items into / out of loop container

---

src/components/vue-form-renderer.vue

This PR adds an `invalid-form-submission` class when submitting a form with errors. This class is needed to identify when a submitted form contains errors, allowing for the custom CSS to target and display the validation error styling. 
The class may not be required in the future when we refactor how the validation runs. 
Below is the custom CSS needed to remove the validation errors from displaying on page load. 
Validation errors will appear when an element with the class `is-invalid` is selected & when the form submits with errors.
```
/* set the is-invalid class to the default form-control styling */
.is-invalid,
.is-invalid .multiselect__tags {
border-color: #ced4da!important;
padding-right: 0.375rem 0.75rem;
background-position: -99999px!important;
color:#000;
} …
```

Invalid Form Submission Class

---

src/components/renderer/form-masked-input.vue

1. Add switch statement to handle formatting different data types.
2. Convert `localValue` to an ISO string when comparing with the emitted date `value`. Preventing an infinite loop.
3. When using a data type `datetime` compare the `localValue` ISO string with the emitted date `value` ISO string. Preventing the time from not updating correctly.
Dependent PR:
https://github.com/ProcessMaker/vue-form-elements/pull/184
https://www.loom.com/share/125a8f1445954e0c86f38302d4cf5a91
<h2> To Test</h2>
1. Using the above VFE PR `npm link` with screen builder
2. Create a screen with 2 input controls setting the data type to `date` and `datetime`
3. Enter preview mode and input dates, open your console.
Dates properly format and no errors are in your console. …

Fix Date Mask Errors

---

src/components/inspector/validation-select.vue

When rules are deleted update the `cloneRules` index. 
Ref
https://github.com/ProcessMaker/screen-builder/issues/691#issuecomment-625400937

Fix Deleting Rule Error

---

src/form-control-common-properties.js

- Updates confusing wording when choosing type of button
- Requires https://github.com/ProcessMaker/processmaker/pull/3107 for translations
Closes #697.

Update wording of submit button type

---

src/components/inspector/validation-select.vue
src/components/renderer/form-masked-input.vue

- Validate the inputted date is the correct ISO or user date format before emitting the value. 
- Update the Validation select `date` option to use our new `custom-date` validation function.
Dependency: 
https://github.com/ProcessMaker/vue-form-elements/pull/186
https://www.loom.com/share/1dc5ec77573e41859228ea3dd7d13843
<h2>To Test:</h2>
1. Using the above VFE PR npm link with screen builder
2. Create a screen with 2 input controls setting the data type to date and datetime
3. Enter preview mode and input dates 
The infinite loop is no longer triggered.
closes #704

Fix Date & Datetime Infinite Loop

---

src/components/renderer/form-masked-input.vue

The `localValue` variable was not being cleared when navigating pages. This PR clears the variable preventing reactivity issues between multipage forms.
closes #709

Fix Masked Inputs reactivity

---

src/App.vue
src/components/renderer/form-input-masked.vue
src/components/renderer/form-masked-input.vue
src/components/watchers-list.vue

Masking failed for all data types when the screen/page is first loaded. Below are the changes made to fix.
- Set the `localValue` if there is already an emitted `value`. Triggering the `localValue` watcher to mask the data based on the data type.
- Fix a `split on null` console error when adding a `currency` or `percentage` data type. 
https://www.loom.com/share/87e897c18a544545966d808206ef4855
1. `npm link` this branch to pm4 core. 
2. Import and run this process - [Test masking.json.txt](https://github.com/ProcessMaker/screen-builder/files/4623554/Test.masking.json.txt)
3. Fill out all fields and take note of their values.
1. When navigating between the two pages the values are consistent.
2. After the process completes navigate to …

Fix input mask on page load

---

src/components/renderer/form-masked-input.vue

Fixes: #727 
This PR debounce the input changes so the reactivity, calculated fields and watchers do not saturate the screen performance.

Debounce input change

---

src/components/inspector/validation-select.vue

Prevent the "add rule" card from displaying when selecting between different controls.
https://www.loom.com/share/628d507d422b4c818497d563362a31cb
closes #739

Fix the "add rule" card 

---

src/components/inspector/validation-select.vue

Set the multi-select `track-by` config to `content` instead of `value` using `value` highlighted similar values within the options list as preselected when they weren't causing users to double click to select those items.
https://www.loom.com/share/e3c5acfce77b4f2f8c6cf080adf552f4
closes https://github.com/ProcessMaker/screen-builder/issues/691#issuecomment-631449160

Fix validation select 

---

src/components/inspector/validation-select.vue

Disable save validation button when the option is deselected
closes https://github.com/ProcessMaker/screen-builder/issues/691#issuecomment-631664221

Disable Save button

---

src/App.vue
src/DataProvider.js
src/components/inspector/mustache-helper.vue
src/components/inspector/options-list.vue
src/components/vue-form-renderer.vue
src/main.js

Re #747 
Requires https://github.com/ProcessMaker/processmaker/pull/3169
This PR adds a number of changes to the inspector as requested in https://github.com/ProcessMaker/package-data-sources/issues/76
From the issue:
- The value field seems to be empty after filling it out, saving, and reloading the screen builder
- Changing the content field does not always take effect in the Preview pane immediately
- It's not clear which fields accept mustache and which don't
- It's not clear whether dot notation is acceptable in either field
This PR attempts to address these issues with the following fixes:
- Fix the bug that causes the value field to empty
- Fix the bug that causes the preview pane to behave inconsistently
- Add an icon to the field(s) that accepts Mustache syntax
- Update the …

Fix data sources inspector for select list

---

src/components/vue-form-renderer.vue

Resolves #748 
It was added a "debounce" like control to keep track of the last time that a computed property was updated. If this time is less than 100ms, we don't update this property in the transientData, the property will be updated after the 100ms timelapse if a new update is triggered.

Calculated Fields generate infinite loop

---

src/components/inspector/image-variable.vue
src/components/inspector/index.js
src/components/renderer/form-image.vue
src/form-builder-controls.js

1. Refactor the inspector controls for rendering images using variable names. 
2. Add support for rendering base64 images used in the Signature Package. 
closes https://github.com/ProcessMaker/screen-builder/issues/757 & https://github.com/ProcessMaker/package-signature/issues/1

Refactor & Add Signature Package Support

---

src/DataProvider.js
src/form-builder-controls.js

- Fix misnamed variable causing console error when selecting 'Data Connector' as a data source.
- Fix blank 'Type of value returned` select list.
closes #761

Fix Select List Data Connector Error

---

src/components/renderer/form-record-list.vue

Create an `initFormValue` object that restores default values when clearing modal fields. 
https://www.loom.com/share/ede3fb54b4fd434b8694ab99de282aad
- Create an editable Record List some default values
- Select the `Add` button and then select `cancel` or `x` buttons. 
- Select the `Add` button
**Expected Results**
The default value is visible. 
closes #769

Fix Default Values in Record Lists Modal

---

src/DataProvider.js

The Api Instance variable was not being set and defaulting to an empty array due to how screen builder is being loaded. This PR converts the Api Instance variable to a function.
- Install the data connector package
- Create a data connector with endpoints
- Create a new form screen and add the select list control.
- Select the Data Sources accordion and select Data Connector in the drop-down.
**Expected Results**
The `Data Connector` & `Endpoint` select lists are populated with the created data connector.
closes #772  & https://github.com/ProcessMaker/package-data-sources/issues/95

Fix Data Connector Select List

---

src/factories/ValidatorFactory.js

Resolves [FOUR-1761](https://processmaker.atlassian.net/browse/FOUR-1761)
The code that converts dataFormats to validation rules has been restricted to LineInputs, so Select Lists (that generated the problem) aren't affected.

Convert dataFormat to validation rule just for LineInputs

---

src/components/renderer/form-record-list.vue
src/mixins/defaultValues.js

Fixes https://processmaker.atlassian.net/browse/FOUR-1819
The problem was in the order of operations when handling data changes in the loop control. The _parent variable, used for getting and modifying data outside the loop control, is supposed to be removed before handing changes back to parent. If it's not, it creates an endless loop. However, the default value mix-in was operating on the data before the _parent value was removed. The default value mix-in then would set the screen data, including the _parent variable, causing the endless loop.
The fix was to remove the _parent variable, if it exists, in the default values mix-in.

Remove the parent variable before handling default values

---

src/components/renderer/form-record-list.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-1742
The console errors were shown because a watcher was run when the component is mounted that emits the _parent variable,  but the parent variable was still undefined. The _parent variable is what allows a record to read and modify the main screen's data from within a record list entry.
This was showing a console error but did not effect functionality.
The fix was to check that the _parent variable exists before emitting it.

Do not emit if parent var does not exist yet

---

src/App.vue
src/components/vue-form-renderer.vue

The issue was caused by the computed property ignoring the correct emitted value. 
- Changes the debounce method to a 'Trailing Edge' instead of a 'Leading Edge'.
1. Add a select list and configure the 'provideData' data source with an 'Returned Value Type' of `single`
2. Add a new calculated property that returns the value of the select list.
3. Preview the form and select an option from the select list.
In the 'Data Preview' panel the returned value from the calculated property returns a `single` value.
closes #790

Fix Computed Property Returning Object For Select List

---

src/components/renderer/form-loop.vue
src/components/vue-form-builder.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-1832
There were 2 issues. First is that the the default variable names were not auto incrementing like they do for other controls so if you dragged 2 loops onto a screen with out configuring them, they would both have the name "loop".
The loop stores its config differently than other components so the name generator wasn't finding the variable name field.
The solution was to explicitly check if it's a loop control and set the generated value if it is.
Having 2 loops with the same name shouldn't be a problem but it was causing the page to freeze. This was caused by back-and-forth updates between the 2 loops that never finished.
The solution was to check if the loop value had changed after an update. If it did not change, do not try to …

Fix loops with same name freezing and auto-increment names

---

src/factories/ValidatorFactory.js

Fixes https://processmaker.atlassian.net/browse/FOUR-1872
Data format validation should only be applied for FormInput control types.
A check for FormInput was added in https://github.com/ProcessMaker/screen-builder/commit/fcf79bfda6e90b4efebbe306c74c4d321cde8fe0 but it also needs to be added explicitly in the part that handles loops.

Only check FormInput for dataFormat validation in loop

---

src/components/inspector/options-list.vue

Fixes [FOUR-1882](https://processmaker.atlassian.net/browse/FOUR-1882)
When filling the list of data connectors if there is one that doesn’t have endpoints,  a javascript error was generated. Code that handles this null condition has been added.
To test: 
- Create a data source and not add any endpoint to it
- Create a screen and add a select list. Afterwards select as source "Data Connector" 
- With the fix no error will be present in the console and any connector can be used as source.

Select List not populating from a Data Source 

---

src/components/inspector/validation-select.vue
src/components/renderer/form-loop.vue
src/factories/CustomValidationRules.js
src/factories/ValidatorFactory.js

Closes Jira Tickets
- [FOUR-1814](https://processmaker.atlassian.net/browse/FOUR-1814)
- [FOUR-1813](https://processmaker.atlassian.net/browse/FOUR-1813)
- [FOUR-1811](https://processmaker.atlassian.net/browse/FOUR-1811)
- [FOUR-1790](https://processmaker.atlassian.net/browse/FOUR-1790)
This PR fixes the following validations in a Loop control:
`required_if`, `required_unless` & `same`
Issue was due to the validation not running on nested values.
- Register new `custom-same` validation to replace Validator JS `same` validation. 
- Fixes nested validation values to include the loop control name and index.
- Include all missing custom validations with screen builder.
- Fixes the`transientData`variable  from returning empty when mounting a loop element
<h2>Dependency</h2> …

Fix Required_if, Required_unless & Same validations in Loops

---

src/mixins/ScreenBase.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2148
The watcher was being re-triggered when a value was set even if it was the same. This was only effecting arrays, not single values. Added logic to check if the values are the same.

Fix screen freezing when calculated property returns an array

---

src/form-control-common-properties.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2135
Vue does not allow javascript keywords as model names. This adds validation to the Variable Name field to prevent the user from adding reserved keywords

Do not allow reserved keywords as variable names

---

src/mixins/extensions/LoopContainer.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2164
Adds loop context to renderer in loop container. Looks like we forgot to re-add it when refactoring screen builder 2

Add loop context to renderer in loop container

---

src/mixins/watchers.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2313
We need to send the script key, not the script ID, when executing a data source watcher

Send script key when execuiting a data source watcher

---

src/components/task.vue

Conversational Forms were not rendering in regular and web entry tasks due to the wrong `renderComponent` being loaded. SB was missing some previous configurations made to support rendering dynamic components.
This PR fixes the issue by adding back the missing configurations which allowed loading the correct `renderComponent` for conversational forms.

Conversational Forms not rendering in Tasks

---

src/form-builder-controls.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2294
Requires https://github.com/ProcessMaker/processmaker/pull/3491
Adds the file upload and download screen builder controls to the list of default controls after the components were moved into screen builder

Add file upload and download to the default form controls

---

src/components/renderer/form-record-list.vue
src/mixins/extensions/LoadFieldComponents.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2221
- Pass in computed prop settings to all components as `formComputed`
- In the form-record-list component, pass it to vue-form-renderer for add and edit modals

Fix computed properties not working in record lists

---

src/form-control-common-properties.js

Resolves [https://processmaker.atlassian.net/browse/FOUR-2419](https://processmaker.atlassian.net/browse/FOUR-2419)
the string null was added to the list of reserved words for the validation of  variable names

FOUR-2419: The Screen is not show if a create a control with the varible_name = "null"

---

src/mixins/extensions/Watchers.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2367
The watchers were being set up before the defaults were set. This caused the watcher to fire when the defaults were set. Since theres no guarantee what order the extensions are run in, this PR sets up the watchers to listen for changes after the component is mounted (after all the extensions have run)

Setup watchers after the component mounts so defaults are already set

---

src/components/renderer/form-record-list.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-2415
The key name for setting a table header title was wrong. It's supposed to be `label`

Bootstrap vue table field key should be label, not title

---

src/mixins/Json2Vue.js
src/mixins/extensions/DataManager.js
src/mixins/extensions/DefaultValues.js
tests/e2e/fixtures/default_values_with_computed_fields.json
tests/e2e/specs/DefaultValuesWithComputedFields.spec.js
tests/e2e/support/commands.js

Fixes: https://processmaker.atlassian.net/browse/FOUR-2422
This PR fixes use of computed fields in default values
```
Test case
Define calculated properties:
- varA = 1
- res = ok
Control with default value:
- uno = {{varA}}
Expected response:
{
varA: 1,
res: "ok",
uno: 1
}
```
[default_values_with_computed_fields.json.txt](https://github.com/ProcessMaker/screen-builder/files/5660473/default_values_with_computed_fields.json.txt)

Fix computed property freeze when used in default value

---

src/components/renderer/form-loop.vue
src/components/renderer/form-multi-column.vue
src/components/renderer/form-record-list.vue
src/components/vue-form-renderer.vue

Fixes: https://processmaker.atlassian.net/browse/FOUR-2436
This PR fixes the popup config used in record-list in different cases:
- In the root of the page
- Inside a nested screen
- Inside a loop
- Inside a multicolumn
- Inside a multicolumn/loop
[Screen FOUR-2436_4_0.json.txt](https://github.com/ProcessMaker/screen-builder/files/5668253/Screen.FOUR-2436_4_0.json.txt)

Fix Four-2436 record list inside a nested screen does not work

---

src/components/vue-form-builder.vue

- Sorts screen builder controls alphabetically by translated label
- Utilizes JavaScript's Internationalization API to sort properly per language
Closes https://processmaker.atlassian.net/browse/FOUR-2507.

Sort Screen Builder controls alphabetically

---

src/mixins/extensions/LoadFieldComponents.js

Part of https://processmaker.atlassian.net/browse/FOUR-1837
The render component has a different name in email screens. Need to exclude it from content modification

Pass unmodified content to FormHtmlEditorStatic

---

src/components/task.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-2540
We might miss the broadcast event if the task is ready before the web socket is initialized. Fix is to always check for a waiting task after web sockets are initialized.

Check for any waiting task after websockets are initialized

---

src/components/renderer/form-image.vue

Resolves [FOUR-2534](https://processmaker.atlassian.net/browse/FOUR-2534)
Fixes image styles when they overflow their container
Before:
After:

FOUR-2534: Controls overlap on top of others

---

src/mixins/Json2Vue.js

- Allows components to set a property `ignoreMustache` to `true` to avoid having their properties rendered by mustache
- This is necessary for components that render mustache internally; specifically in this case, the Collection Record component
- Allow components to update their configuration
- Components can update their configuration by listening for the `screen-renderer-build-component` event and calling the `updateComponentConfig` method with the component name and the updated configuration (for an example of this, see the [corresponding Collections PR](https://github.com/ProcessMaker/package-collections/pull/233/files#diff-0ee38169882816d584d23f4eb5cf4d4265b7912d93e5875be6df481dc2610a2eR21-R23))
- This is necessary to allow older versions of components on older screens to utilize …

Fix issue with mustache rendering fields it should ignore

---

src/components/renderer/form-record-list.vue

This code was incorrectly restored in the PR #878.
This PR removes a watcher referencing old vuetable2 component

Remove vuetable watcher not required anymore

---

src/components/renderer/form-nested-screen.vue
src/components/vue-form-renderer.vue
src/factories/ValidatorFactory.js
src/main.js

Fixes https://processmaker.atlassian.net/browse/FOUR-2550
We were checking validation using $children. This only has items for the current page. This fix saves nested screens in the global object when loaded then retrieves them when validating.

Fix nested screen validation when submitting from another page

---

src/components/task.vue

https://processmaker.atlassian.net/browse/FOUR-2558
- Add `screenTypeClass` to the `task` component. This allows us to enable specific CSS styling for conversational type screens in embedded web entry forms.
<h2>Dependency PRs</h2>
https://github.com/ProcessMaker/package-webentry/pull/101

Add screen type class for conversational forms

---

src/components/inspector/outbound-config.vue
src/components/watchers-form.vue

Fixes: [https://processmaker.atlassian.net/browse/FOUR-2710](https://processmaker.atlassian.net/browse/FOUR-2710)
When the source type (from script to data_source for example) the script configuration is reset to {}

FOUR-2710: Watcher UI not being cleaned up when switching source type

---

src/components/watchers-form.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-2750](https://processmaker.atlassian.net/browse/FOUR-2750)
The script configuration parameter didn't have reactivity. Code to fix this was added.

FOUR-2750: Outbound configuration is lost when addid data mapping items

---

src/components/inspector/validation-select.vue

https://processmaker.atlassian.net/browse/FOUR-2751
- Remove code causing the configuration panel to disappear on the first load.
- Fix loading the rules configurations panel by properly formatting the configured rule accordion id. For example, the accordion id for the rule `After Date` is now `after-date` 
**Video**
https://www.loom.com/share/ae06d5bc148540d099bd3bc1c8783fc7

Fix loading of the rules configuration panel

---

src/components/task.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-2778
A tasks's existing request data might load after the screen has loaded its initial variables and default values. This PR merges the request data instead of overwriting it.

Merge existing request data instead of overwriting

---

src/components/task.vue

Fixes part of https://processmaker.atlassian.net/browse/FOUR-2773
- It was emitting the wrong value with the complete event. This fixes it

Emit the correct value when the process completes

---

src/components/task.vue

https://processmaker.atlassian.net/browse/FOUR-2765
The issue was caused by the 'Task' component overwriting the screen data when loading the request data. This PR adds a `refreshScreen` variable to refresh the screens data after the request data has loaded.
- Create a screen with a loop control configured.
- Create and run a process that uses the above screen.
The Loop control properly loads with no console errors.

Fix loading loop control within a request

---

src/components/inspector/input-variable.vue
src/components/inspector/validation-select.vue

https://processmaker.atlassian.net/browse/FOUR-2751
- Fixes issue where the validation 'Cancel' & 'Update' buttons were not closing the accordion. 
- Fixes issue where selecting the 'Cancel' button on one element validations updated the validation for another element. Due to the `cloneRules` variable not clearing. 
- Fixes console error due to running a 'replace' method on an empty value.

Fix validation accordion not closing 

---

src/factories/ValidatorFactory.js

<h2>Jira Ticket</h2>
[https://processmaker.atlassian.net/browse/FOUR-2824](https://processmaker.atlassian.net/browse/FOUR-2824)
The ValidatorFactory was not registering our custom validation rules causing some rules such as the 'Before Date' & 'After Date' validations to fail when submitting a form in the collections package. This PR imports the file that registers our custom validation rules.
**Video**
https://www.loom.com/share/a31aa6e3d4f246c4a8471f7053f7c637

Fix Custom Validation Rules for Collection Forms

---

src/components/renderer/form-record-list.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-2849](https://processmaker.atlassian.net/browse/FOUR-2849)
The problem was caused because the record list, when inside a multicolumn, overflowed and its div finished at the bottom of the other multicolumn cells. 
**For example with 3 cells:**
**If using just one cell all the width is used and no overflows occurs:**
The same problem was present in this already resolved ticket https://processmaker.atlassian.net/browse/FOUR-2534

FOUR-2849: I cannot edit or delete a row in record list

---

src/form-control-common-properties.js

https://processmaker.atlassian.net/browse/FOUR-2873
This PR updates the Variable Name regex validation to surface and 'Invalid variable name' error for variable names that include dot notation followed by a digit. ex `variable_name.1` 
**Video**
https://www.loom.com/share/ece836865fb34806826ab15c46e039f7

Update Variable Name Field REGEX validation

---

src/components/renderer/form-record-list.vue

https://processmaker.atlassian.net/browse/FOUR-2917
Sets the Record List columns max-width preventing screen distortion when loading larger data like the signature package base64 image code. 
**Video**
https://www.loom.com/share/6c098d0e2c234dd4bb1f2ccc3c976769

Fix record column width when displaying signatures

---

src/components/renderer/form-record-list.vue
src/mixins/extensions/LoadFieldComponents.js

Fixed [FOUR-2465](https://processmaker.atlassian.net/browse/FOUR-2465)
- Enable watchers in modal recordlist

[ZenDesk 22843] Watchers in record lists are not working in nested screens

---

src/components/renderer/file-upload.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-2953](https://processmaker.atlassian.net/browse/FOUR-2953)
Code that deletes all files withing a record or loop (even if they are nested) has been added.

FOUR-2953: The files of a record list that are in loop control, are not deleted after deleting the entire row of record lists

---

src/components/task.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-2979
- Removed the request queue, it wasn't doing anything
- Checks if we're already showing the appropriate task and doesn't attempt to reload it if we are
TESTING
You can trigger the endless reloading/flashing more often by doing this in CORE. 
- In ProcessMaker/Http/Controllers/Api/TaskController.php show function, add a sleep if the node matches the first form task:
```
public function show(ProcessRequestToken $task)
{
if ($task->element_id === 'node_1') {
sleep(2);
}
return new Resource($task);
}
```
- in ProcessMaker/Repositories/TokenRepository.php at the end of persistActivityCompleted but before calling notifyProcessUpdated, add another sleep
```
$request = $token->getInstance();
sleep(2); …
```

Fix screen interstitial endless reload bug

---

src/components/task.vue

Fixes https://processmaker.atlassian.net/browse/FOUR-3175
Interstitials after advanced screens were not showing because we were checking the task component, which in this case was "AdvancedScreen". In reality, the interstitial is always a "task-screen" so we needed to set a property when switching to an interstitial indicating it is one. Then the screen watch checks for that property and, if set, always renders it as a "task-screen"
NOTE: need separate PR to add fix to develop (4.2)

Fix interstitial after advanced screen not showing

---

src/components/watchers-form.vue
src/mixins/watchers.js

Fixes [https://processmaker.atlassian.net/browse/FOUR-3182](https://processmaker.atlassian.net/browse/FOUR-3182)
-Removed the clearing of variable to watch when changing between setting on/off the run on load option
-Fix bug associated with filling the output variable with all response data when a data source was used

FOUR-3182-B: Watcher is not working

---

src/form-control-common-properties.js

Jira Ticket
https://processmaker.atlassian.net/browse/FOUR-3214
The issue only occurs when using the Safari browser. When mounting a Form Input control or when saving / previewing a screen with a Form Input control the following error appeared.
`SyntaxError: Invalid regular expression: invalid group specifier name`
This was caused by the `Variable Name` regex including a negative look-behind assertion that Safari does not support.
- Remove the unsupported negative look behind for Safari
**Video**
https://www.loom.com/share/88456a0d626549bfb6254a4c5bc192c5

Fix Screen saving in Safari

---

src/components/renderer/form-record-list.vue

Fixes [https://processmaker.atlassian.net/browse/FOUR-3210](https://processmaker.atlassian.net/browse/FOUR-3210)
The tracking of the Record List current page has been fixed.

FOUR-3210: Record list updating the wrong record when more than one page of records

---

src/mixins/ValidationRules.js

Fixes https://processmaker.atlassian.net/browse/FOUR-3409
Change to an old style function so we have access to `this`, which vuelidate binds to the current $vm.
Tech note: I think there's a bug in vuelidate since the old format should have worked with the 2nd param being the $vm, but instead, its a subset of the data. Strange.

For sameAs, validate against entire vdata, not just subset

---

src/mixins/ScreenBase.js

Fixes [FOUR-3673](https://processmaker.atlassian.net/browse/FOUR-3673)
- validate exists variable  parent in load variables

_parent variable does not seem to be working

---

src/App.vue

Fixes: https://processmaker.atlassian.net/browse/FOUR-3699
Safari does not support regular expressions with **lookbehind**. This was used previously and some screens still store this expressions in its json definition.
https://caniuse.com/js-regexp-lookbehind
This PR prevents that errors during validation check break the screen builder loading

Prevent errors during validation break the screen builder loading

---

src/mixins/watchers.js

Fixes [https://processmaker.atlassian.net/browse/FOUR-3575](https://processmaker.atlassian.net/browse/FOUR-3575)

FOUR-3575:  returned data is mixed when the watcher runs at the same time in two different sessions

---

package-lock.json
package.json

The old version allowed the user to put the cursor at the end and start typing, resulting in wrong comma placement:
Upgrading forces the user to put the cursor in the correct position

Upgrade inputmask package

---

src/components/renderer/file-upload.vue

Fixes http://tickets.pm4overflow.com/tickets/595
This fix is already in 4.2

Fix non-unique ids

---

src/components/inspector/options-list.vue
src/components/inspector/validation-select.vue

Fixes [http://tickets.pm4overflow.com/tickets/599](http://tickets.pm4overflow.com/tickets/599)
- Border when deleting a validation rule has been removed.
- Padding and border-radius inside .card are configured in our in app.scss file. They were left untouched to avoid a modification that will affect all elements that use this css class accross our application.
Before:
After:

ticket 599: Validation Delete Confirmation UI

---

src/components/renderer/file-upload.vue
tests/e2e/specs/FileUpload.spec.js

Fixes http://tickets.pm4overflow.com/tickets/142
Disables the select file button and drag/drop when the task is self service
Requires: https://github.com/ProcessMaker/processmaker/pull/4030
4.1 Equivalent: https://github.com/ProcessMaker/screen-builder/pull/1056

Disable file upload for unclaimed self service tasks (4.2)

---

src/components/renderer/file-upload.vue
tests/e2e/specs/FileUpload.spec.js

Fixes http://tickets.pm4overflow.com/tickets/142
Disables the select file button and drag/drop when the task is self service
Requires: https://github.com/ProcessMaker/processmaker/pull/4029
4.2 Equivalent: https://github.com/ProcessMaker/screen-builder/pull/1057

Disable file upload for unclaimed self service tasks (4.1)

---

src/components/renderer/file-upload.vue

**Changes**:        
The `package-files` package uses ScreenBuilder's file-upload component.
- In the `package-files@AddPublicFile.vue` modal component, the name of the uploaded file is expected, for that reason we return the file name instead of an empty string.
- Change only in `ScreenBuilder@file-upload.vue`
**Fixes**:
- http://tickets.pm4overflow.com/tickets/745.

Ticket #745 Missing filename in Uploaded Files URL (for 4.2)

---

src/components/renderer/file-upload.vue

**Changes**:
The `package-files` package uses ScreenBuilder's file-upload component.
- In the `package-files@AddPublicFile.vue` modal component, the name of the uploaded file is expected, for that reason we now return the file name instead of an empty string.
- Changes only in `ScreenBuilder@file-upload.vue`
**Fixes**:
- http://tickets.pm4overflow.com/tickets/745.

Ticket #745 Missing filename in Uploaded Files URL (for 4.1)

---

src/mixins/VisibilityRule.js

This PR fixes an infinite loop with the **Rich Text** control that has a **Visibility Rule** configured.
- Checks to see if the passed `fieldName` exists. Rich Text controls (there may be some others) do not have a `name` property.

4.1 Fix Visibility Rule Infinite Loop with the Rich Text control 

---

src/App.vue

This PR adds missing style in json preview:

Add missing style in json preview

---

src/components/inspector/loop.vue

Ticket:
- Remove the editable Loop inspector configs for Display screens.

Remove editable Loop inspector configs for Display screens

---

src/mixins/Json2Vue.js
src/mixins/extensions/DefaultValues.js
tests/e2e/fixtures/FPP_PFP_CHAIRS_SCREEN.json
tests/e2e/specs/LoadComplexData.spec.js

Ticket: http://tickets.pm4overflow.com/tickets/1206
Ticket: http://tickets.pm4overflow.com/tickets/1198
https://processmaker.atlassian.net/browse/FOUR-3488
Problem: A default value (null) is overwriting the object of another one:
Select List Control: FPP_USER_PART_TIME   Default: null
Input Text Control: FPP_USER_PART_TIME.FPP_NAME_PART_TIME Default null
The `Select List Control` was overwriting FPP_USER_PART_TIME to `null`, causing the Input Text Control to fail.
- Test to replicate the issue. Now the user could open the second tab
- Fix: Default value does not overwrite a declared variable (e.g. FPP_USER_PART_TIME.FPP_NAME_PART_TIME)
Screen:
[FPP_PFP_CHAIRS_SCREEN .json.txt](https://github.com/ProcessMaker/screen-builder/files/7476979/FPP_PFP_CHAIRS_SCREEN.json.txt)

Fix: Page Navigation does not work if the data does not provided FOUR-3488

---

package-lock.json
package.json
src/components/inspector/options-list.vue
tests/e2e/fixtures/select_list_array_data.json
tests/e2e/fixtures/select_list_mustache.json
tests/e2e/fixtures/select_list_mustache_custom_key.json
tests/e2e/fixtures/select_list_mustache_request_data.json
tests/e2e/specs/SelectListMustache.spec.js

Fixes: http://tickets.pm4overflow.com/tickets/1205
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/293
- Tests to replicate issues with mustache in Select Lists
- Add missing config option "key" for data sources

Fix mustache replacement in SelectLists

---

src/mixins/extensions/DefaultValues.js
tests/e2e/specs/ComplexScreen.spec.js

Ticket [FOUR-4329](https://processmaker.atlassian.net/browse/FOUR-4329)
Default checkbox value in second page was setted to null instead false, so when moving to second page, the value of the checkbox that initially was null changed to false and watcher was detecting that reactivity. Now checkbox is setted as false instead null.
https://user-images.githubusercontent.com/90727999/141355450-733395d1-9728-4c74-940c-a4373696c025.mov

Bugfix/FOUR-4329: Fixed watcher triggering on a second page with checkbox (FOR 4.2)

---

src/components/task.vue
src/mixins/ScreenBase.js

<h2>Issue</h2>
https://processmaker.atlassian.net/browse/FOUR-4471
When the Vocabulary Package is **NOT** installed, the endpoint `/api/1.0/vocabularies/task_schema/{task_id}` was still triggered when loading a task, causing a `404` error.
<h2>Reproduce</h2>
1. Install the `packages` package
2. Install the `package-vocabularies` package
3. Create a simple process with a FormTask and run
4.  Uninstall the `package-vocabularies` package
5. Run the same process
** Bug Behavior**
Error alerts appear in the UI. In the Network tab there are Not found `404` requests to the `/api/1.0/vocabularies/task_schema/{task_id}` endpoint
<h2>Cause</h2>
The vocabulary package must have been previously installed on the server then later uninstalled. The logic that checks to see if the vocabulary package is …

Fix call to Vocabulary API when Vocabulary package not installed

---

package-lock.json
package.json
src/components/inspector/options-list.vue
tests/e2e/fixtures/select_list_checkbox_collection.json
tests/e2e/fixtures/select_list_collection.json
tests/e2e/fixtures/select_list_dependent.json
tests/e2e/fixtures/select_list_multiselect_collection.json
tests/e2e/fixtures/select_list_radio_collection.json
tests/e2e/specs/ComplexScreen.spec.js
tests/e2e/specs/LoadComplexData.spec.js
tests/e2e/specs/SelectListCollection.js
tests/e2e/specs/SelectListCollection.spec.js
tests/e2e/specs/SelectListDependent.spec.js
tests/e2e/specs/SelectListMustache.spec.js

Fixes: https://processmaker.atlassian.net/browse/FOUR-4516
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/308
- Hide Value field at inspector for SelectList Object Type
- Ad tests for SelectList using Collections:
- SelectList Object Type / Value Type
- SelectList (Radio) Object Type / Value Type
- SelectList (Checkbox) Object Type / Value Type
- SelectList (MultiSelect) Object Type / Value Type
The tests include patterns for:
- Content not using variable reference of two levels e.g. `data.location.city`
- Content mustache e.g. `{{data.location.city}} - {{data.location.country}}`
- Content not using variable reference of one level e.g. `data.name`
https://user-images.githubusercontent.com/8028650/142298502-88c6baf0-ac31-4636-ad72-afd93053050e.mp4

Fix Select List change of behavior

---

src/DataProvider.js
src/components/renderer/file-download.vue
src/components/renderer/file-upload.vue
tests/e2e/specs/MultipleUpload.spec.js

Fixes https://processmaker.atlassian.net/browse/FOUR-4406
Complete refactor of multi-file uploads to fix issues in ticket.
Requires
- https://github.com/ProcessMaker/processmaker/pull/4169
- https://github.com/ProcessMaker/package-webentry/pull/128
- https://github.com/ProcessMaker/package-files/pull/65
To test, try a variety of single and multi-upload enabled file upload components and download components in a screen in a variety of scenarios
Notes
- file download auto-detects if it was a multi-upload, there is no inspector option to enable mulit-file uploads in the download component.
- To test in a loop, set the loop variable name to the same as the multi-file upload. Inside the loop, the file variable is always named "file"

Fix multi-file uploads

---

src/components/renderer/file-upload.vue
src/mixins/VisibilityRule.js

the scenario to replicate is to have a screen with a nested screen plus a loop and to have a require if validation rule.
- have a loop 
- inside the loop a component fileUpload and nested screen with validation rules and visibility fields.
- add a timer to function refresh validation rules
- add new ignore error to component fileUpload
- import process and thread
- run the case until the described form is reached.
https://user-images.githubusercontent.com/1747025/144914670-3bb3a9cc-711e-4be8-9199-95b16d6543e0.mp4
- [FOUR-4259] (https://processmaker.atlassian.net/browse/FOUR-4259)
- [] I have extracted this code locally and tested it on my instance, along with the associated packages.
- [] This code adheres to the [ProcessMaker Coding Guidelines] …

The screen freeze with loop

---

src/components/vue-form-builder.vue
tests/e2e/specs/CustomCss.spec.js

<h2>Issue</h2>
Ticket: [FOUR-4844](https://processmaker.atlassian.net/browse/FOUR-4844)
Per the documentation for [adding custom CSS styling](https://processmaker.gitbook.io/processmaker/designing-processes/design-forms/screens-builder/add-custom-css-to-a-screen#add-custom-css-to-a-processmaker-screen).  Custom CSS styles should display in Preview mode and NOT Design mode. Currently, custom CSS displays in both modes.
<h2>Solution</h2>
- Remove the `custom-css-scope` class that renders Custom CSS in Design Mode.
- Add a test to ensure CSS styles do not display in Design mode
<h2>To Replicate / Test</h2>
1. Add a Line Input control to the screen
2. For the control, configure a custom CSS selector under the 'Advanced' accordion
3. Add CSS for the selector in the Custom CSS modal
**Correct …

Fix Custom CSS Styles rendering on elements in Design mode

---

src/components/renderer/file-upload.vue

Ticket: [FOUR-4125](https://processmaker.atlassian.net/browse/FOUR-4125)
<h2>Issue</h2>
When uploading a public file the modal does not display the file data in the Upload Tray.  This was caused by not emitting the file name in the `fileUploaded` method when the `message` variable is not set. 
<h2>Solution</h2>
- Add `else` condition when the `message` variable is not set and emit the uploaded file name.
<h2>To Replicate</h2>
1. Under the file manager add a new public file
2. Upload a file.
The uploaded file information does not display in the Uploaded Files tray
see video
https://user-images.githubusercontent.com/52755494/145288720-de279fbb-60f6-454f-add8-61c51279b40c.mov
<h2>Related PR's</h2>
https://github.com/ProcessMaker/package-files/pull/66
<h2> To Test</h2>
1. …

Missing uploaded public file data in modal

---

src/components/renderer/add-loop-row.vue
src/mixins/ValidationRules.js
src/mixins/extensions/LoopContainer.js

the scenario to replicate is with json schema (package-vocabulary)
- add message and section for display error in component loop.
- Create a Vocabulary to validate the maximum Item of a loop_1
- Create a Screen with a Loop (loop_1)
- Create a process with that screen assigned to a Task
- Assign the created vocabularyto to the Task
- Run the process,  the loop passes with any number of items
https://user-images.githubusercontent.com/1747025/145604066-339c2166-17c4-46f3-9f05-d973756053f7.mp4
- [FOUR-4785] (https://processmaker.atlassian.net/browse/FOUR-4785)
- [] I have extracted this code locally and tested it on my instance, along with the associated packages.
- [] This code adheres to the [ProcessMaker Coding Guidelines] …

Fix Vocabulary Array Max Items Validation

---

src/mixins/VisibilityRule.js

the scenario to replicate is to have a screen with a nested screen plus a loop and to have a require if validation rule.
- have a loop 
- inside the loop a component fileUpload and nested screen with validation rules and visibility fields.
- add a timer to function refresh validation rules
- add new ignore error to component fileUpload
- import process and thread
- run the case until the described form is reached.
https://user-images.githubusercontent.com/1747025/144914670-3bb3a9cc-711e-4be8-9199-95b16d6543e0.mp4
- [FOUR-4259] (https://processmaker.atlassian.net/browse/FOUR-4259)
- [] I have extracted this code locally and tested it on my instance, along with the associated packages.
- [] This code adheres to the [ProcessMaker Coding Guidelines] …

[4.2] The screen freeze with

---

src/DataProvider.js

Fixes [https://processmaker.atlassian.net/browse/FOUR-4901](https://processmaker.atlassian.net/browse/FOUR-4901)
The problem was caused because the screen definitions were added when the API call response arrived but at that time, n requests were already dispatched, so "n" API calls were made.  Now we'll catch promises instead of screen definitions.
To test:
- Import the attached screen 
[Screen Many nested.zip](https://github.com/ProcessMaker/screen-builder/files/7737310/Screen.Many.nested.zip)
- Associate the screen to a collection
- Create a new record for the collection
- Verify that just one network call to retrieve the nested screen is made.
Before:
After:

FOUR-4901: "Time outs" in collection in screen with several nested screen with select list with variables object 

---

src/mixins/computedFields.js

To reproduce the problem:
screen: [FOUR-4853.json.txt](https://github.com/ProcessMaker/screen-builder/files/7737838/FOUR-4853.json.txt)
Create a calculated prop called `output` with js `return this.foo.one`;
Create a screen with an input name `foo.two`
Create a rich text that shows the `output` variable
Go to preview and add this example input data
```
{
"foo": {
"one": "one",
"two": "two"
}
}
```
Expected: output should show `one`
Actual result: no output
The problem is that the calculated props input data is not merged with the vdata.
Proposed solution is to merge those objects
Need to make sure this solution does not break the solution for https://processmaker.atlassian.net/browse/FOUR-2797

Include vdata in nested calculated props

---

src/DataProvider.js
src/components/screen-renderer.vue
src/mixins/Json2Vue.js
tests/e2e/specs/NestedCalcRadioFreeze.spec.js

Fix: https://processmaker.atlassian.net/browse/FOUR-4925
- Since validation rules object contains Function, isEqual do not check properly if validations have changed
- Visibility rules could trigger multiple times at once the re-render of the screen
- Some nested screens are loaded 
- Improve the comparition of validation rules
- Add a debounce to re-render screen function
- Include https://github.com/ProcessMaker/screen-builder/pull/1130 to cache properly the screens
- Import the attached process
- Open the main screen in preview or Run the process
- Navigate through the tabs, some of them take time to render
Attached files:
[Test Performance Process.zip](https://github.com/ProcessMaker/screen-builder/files/7764303/Test.Performance.Process.zip)

Improve render screen 4.1

---

src/components/screen-renderer.vue
src/mixins/Json2Vue.js
tests/e2e/specs/NestedCalcRadioFreeze.spec.js

Fix: https://processmaker.atlassian.net/browse/FOUR-4925
- Since validation rules object contains Function, isEqual do not check properly if validations have changed
- Visibility rules could trigger multiple times at once the re-render of the screen
- Some nested screens are loaded 
- Improve the comparition of validation rules
- Add a debounce to re-render screen function
- Requires https://github.com/ProcessMaker/screen-builder/pull/1130 to cache properly the screens
- Import the attached process
- Open the main screen in preview or Run the process
- Navigate through the tabs, some of them take time to render
Attached files:
[Test Performance Process.zip](https://github.com/ProcessMaker/screen-builder/files/7764303/Test.Performance.Process.zip)

Improve render screen 4.2

---

src/mixins/Json2Vue.js
src/mixins/extensions/LoadFieldComponents.js
tests/e2e/specs/ComputedFieldsReadOnly.spec.js

We're supposed to prevent elements from modifying calculated properties by making them read-only. This is not working when the element references a sub object.
1. Create a calculated property called `object` and have it run javascript `return { foo: "bar" };`
2. Add a input element and name it `object.foo`
3. Go to preview
Expected behavior: The element is read only
Actual behavior: User can type in the element
- Check if the first part of the elements name (up to the first `.` if any) matches the name of a computed property, and if so, make the element read-only;
Test the the steps above
- https://processmaker.atlassian.net/browse/FOUR-4938
- Found while testing https://processmaker.atlassian.net/browse/FOUR-4915

Make elements read-only if they use a sub object of a computed property

---

src/components/inspector/validation-select.vue

A console error shows when you add a text area and immediately add another and select the unselected textarea
- Add a textarea 
- Immediately add a second textarea
- Click on the other text area
- You will see an error in console
- If value is undefined set an empty array
- Add a textarea 
- Immediately add a second textarea
- Click on the other text area
- You will NOT see an error in console
https://user-images.githubusercontent.com/90727999/147284978-6da4e724-3cac-4b5c-9052-d313c1907e01.mov
- [FOUR-4953](https://processmaker.atlassian.net/browse/FOUR-4953)

Bugfix/FOUR-4953: Console error, when I click on a created text area (FOR 4.1)

---

src/mixins/extensions/DefaultValues.js

This appears to be an order of operations issue. The logic that sets the default value is running after the the data is updated. This is somewhat expected since some default values rely on (using mustache syntax) other values in the data that could change.
Steps to reproduce:
1. Create a watcher or select list that uses a data source or a script that sets a variable with nested data: `{ output: { foo: 'bar'} }`
1. Create a form input and set the variable name to output.foo
1. Add a default value to the input field: abc
1. Preview and activate the watcher
1. Expected result: output.foo input field changes to bar
1. Actual result: output.foo input field does not change, stays abc
Instead of re-ordering the methods that change the data, or skipping the default value setting logic if it …

Do not reset default values on nested objects after a data has changed

---

src/components/renderer/form-record-list.vue

When you have a textarea with rich text option enabled inside recordlist, the textarea shows but editing is disabled because the modal is not showing.
Reproduction steps:
- Create a  screen
- Create a  record list 
- Create a  new  page 
- Create  loop
- Inside loop create  text area
- Enable rich text  option in text area
- Click on preview and open the modal (Add)
- The rich text area are showing but you are not able to edit the data
- NOTE: you can import the attached screen
- Reboot the textarea on modal shown
- Create a  screen
- Create a  record list 
- Create a  new  page 
- Create  loop
- Inside loop create  text area
- Enable rich text  option in text area
- Click on preview and open the modal (Add)
- The rich text area are showing and you are able to edit the data
- NOTE: you …

Bugfix/FOUR-4955: The first item of a loop with text area rich text, in a record list does not work

---

src/components/renderer/form-record-list.vue

When you have a textarea with rich text option enabled inside recordlist, the textarea shows but editing is disabled because the modal is not showing.
Reproduction steps:
- Create a  screen
- Create a  record list 
- Create a  new  page 
- Create  loop
- Inside loop create  text area
- Enable rich text  option in text area
- Click on preview and open the modal (Add)
- The rich text area are showing but you are not able to edit the data
- NOTE: you can import the attached screen
- Reboot the textarea on modal shown
- Create a  screen
- Create a  record list 
- Create a  new  page 
- Create  loop
- Inside loop create  text area
- Enable rich text  option in text area
- Click on preview and open the modal (Add)
- The rich text area are showing and you are able to edit the data
- NOTE: you …

Bugfix/FOUR-4955: The first item of a loop with text area rich text, in a record list does not work (For 4.2)

---

src/form-control-common-properties.js
tests/e2e/specs/Builder.spec.js

See https://processmaker.atlassian.net/browse/FOUR-4972
Instead of supporting array indexes in variable names, update the regex to prevent referencing them.
Add an input with a variable name that references an array index like `aaa.0.bbb`. The variable should be invalid.
- https://processmaker.atlassian.net/browse/FOUR-4972

Prevent referencing array index in variable name

---

tests/e2e/specs/DatePicker.spec.js

Reproduction steps
- Create a screen with 2 datepickers (date1 and date2)
- In date2 in Configuration section, add {{date1}} in Minimum Date field.
- Go to preview and select a date in date1
- Date2 will set the minimum date to the selected date - 1
Removed timeZone in config. 
- Create a screen with 2 datepickers (date1 and date2)
- In date2 in Configuration section, add {{date1}} in Minimum Date field.
- Go to preview and select a date in date1
- Date2 will set the minimum date to the selected date
https://user-images.githubusercontent.com/90727999/148285428-d2efd318-5ad4-49e7-a1de-4137f84c6202.mov
- [FOUR-4950](https://processmaker.atlassian.net/browse/FOUR-4950)
- [PR vue-form-elements](https://github.com/ProcessMaker/vue-form-elements/pull/325)

Bugfix/FOUR-4950: e2e tests for Field Date picker does not correctly validate the minimum date (For 4.1)

---

src/ValidationsFactory.js
tests/e2e/specs/Loop.spec.js

Ticket: [FOUR-5076](https://processmaker.atlassian.net/browse/FOUR-5076)
Hidden fields with validations in loops are being validated, preventing form submission.
<h2>To Reproduce:</h2>
1. Create a screen
2. Add loop with the next configuration:
3. Data source: Existing Array
4. Variable Name: accounts
5. Add line input 
6. Add validation between Min-Max
7. Add visibility rule: product  != "dos" ; in such a way that one records are visible and others are not 
8. Press the preview button
9. Populate the accounts loops with the next data
```
{
"accounts": [
{
"product": "uno",
"initialDeposit": 0
},
{
"product": "dos"
}
]
}
```
10. Fill the data with validations
11. Press submit button
The form submits with no errors.
The form does not submit due to …

Fix Loop running validations on hidden fields

---

src/components/renderer/form-record-list.vue

- create a screen with recordlist
- add a vocabulary
- add new register to recordlist
- does not allow adding new records to the record list.
- allow adding new records to the record list.
does not allow adding new records to the record list.
- validation only vdata in recordlist
- [FOUR-5176](https://processmaker.atlassian.net/browse/FOUR-5176)
https://user-images.githubusercontent.com/1747025/150209455-b241ee3e-82dd-4bfd-8f63-a2b9cf93dc63.mp4

[4.2] A record cannot be added to the Record List, if the screen has a vocabulary

---

src/components/task.vue
tests/e2e/specs/Task.spec.js

Ticket [FOUR-5146](https://processmaker.atlassian.net/browse/FOUR-5146)
Issue is due to the `PM4ConfigOverride.getScreenEndpoint` variable being hardcoded.  The task IDs are not updating to the latest task causing an error when trying to load an interstitial on a task that is followed by a script task. 
1. Ensure you have a non-admin user created
2. Import this process
[test.json.txt](https://github.com/ProcessMaker/screen-builder/files/7947122/test.json.txt)
3. Assign the start permissions to a non-admin user
4. log in as the user and run the process
5. On the first task select 'Button B'
No errors when displaying an interstitial
After completing the task an error is displayed when loading the interstitial. 
- Update the …

Fix hardcoded PM4ConfigOverride Screen Endpoint 

---

src/ValidationsFactory.js
tests/e2e/specs/Loop.spec.js

[FOUR-5077](https://processmaker.atlassian.net/browse/FOUR-5077)
1. Create a screen
2. Add loop with the next configuration:
3. Data source: Existing Array
4. Variable Name: accounts
5. Add Multicolumn
6. Add visibility rule: `required` ; to the multicolumn
7. Add line input
8. Add validation between Min-Max
9. Press the preview button
10. Populate the accounts loops with the next data
```
{
"accounts": [
{
"product": "uno",
"initialDeposit": 0
},
{
"product": "dos"
}
]
}
```
11. Fill the data with validations
12. Press submit button
The form submits with no errors.
The form does not submit due to validations running on the nested hidden fields.
- Check if the nested field parent component is visible before setting validations on the field. If the …

Fix Loop running validations on nested hidden fields 4.2

---

src/components/renderer/form-record-list.vue

Can't see all the records within a record list when a request is completed.
This Pull Request is part of a solution of [Pull Request 4252 in Core](https://github.com/ProcessMaker/processmaker/pull/4252).
- Be able to modify the `perPage` value from other components.
- [FOUR-5119](https://processmaker.atlassian.net/browse/FOUR-5119)
- [Pull Request 4252](https://github.com/ProcessMaker/processmaker/pull/4252)

Bugfix FOUR 5119 - Remove pagination in Forms tab when a request is complete. 

---

src/components/renderer/form-record-list.vue
tests/e2e/fixtures/record_list_single_input.json
tests/e2e/specs/RecordList.spec.js

When try to edit or delete a row in record list after sorting, it is taking the wrong record.
- Create a screen with only a record list control
- Add one column named ID to the record list
- Create a new page in order to add values to the record list
- Add a line input with ID as the variable
- In the first page check the Editable option and choose the new page in the record form field
- Click on preview add some rows
- Sort the column and try to edit one record or delete
The data shown in the edit option and in the record list is not the same. If you try to delete the record, will remove the wrong record
- After sorting, listen the sortChanged event and sort also the parent tableData (to have the same order that the local vuetable) and retrieve the edit or delete row from the tableData …

Bugfix/FOUR-5103: Using the sort option in a record list, doesn't update the records when using the edit action

---

src/components/task.vue
src/main.js
tests/components/TaskRedirect.vue
tests/e2e/fixtures/single_line_input.json
tests/e2e/specs/Task.spec.js
tests/e2e/support/commands.js

It was reported as a bug that subprocess inside a main process are not showing the summary screen in the subprocess, but that is not the correct behavior. It was fixed the issue related with the interstitial screen getting stuck and not getting
the next task.
- Steps to Reproduce:
- Create a process with the next configuration
- Start Event -> Task -> Sub Process -> End Event
- Create a sub process 
- Add Start Event -> Task(Assign Screen Interstitial) -> End Event (Assign Summary Screen)
- Create a request 
- Route to the sub process
- Open the sub process
- Complete the task
- Modified the flow to follow the next rules (For more clarify please watch the videos for the different scenarios):
1. Summary screen in a subprocess will show only if the process is running as standalone.
2. If a …

Bugfix/FOUR-5159: Summary screen is not displayed in sub process

---

src/ValidationsFactory.js
tests/e2e/specs/Loop.spec.js

[FOUR-5076](https://processmaker.atlassian.net/browse/FOUR-5076)
1. Create a screen
2. Add loop with the next configuration:
3. Data source: Existing Array
4. Variable Name: accounts
5. Add Multicolumn
6. Add visibility rule: product != "dos" ; to the multicolumn
7. Add line input
8. Add validation `required`
9. Press the preview button
10. Populate the accounts loops with the next data
```
{
"accounts": [
{
"product": "uno",
"initialDeposit": 0
},
{
"product": "dos"
}
]
}
```
11. Fill the data with validations
12. Press submit button
The form submits with no errors.
The form does not submit due to validations running on the nested hidden fields.
- Check if the nested field parent component is visible before setting validations on the field. If the …

Fix Loop running validations on nested hidden fields 4.1

---

src/components/renderer/form-record-list.vue
tests/e2e/specs/RecordList.spec.js

After delete all records in second page in record list, you are not able to edit records.
- Create a screen with a Record List
- Add at least 6 records to get pagination
- Go to page 2 and remove all the records in page 2
- After deleting records of page 2, in page 1 try to edit a record. A error in console is displayed and editing modal is not showing.
- Use currentPage variable instead paginatorPage to calculate pageIndex
- Added a sorting method to match the sorting method used by vuetable because the lodash _.orderBy sort the data with a different behavior for case sensitive.
- If currentPage is 0 when deleting al records in recordlist, set to 1 to avoid index exception.
- Create a screen with a Record List
- Add at least 6 records to get pagination
- Go to page 2 and remove all the …

Bugfix/FOUR-5304: Does not allow editing the registry

---

src/components/task.vue

Ticket: [FOUR-5414](https://processmaker.atlassian.net/browse/FOUR-5414)
Web entry Start Event with interstitial screen configured does not progress to the next assigned task. Console error appears `Cannot read properties of null (reading 'process_request_id')`
1. Create a Web Entry Start Event and configure an interstitial screen.  
 2. Add a form task and enable Web Entry
3. Add end event 
4. Save and run the process. 
When selecting the submit button the interstitial displays then loads the next assigned task.
When selecting the submit button the interstitial screen continuously displays and never loads the next assigned task.
- Check if `this.task` exists before retrieving the `process_request_id` key.
1. Test the replication steps above.
2. Test …

Fix interstitial not progressing to next task with web entry start events

---

src/mixins/ScreenBase.js

The problem was produced because for the default value was used a JavaScript expression that didn't return any value. By default JavaScript returns "undefined". 
Even if the the expression used for the default value of a select list is undefined, its value should be able to be set.
The select list variable with the undefined default value it is not updated when an item is selected.
If the JavaScript function returns undefined, by default the variable is initialized with a null value.
Steps to Reproduce:
Create Screen
Add select list 1 with default values
[{"content":"1","value":"1"},{"content":"2","value":"2"}]
Put default value = 2
Add select list 2 with data connector
Put default value JS
if (this.form_select_list_2 != 2) {
return null;
}
Press …

FOUR-5348: 4.2.- Variable is not created if has default value dependent

---

src/components/renderer/file-upload.vue
src/components/renderer/form-record-list.vue
tests/e2e/fixtures/record_list_fileupload_loops.json
tests/e2e/specs/RecordList.spec.js
tests/e2e/support/commands.js

- The documents uploaded should be shown correctly on the File Upload UI.
- When we upload documents inside a loop control that at the same time this loop is inside a record list, on the next task it will not be visible or the first document will be visible twice.
The issue was related to:
1. The `query.options.row_id` property for new items in the loop was generated with NULL value. This was fixed from the `form-recordlist.vue` file. 
2. The `query.options.data_name` property was generated with incorrect values. This was fixed by commenting out the `checkIfInRecordList` function.
- Import the process `26955.json` attached in JIRA
- Run a new request
- Add new records in record list
- Upload documents on the loop control
- You can override the same …

Bugfix FOUR-4986 - File Upload control inside a loop in the record list issues

---

src/components/task.vue
tests/e2e/specs/Task.spec.js

Fixes Tickets
- [FOUR-5299](https://processmaker.atlassian.net/browse/FOUR-5299)
- [FOUR-5806](https://processmaker.atlassian.net/browse/FOUR-5806)
Reproduce:
1. Create a process with the next configuration
2. Put an interstitial in Form Task
3. Put a screen display in the end event
4. Create a request
5. Route to script to the process finished
Insterstitial should wait until the script task is completed.
Insterstitial completes BEFORE the script task is executed/completed.
Issue:
The issue was due to emitting the "completed" status of the current task if there was no assigned task to load next. Script tasks are not considered "tasks" that the user has access to, this caused the interstitial to complete before the script task had time to execute or be …

Fix Interstitial redirecting before a script task is completed

---

src/components/screen-renderer.vue

Ticket: [FOUR-5359](https://processmaker.atlassian.net/browse/FOUR-5359)
When two loops on a page contain the same nested screen and the nested screen has an input variable value of `nested.form_input_1` Loop B inherits Loop A's  values when navigating between pages.  
Note:  There is more complexity with the replication steps to make it simpler import the screen attached, however if you would like to build your own below are some more detailed instructions.
1. The nested screen must have an input field variable value of an object ex `nested.form_input_1` 
2. Loop B needs to have a visibility rule set
3. Page 2 of the screen needs to reference Loop A as an existing loop and also contain a visibility rule same as Loop B
1. Import this screen …

Fix Values from being overwritten in loops with nested screens

---

src/components/renderer/file-download.vue
src/components/renderer/file-upload.vue
src/components/renderer/form-record-list.vue
tests/e2e/fixtures/record_list_fileupload_loops.json
tests/e2e/specs/MultipleUpload.spec.js
tests/e2e/specs/RecordList.spec.js
tests/e2e/support/commands.js

- The files loaded from a file upload inside a loop in the record list, should not be lost when pressing the edit button of the record list.
- Files loaded in the loop - record list have disappeared. 
- Pulling the fixes of what was solved in 4.1.
You can run the following test: `RecordList.spec.js` and follow these steps:
1. Log in 
2. create a  screen
3. create  record  list
4. create  second page  for recorlist 
5. create a loop 
6. inside  loop create a file upload
7. start a new  request 
8. Click on Add  record list 
9. upload a file in the upload file that is inside the loop
10. add a new item
11. load a new file
12. click on save from the record list
13. click on the button edit
- [FOUR-5131](https://processmaker.atlassian.net/browse/FOUR-5131) …

Bugfix FOUR-5131: File upload inside the loop is lost

---

package-lock.json
package.json
src/form-builder-controls.js
tests/e2e/specs/DatePicker.spec.js

- Add a Date Picker control to a screen
- Open the browser dev console
- Open the Configuration right side menu and insert a value for the Maximum Date
- Added method to check if max date is valid.
- Added new validation rule to show the error under the field.
- Add a Date Picker control to a screen
- Open the browser dev console
- Open the Configuration right side menu and insert a value for the Maximum Date
- Should not display any errors in the console.
- Try adding a min date and then a max date before the min date, you should see the error under Maximum Date input
- Try adding a min date and then a max date after the min date, you should NOT see the error under Maximum Date input
Run DatePicker.specs e2e tests …

Bugfix/FOUR-5590: Console error when adding a value for Maximum Date

---

src/components/inspector/screen-selector.vue
src/mixins/multiselectApi.js

The screen select list is getting slow every time it is used.
- Apply the PRs: https://github.com/ProcessMaker/processmaker/pull/4332 and https://github.com/ProcessMaker/processmaker/pull/4334
- Select only `id` and `title` to get the list of screens for the select list control
1. Create about 500 screens
2. Create a new screen
3. Go to preview
4. Go to design
5. Add a nested screen
6. Choose a screen
7. Go back to preview
8. Go back to design
9. Add a new nested screen or select one already added
10. Choose a screen
Repeat steps 7 to 10 note the screen is getting very very slow
- https://github.com/ProcessMaker/processmaker/pull/4332
- https://github.com/ProcessMaker/processmaker/pull/4334
- TICKET: https://processmaker.atlassian.net/browse/FOUR-5890

Select fields for screens selector

---

src/components/inspector/screen-selector.vue
src/components/renderer/form-nested-screen.vue
src/components/vue-form-builder.vue

- Add loop control
- Add captcha control inside loop 
- Press preview button
Current behavior 
- After adding captcha controls inside loops an error message is displayed in the top screen.
Acceptance criteria
- When try to add a captcha in a loop a warning message should shows with the following text:
`CAPTCHA controls cannot be placed within a Loop control.`
- When try to add a nested screen with a captcha in a loop a warning message should shows with the following text:
`You are trying to place a nested screen within CAPTCHA elements inside a loop. CAPTCHA controls cannot be placed within a Loop control.`
- Recursively search for captcha controls inside loops in all screen config, including nested screens.
- Added warning message when placing captcha inside loops
Test …

Bugfix/FOUR-5865: Error in captcha inside a loops 

---

src/components/renderer/file-download.vue

The File Preview is refreshed with each row add/edit and when we add a new item in the loop.
Steps to Reproduce:
1. Import process the attached process from JIRA.
2. Start a new request
3. Click on ADD of record list
4. Upload files in file upload
5. Click on the + of the loop
6. Upload a new file
- The file preview control should not be refreshed with each record list row edit, nor when we load a new file in the loop item.
1. The loading flag is set to false, to avoid an infinite loading state in the FileDownload component and File Preview.
- Please follow the reproduction steps of above.
NOTE: Branches:
-  `4.1.27-patch4` in PM Core.
- `bugfix/FOUR-6123` in Package Files.
Working video:
https://user-images.githubusercontent.com/90741874/166939608-9e119871-0a6b-411e-b8 …

Bugfix FOUR-6123 - Fix file preview refresh on new record and loop.

---

src/components/renderer/file-download.vue

Ticket: [FOUR-6022](https://processmaker.atlassian.net/browse/FOUR-6022)
HTML files cannot be previewed by PM4, but they can be downloaded. In this case the download button does not appear, like in previous versions. 
The download button appears and allows downloading of the generated HTML file.
The download button does **NOT** appear. The user is unable to download the generated HTML file.
- There was a `requestFiles` variable that was not being accounted for with the refactor of the file download. This variable contained all of the file information needed. The solution is to include the `requestFiles` variable in the `filesInfo` array, allowing the proper file info to be displayed for download. 
1. Import this process: [process …

Allow ability to download HTML file generated by a script in the request File Manager preview

---

src/components/renderer/file-upload.vue

- Create a screen with 2 file uploads: one configured as single upload, the other as multiple upload
- Create a process that uses this screen
- Start the process and upload files (better large ones > 10 MB)
*Current behavior:* 
Files are uploaded but there is no clue that the file is being uploaded - no progress bar is displayed.
When loading a file, a progress bar should be displayed
- Render the filesList array of the simple upload component to display the files while they are being uploaded.
[https://processmaker.atlassian.net/browse/FOUR-6019](https://processmaker.atlassian.net/browse/FOUR-6019)

FOUR-6019: File Upload does not show the upload progress of a large file

---

src/components/renderer/file-upload.vue

- Import the attached process
- Set up configuration
- Run request
**Current behavior** 
Uploading bar does not fit
**Expected behavior** 
Uploading bar should fit
- Added overflow hidden class
https://user-images.githubusercontent.com/90727999/166932853-b7ca5efd-7a56-4429-81e7-ca8b90987e58.mov
- [FOUR-5949](https://processmaker.atlassian.net/browse/FOUR-5949)

Bugfix/FOUR-5949: Upload File Size Loading Bar not fitting inside the auxiliary screen

---

src/components/renderer/file-upload.vue
tests/e2e/specs/FileDownload.spec.js

When you have a screen with a file upload inside a loop inside a record list, a console error shows in the task when running a new request in Firefox browser.
- Import the attached process.
- Run a new request.
- When the Task is opened, the console error appears.
[PRUEBA DE BUCLE.json.txt](https://github.com/ProcessMaker/screen-builder/files/8592869/PRUEBA.DE.BUCLE.json.txt)
- Check in file upload if uploader exists when rendering uploader-drop 
https://user-images.githubusercontent.com/90727999/166001430-e74d3531-48b5-4fad-984e-79179587e1e3.mov
- [FOUR-6039](https://processmaker.atlassian.net/browse/FOUR-6039)

Bugfix/FOUR-6039: Console error "e.uploader.uploader is null" in Task - Screen with fileupload in loop and RecordList

---

src/components/vue-form-builder.vue

Not checking for captcha elements for imported screens with captcha inside loops.
Please refers to [FOUR-5865](https://processmaker.atlassian.net/browse/FOUR-5865)
- Import a screen with captcha elements inside a loop
- Open the screen
- Captcha inside loops still there and error shows in preview
- Check for captcha also on mounted
- Import a screen with captcha elements inside a loop. 
- An alert should shows and captcha should be removed from loops.
https://user-images.githubusercontent.com/90727999/165822814-73344d94-50a6-41c1-8841-9d79c1bef7eb.mov
- [FOUR-5865](https://processmaker.atlassian.net/browse/FOUR-5865)

Check for captcha elements also in mounted

---

src/components/renderer/form-nested-screen.vue

If a form has a toggle/checkbox, this is not read-only when the submitted form is reviewed in the Forms tab. When you preview the submitted you can actually modify the toggle value. Which, if you have visibility rules added to the toggle value, will also trigger in the Form preview. 
- Create a screen with some Checkbox/Toggle elements
- You can add some Visibility Rules
- Create another screen and add a Nested screen with the previous screen configured
- Add the screen to a process
- Run a request and complete the task
- Go to Form tab and then expand the details
- Checkbox and toggle elements should be disable also for nested screen
- Disable elements in nested screens
https://user-images.githubusercontent.com/90727999/168336641-02cc4b20-7d93-45a5-89ec-43af3745e394.mov …

Bugfix/FOUR-622: Forms in the Detail review tab allow for checkbox toggle modification

---

src/components/renderer/file-upload.vue

Steps to Reproduce:
- Go to admin
- Click on File manager
- Click on public files 
- Click on Add public files  
Current Behavior:
The button to upload files in public files is not there.
We can't upload files. 
You have to be able to upload files in public files
- Moved checking if uploader exists to a method to avoid issue in modal
https://user-images.githubusercontent.com/90727999/169551193-8babc87f-196c-4f0d-bb48-2f29400de165.mov
- [FOUR-6284](https://processmaker.atlassian.net/browse/FOUR-6284)

Bugfix/FOUR-6284: The button to upload files in public files is not visible

---

src/components/renderer/file-download.vue

display the message “File ID does not exist” for each file that you want to download and the id is not found.
please review documentation https://processmaker.atlassian.net/browse/DOC-2353 for multiple files download
display other message
- change label
1. Create a screen with download file 
2. Create a process with start->task->end
3. Assign the screen on the task
4. Create a request
5. Go to data
6. Put a invalid id in file 
- [FOUR-6201](https://processmaker.atlassian.net/browse/FOUR-6201)

"File Download missing files" message error appears

---

src/components/renderer/form-button.vue
src/mixins/extensions/PageNavigate.js

1. Create a screen or import the attached file from JIRA.
2. Add more that one control with required field.
3. Create a page navigation
4. On the second page put the submit button.
5. Press preview button.
Message error should disappears, when the fields are fixed in pagination.
Message error  does not disappears, when the fields are fixed in pagination.
- Added code to perform the necessary validations when there's only one FormButton of Nagivation type.
- Improved the way to set the disabled state for a FormButton of submit type.
Test the steps of above.
Working Video:
https://user-images.githubusercontent.com/90741874/168863189-8df59a57-b3b0-4abd-9033-5404b592f572.mov
- [FOUR-6158](https://processmaker.atlassian.net/browse/FOUR-6158)

Bugfix FOUR-6158 - Error message of validation does not disappear with pagination

---

src/components/task.vue
tests/e2e/specs/Task.spec.js

- Import this process 
[MainAndSubprocess.zip](https://github.com/ProcessMaker/screen-builder/files/8662584/MainAndSubprocess.zip)
- Run the main process
- Execute until the first task of the subprocess
Task 2 of sub-process should be displayed after the script is completed 
Interstitial does not route to next task on sub-processes, If the sub-process has a script task 
-
- Test the steps above
- Test with different processes: processes withou and without subprocess, with and without interstitial. Some processes to test:
[testProcesses.zip](https://github.com/ProcessMaker/screen-builder/files/8662650/testProcesses.zip)
- [https://processmaker.atlassian.net/browse/FOUR-6050](https://processmaker.atlassian.net/browse/FOUR-6050)

FOUR-6050: Interstitial does not route to next task on sub-processes

---

src/components/renderer/form-input-masked.vue
tests/e2e/specs/FormInput.spec.js

Backspacing a character after the decimal was not working. See https://processmaker.atlassian.net/browse/FOUR-5425
Expected behavior: see ticket
Actual behavior: see ticket
This is a bug in the inputmask package. Workaround is to listen for the keyup event and manually set the currencyValue if it's not the same
Follow video in ticket
- https://processmaker.atlassian.net/browse/FOUR-5425

Fix backspacing a decimal character in currency input

---

src/components/inspector/form-multiselect.vue

Select List and signature controls, still mark in red, the validation of the required field
1. Go to admin
2. Open Customize UI
3. Select a color different to red in "Danger" option
4. Save the changes
5. Create a Screen
6. Add controls like(line input, textarea, select list, signature)
7. Add Required validation in each control
8. Press preview button
- Remove `!important` from the multiselect, this way it will use the custom style from Core.
When `package-savedsearch` is installed you will notice it still has the inline style `border: red !important`. That's because the package uses `"@processmaker/screen-builder": "^0.24.2",`. We should update screen-builder version in package savedsearch when changes in ScreenBuilder are merged.
- Compile assets, please run `npm link` for screen …

 Bugfix FOUR-6101 - Error validations are not marked with the color selected in Customize UI (ScreenBuilder) 

---

src/components/inspector/form-multiselect.vue

Select List still mark in red the validation of the required field
1. Go to admin
2. Open Customize UI
3. Select a color different to red in "Danger" option
4. Save the changes
5. Create a Screen
6. Add controls like(line input, textarea, select list, signature)
7. Add Required validation in each control
8. Press preview button
- Another class is used for errors, since other packages like saved search overwrite using inline css and the !important property.
- Compile assets, please run `npm link` for screen builder and vue-form-elements.
- [FOUR-6101](https://processmaker.atlassian.net/browse/FOUR-6101)

Bugfix 6101-B: Error validations are not marked with the color selected in Customize UI 

---

src/ValidationsFactory.js
src/mixins/VisibilityRule.js

Screen still validates validation rules of hidden controls.
1. You can use the next screen for testing purposes (remove .txt extension).
[hidden-errors.json.txt](https://github.com/ProcessMaker/screen-builder/files/9057091/hidden-errors.json.txt)
2. Press preview button
3. Put the next data in **Data Input**
```
{
"business": [
{
"hasBeneficialOwners": "Yes"
}
]
}
```
4. Try to press submit button
- Screen should not validate validation rules for hidden controls, like PM 4.2.24
- Screen still validates validation rules of hidden controls
- No need of complex algorithm, fixed allowing NestedScreens to enter isVisible Parser condition.
- [FOUR-6438](https://processmaker.atlassian.net/browse/FOUR-6438)

Bugfix FOUR-6438 - Screen still validates validation rules of hidden controls

---

tests/e2e/plugins/index.js

Fixed issue when trying to run cypress in screen builder
- Replaced browserify to use babelrc
-  [FOUR-6617](https://processmaker.atlassian.net/browse/FOUR-6617)

Bugfix/FOUR-6617: Create PR to address not being able to run cypress locally (screen builder)

---

src/App.vue
src/components/task.vue
src/mixins/ScreenBase.js
tests/components/WebEntry.vue
tests/e2e/specs/NestedValidationRules.spec.js
tests/e2e/specs/ValidationRules.spec.js

Steps to Reproduce:
Please see: https://processmaker.atlassian.net/browse/FOUR-6409
- Create a form with some elements
- Mark some of them as required
Current behavior: When start a new request and start the task or go to preview in screen builder, the validation errors appears before clicking on submit, and not showing as alert
Expected behavior: Validation error message shouldn't appear until the submit button is pressed. Message should appear as the "success" alert when submitting a form
- When submit a form, while checking if is valid, if not show ProcessMaker.alert()
- Removed old alert divs
https://user-images.githubusercontent.com/90727999/176259628-06e0ccc5-f2f8-4022-9fbe-dcf215ebb6a4.mov
- …

Bugfix/FOUR-6409: Form Validation Error messaging not displaying correctly

---

src/App.vue
src/components/task.vue
src/mixins/ScreenBase.js
tests/components/WebEntry.vue
tests/e2e/specs/NestedValidationRules.spec.js
tests/e2e/specs/ValidationRules.spec.js
tests/e2e/support/commands.js

The following tests stopped working because the error message in the HTML body is no longer displayed:
- ValidationRules.spec
- NestedValidationRules.spec
**Current behavior:**
- Tests have asserts removed.
**Expected behavior:**
- The tests should have asserts updated to the new modality.
- Tests that depended on the old global error message have been updated and now works by checking if the element have the `is-invalid` class in their list of classes.
We think it might be a good idea to have a test for the new popup error message (validate it shows up), however this cannot be directly tested from ScreenBuilder, it can be done from Core.
For the above, the conclusion of [FOUR-6468](https://processmaker.atlassian.net/browse/FOUR-6468) is necessary.
At this point, …

Bugfix FOUR-6464 - Add E2E test for added validation in FOUR-6409

---

package-lock.json
package.json
src/components/renderer/form-button.vue
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue
src/form-control-common-properties.js
src/mixins/Json2Vue.js
src/mixins/ScreenBase.js
src/mixins/VisibilityRule.js
src/store/modules/global-errors.js
tests/e2e/specs/RecordList.spec.js

For a form with validation rules and visibility rules combined, when an input text changes it triggers multiple times the `refresh-validation-rules` event causing performance problems.
The refresh of validation rules should be "debounced" to prevent it triggers multiple times on an input change.
The refresh of validation rules is triggered multiple times, it increases when the screen has many nested screens and loops.
- Move the refresh validation rules logic to $store so this way it will be unique for the screen.
- Add refresh validation rules logic to submit button to make sure all the validations are updated before submit.
- Debounce the refresh validation rules function.
- In a Screen with visibility rules combined with validation rules
- Fill the values
- Check the validation is …

Improve refresh validation event triggering to perform

---

package-lock.json
package.json
src/App.vue
tests/e2e/specs/NestedScreen.spec.js
tests/e2e/specs/RichText.spec.js
tests/e2e/support/commands.js

Preview Data in Screen Builder is refreshing many times when a input changes.
Delay and debounce the refresh of data preview
- Create a form with some inputs and other controls
- Go to Preview
- Focus on a input text
- Type
- Note in the Preview Data panel VueJosnPretty was changed by Monaco
- Note the Preview Data is devounced (refresh after user complete to type)
https://user-images.githubusercontent.com/8028650/191998125-ad117d9a-bb43-4801-953c-15a6a32266a3.mp4
- https://processmaker.atlassian.net/browse/FOUR-6732

Four 6732/change vuejsonpretty

---

tests/e2e/fixtures/FOUR-6910_Watcher_Checkbox.json
tests/e2e/fixtures/FOUR-6910_Watcher_Radio.json
tests/e2e/specs/SelectListWatcher.spec.js

Select List of type Radio (and also Checkbox) does not refresh its options after a watcher execution.
After the watcher load the values for the select list options, these options should be updated in the select list control.
Select List of type Radio (and also Checkbox) does not refresh its options after a watcher execution.
- Add missing reactivity to refresh the Radio and Checkbox options.
1. Import the screen attached in the ticket
2. Setup the required collection and data source
3. Update the screen watcher to point the prepared data source in step 2
4. Preview the screen
5. Enable the checkbox to trigger the watcher
- https://processmaker.atlassian.net/browse/FOUR-6910

Verify Select Lists loaded by watchers

---

src/DataProvider.js
src/ValidationsFactory.js

**Steps to Reproduce:**
- Go to https://release-testing-qa.processmaker.net/ (PM 4.3.0-RC4)
- Go to Designer tab
- Go to screen option in sidebar menu
- Create a Form type screen
- Click on Add screen
- Fill a name and description
- In the type option, select “Form“
- Click on Save button
- Drag and drop a Nested Screen control.
- Drag a control of the following: Checkbox, Date Picker, File Upload, Google Places, Line Input, Loop, Record List, Select 
- List or Text Area (In the attached video I tested with a Text Area control)
- Open Devtools and go the network tab
- Click on Preview button
**Expected behavior:** 
A single call should be generated by the nested Screen.
**Actual behavior:** 
Two pop-ups with 404 error appear and two calls are generated.
- Check if id exists before send …

Bugfix/FOUR-7111: Previewing a screen that contains a nested screen and another control causes two 404 error calls

---

src/components/renderer/form-button.vue

Create a Screen with 2 pages
On the first page
Add any control like line input
Add page navigator to second page
On the Second page
Add check box with required filed
Add submit button
Save the changes
Go to the page where is the submit button
Press preview button
Go to until submit button
Button’s class is not disabled , when there are fields required 
The property used to determine if the button was enabled/disabled was a Vue watcher that was not updated when expected. The problem is resolved when the Vuex store value is used directly.
[https://processmaker.atlassian.net/browse/FOUR-7158](https://processmaker.atlassian.net/browse/FOUR-7158)

FOUR-7158: Class submit is not disabled with field required 

---

src/components/renderer/form-record-list.vue
src/mixins/DataReference.js
src/mixins/ScreenBase.js
src/store/modules/globalErrorsModule.js
tests/e2e/fixtures/validation_rules_and_recordlist.json
tests/e2e/specs/ValidationRulesAndRecordlist.spec.js

- Add record list
- Add a Submit button
- click + Add new page
- Add one line input have to required
- Add page to record list
- Save
- Press preview button
- Add a record list
- Fill the field required
After completing the required fields the "submit button" should show as enabled, this causes confusion even though if clicked the submit button works, as in previous versions 4.2.35
After completing the required field, the submit button is shown as disabled, with no more required fields to complete.
- Refactored logic for showAddForm method and addFormInstanceKey.
- Handle cancel popup method to not validate
https://user-images.githubusercontent.com/90727999/204291596-bd422694-882e-4c9d-9402-2eab4eb2e490.mov
Test the …

Bugfix/FOUR-7131: Submit button it seems disabled with required fields in the record list

---

tests/e2e/specs/Watchers.spec.js

We should run all the tests from the Watchers spec file
Only one test of 10 were running
- Removed the `.only` from the last test. Now all test should be running
* Run `npm run open-cypress` after spinning up `npm run serve` and run the Watchers.spec.js file
- https://processmaker.atlassian.net/browse/FOUR-7405

FOUR-7405 Watchers E2E file was only running 1 test of 10

---

tests/e2e/support/commands.js

The following test fails when it run the last day of the week (Feb 11, in the image).
Fix pickTomorrow command should correctly select tomorrow on the last day of the week
- Fix pickTomorrow command 
1. Run Screen Builder in development mode
2. Open the Cypress tests
3. Run the test ValidationRulesAdvanced.spec.js
4. The pick tomorrow step will fail (When executed the last day of the week)
- https://processmaker.atlassian.net/browse/FOUR-7416

Fix pickTomorrow command to correctly select tomorrow on the last day of the week

---

tests/e2e/specs/FormTextArea.spec.js

The E2E test for the text Area field 
Text area need some improvements
run the cypress tests
- https://processmaker.atlassian.net/browse/FOUR-6996
- https://github.com/ProcessMaker/vue-form-elements/pull/380

FOUR-6996: e2e test for Text Area

---

src/App.vue
src/mixins/ScreenBase.js

Incorrect debounce declaration of updateDataInputNow and updateDataPreview methods.
Debounce the methods during the creation of the component.
Incorrect debounce declaration of updateDataInputNow and updateDataPreview methods.
- Fix debounce initialization following the guide: https://forum.vuejs.org/t/lodash-debounce-not-working-when-placed-inside-a-method/86334/5
- Create a simple screen with some fields like: input text, currency, select list
- Go to preview
- Input and change information
- Submit the form
- https://processmaker.atlassian.net/browse/FOUR-6888

Fix debounce of updateDataInputNow and updateDataPreview methods

---

src/components/task.vue
tests/e2e/specs/Task.spec.js

After completing the task, it was redirecting to a parent request that the user did not have access to.
https://user-images.githubusercontent.com/16992680/210136587-ce333c49-a2a9-4992-987f-e5c45d7b8328.mp4
Redirect to the request where the user has access
https://user-images.githubusercontent.com/16992680/210136594-6d3b6f31-8f43-425c-a05e-958dd3e48e8f.mp4
- Include uses permission data information when fetch task data
- Create a process with the next configuration
- Create a sub-process with the next configuration
- Create a user without permissions  to assign on the sub-process. Like the next image:
- Create a request with admin user
- Route to the sub-process, where the user without permission is assigned to the sup-process
- Log in with the user on …

Redirecting to the authorized request - FOUR-7187

---

package-lock.json
package.json
tests/e2e/specs/DatePicker.spec.js

The date picker component is not responsive as other controls and it doesn't look good on the design the screen.
1. Create screen 
2. Add line input 
3. Add date picker
4. Press preview button
The date picker component should be responsive, the same with others controls, the label should be at the top.
The date picker input is displayed next to its' label either in design mode or in preview mode.
- A new class (`.datePicker`) on the FormDatePicker.vue file was added to the date-picker input. This was done to change the css property: `display: inline-block` that was causing the issue. The display mode was changed to `block` to match the other inputs.
- https://processmaker.atlassian.net/browse/FOUR-7559
- …

FOUR-7559: Fixed datepicker input not being responsive

---

tests/e2e/specs/DatePicker.spec.js

Having a test case scenario to cover helper text changes
No test case covering this scenario
- Added a test case scenario
- Run SB with the branch in VFE `FOUR-7610`
- Run Cypress, Datepicker spec file
- https://processmaker.atlassian.net/browse/FOUR-7610

FOUR-7610 Added test coverage for Helper Text

---

tests/e2e/specs/DatePicker.spec.js

The date picker component is not validating if the usere enter invalid characters in the input field
1. Create screen 
2. Add line input 
3. Add date picker
4. Press preview button
5. Select a date from widget
6. edit and enter wrong dates to the input 
The date picker component should validate the wrong entered characters .
The date picker input allow none formatted date 
- on Change handler was improved to catch and validate the input string and evaluate if is a valid date
- https://processmaker.atlassian.net/browse/FOUR-7564
ci:vue-form-elements:bugfix/FOUR-7564

FOUR-7564: Date picker does not validate the correct format

---

src/components/inspector/collection-select-list.vue
src/components/inspector/options-list.vue
tests/e2e/specs/SelectListDependent.spec.js

Global AI search
- [FOUR-7864](https://processmaker.atlassian.net/browse/FOUR-7864)
- [Core PR](https://github.com/ProcessMaker/processmaker/pull/4680)
- [Screen builder PR](https://github.com/ProcessMaker/screen-builder/pull/1361)
- Bugfixes
- Clear history funcitonality
- Make history per user
- Persist search across pages after submit search
- Add an X to the search bar to remove the session
- Reduce animation for text in popup
- Added PmqlInput in dependent selects
- Added support to mustaches PmqlInput for dependent selects
[FOUR-7864]: https://processmaker.atlassian.net/browse/FOUR-7864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Epic/FOUR-7864: Global AI search

---

.gitignore
src/components/inspector/color-select.vue
src/components/vue-form-builder.vue
src/store/modules/undoRedoModule.js

- Saving indicator (autosave draft) should be displayed when a page is edited and deleted, when the clear color selection and color is changed and when redo and undo buttons are pressed.
- Autosave is not working when:
- the page name is edited
- the page is deleted
- the clear color and color is changed
- the undo and redo buttons are pressed
- Applied eslint format to the edited files.
- The `updateState` function was improved.
- Now, every time an action from the undoRedoModule is used, a "screen-change" event will be emitted, which triggers autosave.
- This improves the UX of autosave and fixes the problem when editing and deleting pages and when using the undo/redo button.
- The Color Component now emits "update-state".
- This helps to …

Bugfix FOUR-7330 Autosave emit changes

---

src/mixins/ScreenBase.js

**Steps to Reproduce**
- Add two Select List controls on the screen with variable name sex and sexResp
- On both controls, select data source as “Provide Values” and enter the JSON below
```
[
{
"content": "Male",
"value": "M"
},
{
"content": "Female",
"value": "F"
}
]
```
- On the select list with variable name sexResp, on the advanced tab, enter the JavaScript code below  enter the 
`return this.sex;`
On select of the options on the sex control, the sexRespvalues is not dynamically updated to match the choice in the sex variable, since the default value has been set to the sex value
On select of the options on the sex control, the sexRespvalues should dynamically be updated to match the choice in the sex variable
- Do not set to true the was_filled …

Bugfix/FOUR-8132: Default Value not working dynamically in Dropdowns

---

src/ValidationsFactory.js
tests/e2e/specs/SelectListDependentCollection.spec.js

Nested screens in record lists are causing the page continually re-render every second
- Create a screen with a record list
- Create a new page for the record list item
- In the record list row page, add a nested screen
- In the nested screen, add a checkbox, multicolumn, and a select list that calls a data source
- Preview and add an item to the record list
- Look at the network panel and notice it's calling the data source every few seconds
- Also, notice the input box gets unfocused
- Notice on the Vue tab of devtools, events are firing every second without any interaction
Should not re-render
Screen is re-rendering every second
- In ValidationsFactory, make the `pagesValidated` a non-reactive property as to not-trigger `rebuildScreen`
Test the …

Save pagesValidated outside definition

---

src/components/renderer/file-upload.vue

the progress bar does not display when uploading a file.
progress bar display correctly
progress bar not display correctly
- Initialize the Uploading variable before verifying that it is a wrong file
- Add file upload 
- Configure the file upload to only pdf will be upload 
- Create a request
- Upload a wrong file like an image
- Upload a pdf file 
https://user-images.githubusercontent.com/1747025/236535617-1887ff36-2148-4104-83dd-b6c73649ce44.mp4
- [FOUR-8433](https://processmaker.atlassian.net/browse/FOUR-8433)
[FOUR-8433]: https://processmaker.atlassian.net/browse/FOUR-8433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

The progress bar in file upload disappears

---

src/components/SimpleErrorMessage.vue
src/components/task.vue

Create a process with: start->task->script->task->end
In the script, put throw new \Exception('Custom error');
The first task should have the interstitial configured.
Now, only a simple error message must be displayed.
We redirect the user to the error detail page
Change the redirection behaviour

FOUR-8060 Interstitial Reroute

---

src/ValidationsFactory.js

- Create a Form Screen with two pages at least
- Include on all pages the required fields
- Create other Form Screen
- Add a nested screen and assign the previous form.
- Add a Submit button
- Add a second nested screen with no screen assigned
- Go to Preview mode. All required fields are required on the first page, but on other pages lost all required fields.
- Create a process
- Add a Start Event, form task, and End Event.
- Connect one by one.
- Save all changes
- Start a new request for the process
- The task started and all required are required on the first page, but on other pages lost all required fields and it is possible to submit the task.
In a nested screen that have more than 1 page, validation of all pages should be used.
Validations of …

FOUR-8509: Required fields in nested screens are lost 

---

src/components/vue-form-builder.vue

Ticket: [FOUR-8548](https://processmaker.atlassian.net/browse/FOUR-8548)
The name of the Photo/Video control does not iterate when other Photo/Video controls are present on the screen.
If you have three Photo/Video controls on the screen, they all have the Variable Name "photo_video_1".
1. Log in to ProcessMaker.
2. Go to the Designer tab.
3. Create a new Screen.
4. Add three Photo/Video controls to the screen.
1. Go to branch `observation/FOUR-8548` in `package-photo-video`. Install the package.
2. Go to branch `observation/FOUR-8548` in `screen-builder`. Link screen-builder to core.
3. Follow the Steps to Reproduce.
4. The name of the Photo/Video control should update sequentially when multiple controls are added.
- [FOUR-8179](https://processmaker.atlassian.net/browse/FOUR-8179) | …

FOUR-8548 | Photo/Video Variable Name Is Not Created Correlatively

---

src/components/vue-form-renderer.vue

The user must able to write media query in the custom css
n/a
- media query was enabled for the user
- npm run serve
- add a input field
- for this input add a CSS Selector Name
- add media query
- preview the screen
https://github.com/ProcessMaker/screen-builder/assets/1401911/a15a3dce-bf04-4ed8-972b-d7c7fc071a66
- https://processmaker.atlassian.net/browse/FOUR-8992

FOUR-8992: Media Queries - Enable Media Queries for custom css in the screen builder

---

tests/e2e/specs/DeviceVisivilityInspector.spec.js

have a e2e test to validate device visibility in the inspector panel
n/a
- created tests/e2e/specs/DeviceVisivilityInspector.spec.js to validate device visibility for all controls
-     run the command npm run seve, port 8080
-     run the command npm run open-cypress
-     find the test DeviceVisivilityInspector.spec.js and run it.
-  https://processmaker.atlassian.net/browse/FOUR-9094

FOUR-9094: e2e Tests for configuring a screen with controls that show/hide for desktop/mobile devices

---

tests/e2e/specs/MediaQuery.spec.js

have a e2e test  to validate media query
n/a
- created MediaQuery.spec.js to validate if the media query rules was applied
- run the command npm run seve, port 8080
- run the command npm run open-cypress
- find the test MediaQuery.spec.js and run it
- https://processmaker.atlassian.net/browse/FOUR-9096

FOUR-9096: e2e Test(s) that validate that media queries are applied to controls of a screen

---

src/mixins/VisibilityRule.js
src/mixins/extensions/VisibilityRule.js

Create a screen with 2 input lines and configure them like this:
Line1-> Select Show For Desktop = true, Show For Desktop = false
Line2-> Select Show For Desktop = false, Show For Desktop = true
Change the browser screen size. When the screen width is less than 480px Line 2 will be displayed and Line 1 will be hidden.
- Added an additional condition when displaying/hiding a control
- [https://processmaker.atlassian.net/browse/FOUR-9117](https://processmaker.atlassian.net/browse/FOUR-9117)

FOUR-9117: Use the size of the rendered screen to hide/show controls according to the Device Visibility Configuration

---

src/mixins/ScreenBase.js
src/store/modules/globalErrorsModule.js
tests/e2e/specs/DatePicker.spec.js
tests/e2e/specs/DatePickerTimezone.spec.js

Ticket FOUR-8185
This PR enhances the functionality of the globalErrorsModule.js file by introducing a mutation to disable form submission while a photo is being uploaded to Intelligent Processing (IDP) using the Photo Video package.
The changes made in this PR are as follows:
- Addition of the disableSubmitOnPhotoVideoUpload mutation in globalErrorsModule.js.
- Integration of the this.disabledSubmit__ variable within the submit condition to prevent form submission during photo upload.
Once the photo processing is completed, the submit button will be automatically enabled for the user.
-  [Photo Video Package PR](https://github.com/ProcessMaker/package-photo-video/pull/10)
-  [Connector IDP PR](https://github.com/ProcessMaker/connector-idp/pull/23)
ci:package-photo-video:feature/FOUR-8185 …

Photo Video: Implement Feedback Signal (FOUR-8185)

---

package-lock.json
package.json
src/components/vue-form-builder.vue

Improved PR Description:
As part of the ongoing development efforts for [EPIC FOUR-8178](https://processmaker.atlassian.net/jira/software/c/projects/FOUR/boards/434?modal=detail&selectedIssue=FOUR-8178), this pull request introduces SVG icon rendering for Screen Builder controls.
- Implemented conditional rendering of SVG icons based on the presence of an SVG attribute within the config object.
- Utilized the v-html directive on a span element to render the SVG icons.
- [FOUR-8178](https://processmaker.atlassian.net/jira/software/c/projects/FOUR/boards/434?modal=detail&selectedIssue=FOUR-8178) - The related ticket tracking this feature development.
- [Plaid Package PR](https://github.com/ProcessMaker/package-plaid/pull/1) - A pull request associated with the Plaid package.
[FOUR-8178]: …

FOUR-8178: Add SVG Icon Support  for Controls

---

src/App.vue
tests/e2e/specs/MediaQuery.spec.js
tests/e2e/specs/ResponsivePreview.spec.js

Web and mobile preview icons should have pop up to identify them 
Web and mobile preview icons do not have pop up
- Add tool-tip labels
1. Go to screen 
2. Press preview button
3. Check the icons for web and mobile 
- https://processmaker.atlassian.net/browse/FOUR-9247

FOUR-9247: adding toolip for desktop and mobile preview buttons

---

src/mixins/extensions/LoopContainer.js

-     Create screen 
-     Add a loop
-     Add line input control inside the loop
-     Disable “Show for Desktop“ option in line input
-     Press Preview option
-     Go to Web and mobile
The line input inside the loop should be visible according to configuration 
The line input is not visible in Web or mobile design
- The isMobile attribute of the main screen definition was not passed to loops
[https://processmaker.atlassian.net/browse/FOUR-9300](https://processmaker.atlassian.net/browse/FOUR-9300)

FOUR-9300: Device Visibility is not working inside a loop

---

src/mixins/VisibilityRule.js

1. Create a screen
2. Add line input control inside the screen
3. Configure the  line input with a variable non-existent in visibility
4. Press Preview button
Expected behavior:
If the variable does not exist the validation rules should not show the control configured. like PM 4.7.0 Alpha 1
Actual behavior:
Controls that are configured with a variable non-existent in visibility rules are showed 
Validate the variable in visibility rule mixin
1. Switch to bugfix/FOUR-9420 branch
2. Configure the line input with a variable non-existent in visibility
3. Press Preview button
4. The control must not be displayed
[FOUR-9420](https://processmaker.atlassian.net/browse/FOUR-9420)
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*co …

FOUR-9420 visibility rules show the controls, when the variable does not exist

---

tests/e2e/specs/MediaQuery.spec.js

media query spec must work
media query spec is failing in the Circle CI enviroment
- refactor the cypress media query tests
1. run npm run serve
2. run npx cypress run --spec tests/e2e/specs/MediaQuery.spec.js
3. test result fails
- https://processmaker.atlassian.net/browse/FOUR-9485

Refactor media query spec because the previous spec was failing

---

src/components/vue-form-builder.vue
tests/e2e/specs/Loop.spec.js

The Bootstrap controls in Screen Builder are not listed in alphabetical order. They are presently the last ones in this list. They should be listed as the first controls to be alphabetical.
Bootstrap controls should fall in alphabetical order along with all other controls.
Bootstrap controls are out of order and appear at the bottom of other controls.
- Added a sort to the filtered controls.
- https://processmaker.atlassian.net/browse/FOUR-9477

FOUR-9477: Added alphabetical sort to control list

---

tests/e2e/specs/DatePicker.spec.js

The user shouldn't be able to clear the date if the datepicker is in `readonly` mode
The user is able to clear the date when in `readonly` mode
- `isReadOnly` coming from the mixin `validation.js` and we weren't getting a prop from `readonly`. Removed the prop since it wasn't needed and added the test to cover this scenario
- https://processmaker.atlassian.net/browse/FOUR-8416
- https://github.com/ProcessMaker/vue-form-elements/pull/407
ci:deploy
ci:vue-form-elements:bugfix/FOUR-8416

FOUR-8416 Added test to support read only attributes

---

src/components/watchers-form.vue
tests/e2e/specs/ComputedFieldsReadOnly.spec.js

- Create a Watcher 
- Go to the Source configuration - 
-  Add a script on the source list
-  Go to the Script configuration part
-  Add a JSON to the Script configuration
-  Save the Watcher 
-  Re-open the Watcher
-  Look for the Script Configuration again 
-  At this point, all the JSON lines breaks are gone upon 
When we save the script configuration, all line breaks should not go upon reopening the editor.
When saving the Script Configuration for a Watcher, all line breaks are gone upon reopening the editor.
The problem is that internally, a new JSON object is created (a merge of 2 objects), causing any "customization" in the JSON string to be lost.
The proposed solution involves adding carriage returns and spaces to the created JSON. …

FOUR-8770: Watcher script configuration strips line breaks

---

tests/e2e/specs/DatePickerTimezone.spec.js

- Added an extra wait for Vue queue to pick up the changes
- https://processmaker.atlassian.net/browse/FOUR-9720

FOUR-9720 Added a wait in the DatePickerTimezone.spec.js

---

src/components/vue-form-builder.vue

Address issue related to the icon in screen builder controls list for Plaid package.
- Fix width and height in plaid package
- fix margin bottom for svg icons
- install package-plaid and go to screen builder. Verify the icon for plaid is correctly displayed
- [FOUR-10072](https://processmaker.atlassian.net/browse/FOUR-10072)
[FOUR-10072]: https://processmaker.atlassian.net/browse/FOUR-10072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix/FOUR-10072: Address issue related to the icon in screen builder controls list

---

src/mixins/DeviceDetector.js

1.   Create a new process.
2.   Add a Start Timer event.
3.   Add an End Event
4.   Connect all tasks.
5.   Change the time or date on the Start Timer Event functionality.
6.   When you click out of the event, the settings are reset to the initial ones about the Start Timer Event.
he Start Timer Event should be able to keep the date and time change.
The Start Timer Event, shows an erroneous behavior when making changes within the date and time.
- Added optional chaining to access cycle body
-  Restored Cycle initialization in component data
[https://processmaker.atlassian.net/browse/FOUR-10022](https://processmaker.atlassian.net/browse/FOUR-10022)

FOUR-10022: Start Timer - No change of date and time allowed

---

src/components/task.vue

Sometimes when a ActivatedActivity is triggered and the get tasks function is executed immediatly it gets an empty result. It needs a retry capacity to retry to get the next task.
A retry feature to get the last assigned task.
Does not have a retry feature.
- Implement a retry feature to `getTasks()` function.
Run the attached process as a webentry.
- Upload a file
- Submit the form
- See the interstitial get properly the next screen.
[webentry.zip](https://github.com/ProcessMaker/screen-builder/files/12501628/webentry.zip)
- https://processmaker.atlassian.net/browse/FOUR-10271
.

Add retry to get task endpoint

---

src/components/task.vue

Redirect automatically to Request if the request was already completed
-
- https://processmaker.atlassian.net/browse/FOUR-10311
ci:next

FOUR-10311 Redirect automatically to Request if the request was already completed

---

src/components/renderer/file-upload.vue

- Please see the [core PR #5414 to find the issue](https://github.com/ProcessMaker/processmaker/pull/5414), reproduction steps, process to test with, testing process, and related ticket(s).
- Make sure you install and compile the npm assets for screen-builder and link it to core before building core's assets.
ci:processmaker:feature/FOUR-10833
.

FOUR-10833: Update warning messages for file upload(s)

---

src/components/renderer/file-download.vue
src/components/task.vue
src/components/vue-form-renderer.vue
src/store/modules/globalErrorsModule.js

Restart screens to be validated when a task resets screen state.
Required for process testing.
- https://processmaker.atlassian.net/browse/FOUR-8066
ci:next

FOUR-8066 Restart screens to be validated when a task resets screen state

---

src/components/renderer/form-button.vue

Loading submit button should validate all required field before it displays its Loading Label message
The loading submit button is not working correctly when a field is marked as Requited
Check the validation of the formdata before changing the submit button 
Create a Screen 
Create a line input control and check Make Required option
Create a Submit control and check Loading Submit Button option
Assign that Screen in a Web Entry
Run a Request from Web Entry
https://processmaker.atlassian.net/browse/FOUR-11025
ci:next

Bugfix/four 11025 Loading Submit is not working correctly when required field is enabled

---

src/components/task.vue

1. Create a new [process](https://github.com/ProcessMaker/screen-builder/files/12831232/four-10115.json.zip) with a minimum of two tasks, each with a form
2. In the second task, the assignment rule is self-service
3. Run a request up to the self-service task
4. Open the second task, notice you can fill the form without claiming the task
5. Fill out the form and try to submit it, you will get a message that says you need to claim the task first
6. Claim the task, at that point, the form is reloaded and all the previous data you filled in is whipped out
- Added a bootstrap-vue component overlay to prevent the task form(s) from being altered before the self-service is claimed.
Run through the reproduction steps and you should now not be able to change the form inputs on the second task …

FOUR-10115: Prevent form changes if task has not been claimed as self service

---

src/components/renderer/avatar-dropdown.vue
src/components/renderer/form-list-table.vue
src/components/renderer/form-new-request.vue
src/components/renderer/form-requests.vue
src/components/renderer/form-tasks.vue

New filters were added to List Table new control
- FOUR-10336 package-screen-builder
ci:deploy
ci:next
ci:processmaker:feature/FOUR-9486

FOUR-10336: HOME: Add in the component "VIEW ALL"

---

src/components/renderer/form-list-table.vue
src/components/renderer/form-new-request.vue
src/components/renderer/form-requests.vue
src/components/renderer/form-tasks.vue

In this Ticket was added functionality related to ticket FOUR-9653 because both tickets have the same scope.
- HOME: Add in the component "SEARCH"
- HOME the component "SEARCH" needs to apply the following filter in the API CALL
- FOUR-9653
ci:next
ci:processmaker/feature/FOUR-9486

FOUR-10337: HOME: Add in the component "SEARCH"

---

src/components/inspector/analytics-selector.vue

- The Analytics Management dropdown in Screen Builder shows the name of selected Analytics Chart
- Package Analytics Reporting must be installed with last version which includes new API's
ci:next

QA Observation Bugfix/FOUR-11084: The "Analytics Management" does not show the value selected

---

src/components/renderer/form-tasks.vue

My Task: Enlarge the participant task preview panel
- The preview pane needs to use the 50%
- Create Request
- Create Route Request
- See the preview Pane From Task and Welcome Screen
- [FOUR-11278](https://processmaker.atlassian.net/browse/FOUR-11278)
ci:deploy
ci:next
[FOUR-11278]: https://processmaker.atlassian.net/browse/FOUR-11278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-11278: Enlarge the participant task preview panel

---

src/mixins/extensions/ValidationRules.js
tests/e2e/specs/ValidationShownOnSubmit.spec.js

Validations are only shown after submitting.
- When the form opens, there is no validation.
- All required fields should be marked with a red asterisk (*).
- Fields designated as "Required If," which meet their specified conditions, should also be identified with an asterisk (*).
- While filling out the form, if a required field is left blank when completing the form in order, the empty field should be highlighted in red.
- An alert message should be displayed when the validation criteria are not met while filling a field.
- The field should also highlight in red when the Submit Button is clicked, and the validation criteria are not met.
- These rules apply to loops, nested screens, and multiple screens.
Validations are only shown after submitting.
- …

Validations rules do not work the first time before pressing the Submit button

---

src/components/renderer/file-download.vue

- After any file deletion, download file needs to be synchronized.
- After file deleting, download file is not synchronized.
- It was necessary to set the filesInfo array as empty when no files are present. This same functionality is already implemented in the `setFilesInfoFromCollectionValue` method. 
- The additional changes are simply related to formatting applied by eslint.
- Please follow the reproduction steps.
- [FOUR-12206](https://processmaker.atlassian.net/browse/FOUR-12206)
[FOUR-12206]: https://processmaker.atlassian.net/browse/FOUR-12206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-12206: Deleting a File in File Upload does not synchronize File Download

---

src/components/vue-form-builder.vue

Steps to reproduce:
- Login as admin
- Go to Designer > Screen
- Click on +Screen
- Set the information required
- Drag and drop any control
Current behavior:
The icons of the buttons are displaced to the left
Expected behavior:
The icons should be centered 
Please see the image in the ticket for more information
https://processmaker.atlassian.net/jira/software/c/projects/FOUR/boards/493?selectedIssue=FOUR-11185
Fix padding for buttons in screen builder
- [FOUR-11185](https://processmaker.atlassian.net/jira/software/c/projects/FOUR/boards/493?selectedIssue=FOUR-11185)
ci:next
[FOUR-11185]: https://processmaker.atlassian.net/browse/FOUR-11185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix/FOUR-11185: Icons of buttons displaced to the left in Screen builder

---

src/components/task.vue

Currently, if the interstitial screen is configured in the start event, it never shows up and the request’s task is shown directly. We have noticed that this happens with a process with more than 50 elements (meaning tasks, events, lines, pools, etc.) at the beginning you will see this behavior intermittently but if you increase the number of elements (>50) you will see it permanently.
If you reduce the number of elements you will see that the interstitial works normally.
- Check if the interstitial screen is set
[FOUR-12665](https://processmaker.atlassian.net/browse/FOUR-12665)
https://github.com/ProcessMaker/processmaker/pull/5753
[FOUR-12665]: https://processmaker.atlassian.net/browse/FOUR-12665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

FOUR-12665 The interstitial screen in the start event stops working

---

src/components/task.vue

Do not display interstitial by default at the beginning
- Do not display interstitial by default at the beginning when screen is loading
- Do not display interstitial when loading screen
- https://processmaker.atlassian.net/browse/FOUR-12754
ci:deploy
ci:processmaker:develop

FOUR-12754 Fix Screen Interstitial unexpected behavior

---

src/components/vue-form-builder.vue
tests/e2e/specs/FileUpload.spec.js
tests/e2e/specs/MultiInstanceLoopContext.spec.js

No errors should appear when using Screen Builder
There was an error appearing about `AIAssistant` being undefined due to a race condition where the watcher was being executed AFTER rendering and we needed that watcher to be executed immediatly when rendering. 
- Added `immediate` to be `true` on watcher
- Re-indent
- Added the filteredGroupedControls varaible to the v-data since it was missing.
* Open a Screen of type FORM and no errors should appear in the console.
- https://processmaker.atlassian.net/browse/FOUR-13065?atlOrigin=eyJpIjoiMjc4ZDllNDU5YzRiNDQ3ZWJmM2YxM2U2NzJiZTYwMGEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
ci:deploy
ci:next

FOUR-13065 AIAssistant was coming as undefined due to a watcher race-condition issue

---

package-lock.json
package.json
src/components/vue-form-builder.vue

https://processmaker.atlassian.net/browse/FOUR-12891
https://processmaker.atlassian.net/browse/FOUR-12881
- 
- 
..

FOUR-12891 / FOUR-12881 Fix Balloon position and improvement of Control Menu for Display Screen

---

src/components/task.vue

This PR addresses an ongoing bug in CI servers related to task progression and error handling in Guided Templates. The issues included a 422 error indicating the task was already closed, replication of closed tasks displaying, and incorrect task statuses (In Progress instead of Completed) upon completion.
1. The <task> component was not automatically progressing to the next task.
2. An error was thrown from Screen Builder upon closing the first task, with an unknown `getScreenEndpoint` message.
1. Removed the initial `getNextTask` method and allow the <task> component progresses correctly.
2. Updated the conditional to check if the `getScreenEndpoint` variable exists, preventing an error and allowing the <task> component to progress.
1. Install the latest Send Email Connector.
2. Symlink …

Resolve Task Progression and Error in Guided Templates

---

vite.config.js

No console.errors and the editor for the Javascript working
Error was saying that `editor` is undefined or undeclared.
- Added `vue-monaco` to the externals array since this package is already being provided in core
- https://processmaker.atlassian.net/browse/FOUR-13951
- https://processmaker.atlassian.net/browse/FOUR-13952
ci:next
ci:deploy

FOUR-13951 Added vue-monaco and monaco-editor in the externals array

---

src/form-builder-controls.js

- List Table option must be in Dashboards section in Screen Builder
- Open or Edit an Screen of type "Display"
- Click on Dashboards section
https://processmaker.atlassian.net/browse/FOUR-13934
ci:next

QA Observation bugfix/FOUR-13934: List Table must be in Dashboard

---

src/components/task.vue

create a form with webEntry and review form.
The form with the WebEntry package should be displayed.
the form is not displayed.
- Add declaration 
steps in ticket
[https://processmaker.atlassian.net/browse/FOUR-13945](FOUR-13945)
ci:next
ci:deploy

The form is not displayed in a web entry request

---

src/components/renderer/form-analytics-chart.vue
src/components/renderer/form-list-table.vue

The title sections: My task, My Request, Start New Request and Analytics charts must be similar to the Figma
-
- [FOUR-14000](https://processmaker.atlassian.net/browse/FOUR-14000)
ci:deploy
ci:next
[FOUR-14000]: https://processmaker.atlassian.net/browse/FOUR-14000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-14000:Home "Title Sections" are not the same as figma

---

src/components/index.js
src/components/renderer/form-avatar.vue
src/components/renderer/index.js
src/form-builder-controls.js

The Avatar is not the same in Home Option and Designer Option, since is the same user that was login.
- https://processmaker.atlassian.net/browse/FOUR-13370
https://github.com/ProcessMaker/processmaker/pull/6190
ci:next
ci:deploy
ci:processmaker:feature/FOUR-13370

feature/FOUR-13370: The Avatar is not working correctly as Participant and Designer package

---

src/components/renderer/form-empty-table.vue
src/components/renderer/form-list-table.vue

Ticket: [FOUR-13914](https://processmaker.atlassian.net/browse/FOUR-13914)
When a language is selected for a user, all strings are not translated into the selected language.
- Ensure missing translations are wrapped in the `$t(...)` translation method.
- Ensure missing translations are added to the language JSON files.
1. Go to branch `observation/FOUR-13914-b` in `processmaker`.
2. Go to branch `observation/FOUR-13914-b` in `screen-builder`.
3. Create a user. Change their language to `es` for Spanish.
4. Ensure that the text on the following pages is translated into Spanish:
- Homepage (Custom Dashboard text)
- Processes
- Designer
ci:next
..
[FOUR-13914]: https://processmaker.atlassian.net/browse/FOUR-13914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

FOUR-13914 | The Language Selected for a User Is Not Complete

---

src/App.vue
src/assets/css/custom.css
src/bootstrap.js
src/components/editor/pagesDropdown.vue
src/components/vue-form-builder.vue
src/stories/DropdownAndPages.stories.js
src/stories/PagesDropdown.stories.js
tests/e2e/specs/pagesDropdown.spec.js

As a Designer I want to have the option when clicks on the pages dropdown the platform will show the list of pages created.
n/a
- create page dropdown component
[pagesDropdown2.webm](https://github.com/ProcessMaker/screen-builder/assets/1401911/d665e327-2024-4c76-b63e-04097ae48c9a)
- https://processmaker.atlassian.net/browse/FOUR-13447
ci:next

FOUR-13447: Page Dropdown

---

src/App.vue
src/components/TabsBar.vue
src/components/vue-form-builder.vue
src/main.js
src/stories/Configure.mdx
src/stories/PageTabs.stories.js
src/stories/ScreenToolbar.stories.js

- https://processmaker.atlassian.net/browse/FOUR-13450
ci:next

FOUR-13450 Reindex page index when deleted

---

src/components/sortable/sortableList/sortableList.scss
src/components/vue-form-builder.vue

The subtitle should appear in the modal Edit pages
The height of the rows must be the same
Subtitle does not appear in modal Edit pages
The height of the rows is not the same
- subtitle component was added
- height was adjusted
Open any screen
Go to menu dropdown
Click on See all pages
- https://processmaker.atlassian.net/browse/FOUR-14227

FOUR-14227: Design in modal to edit pages is not the same with mockup

---

src/components/TabsBar.vue
src/stories/PageTabs.stories.js

The button to navigate between pages should appear.
The button to navigate between pages does not appear
fix the navigation buttons
1. Import attached screen
2. Open screen
[FOUR-14221](https://processmaker.atlassian.net/browse/FOUR-14221)
ci:next
[FOUR-14221]: https://processmaker.atlassian.net/browse/FOUR-14221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-14221 the button to navigate between pages does not appear

---

src/components/sortable/sortableList/SortableList.vue

The numbers next to the name of each page in See all pages should not appear, only the names should be shown
Numbers appear next to the name of each page in See all pages
- Fix the sortable list
1. Open screen
2. Create a few pages 
3. Click on See all pages
[FOUR-14224](https://processmaker.atlassian.net/browse/FOUR-14224)
ci:next
[FOUR-14224]: https://processmaker.atlassian.net/browse/FOUR-14224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-14224 numbers appear next to the name of each page in see all pages

---

src/assets/css/custom.css
src/components/editor/pagesDropdown.vue

The size of the menu is small, it is in black
Its contain is small too
- improve styles
Describe how to test that this solution works.
- Open any screen
- Go to menu dropdown
- https://processmaker.atlassian.net/browse/FOUR-14220
ci:next

FOUR-14220: The size and color of the dropdown button must be adjusted

---

src/components/sortable/Sortable.vue
src/components/sortable/sortableList/SortableList.vue
src/components/vue-form-builder.vue
src/mixins/canOpenJsonFile.js

It should be possible to reorder the pages from the modal
It is not possible to reorder the pages from the modal
Fix the sortable component to allow ordering for imported screens
1. Import attached screen
2. Open screen
3. Click on See all pages
4. Try to move the last page to the top 
[FOUR-14225](https://processmaker.atlassian.net/browse/FOUR-14225)
ci:next
[FOUR-14225]: https://processmaker.atlassian.net/browse/FOUR-14225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-14225  it is not possible to reorder the pages from the modal

---

src/components/vue-form-builder.vue
tests/e2e/specs/pagesDropdown.spec.js

Fix screen creation popup.
- Adjust style to match as best possible the mockups
Create a new Page
- https://processmaker.atlassian.net/browse/FOUR-14230
ci:next

Fix design of page creation

---

src/components/editor/pagesDropdown.vue
src/components/sortable/sortableList/SortableList.vue
src/components/vue-form-builder.vue
src/stories/DropdownAndPages.stories.js
src/stories/Sortable.stories.js
tests/e2e/specs/Pages.spec.js
tests/e2e/specs/Pagination.spec.js
tests/e2e/specs/UndoRedo.spec.js

- Add a calculated property with the sorted pages
- Use the object reference to the page to select the page
1. Create multiple pages
2. Sort the pages
3. Use the drop-down of pages check it has the same order as the step 2
- https://processmaker.atlassian.net/browse/FOUR-14287
ci:next

FOUR-14287 Fix Reordering pages in the modal is not reflected in the menu list

---

src/components/sortable/sortableList/SortableList.vue

New rename page are not being validated
- Add validations to the page rename
Rename the page, use empty or duplicated name for test.
- https://processmaker.atlassian.net/browse/FOUR-14292
ci:next

FOUR-14292 Fix Edit page validation

---

src/assets/css/tabs.css
src/components/TabsBar.vue

Not all tabs are shown in Settings.
- Restore default behavior of tab wrap.
- Add a css class to apply nowrap to SB tabs only
1. Login
2. Go to admin tab
3. Click on Setting option in sidebar menu
- https://processmaker.atlassian.net/browse/FOUR-14341
ci:deploy
ci:next

FOUR-14341 Fix Not all tabs are shown in Settings

---

sonar-project.properties
src/assets/css/custom.css
src/components/TabsBar.vue
src/components/sortable/sortableList/SortableList.vue
src/components/vue-form-builder.vue
src/stories/DropdownAndPages.stories.js
src/stories/PageTabs.stories.js

Need a scroll when the screen has more than 10 pages.
- Add scroll when there are more than 10 pages
- https://processmaker.atlassian.net/browse/FOUR-14223
- https://processmaker.atlassian.net/browse/FOUR-14288
- https://processmaker.atlassian.net/browse/FOUR-14292
- https://processmaker.atlassian.net/browse/FOUR-14293
- https://processmaker.atlassian.net/browse/FOUR-14294
- https://processmaker.atlassian.net/browse/FOUR-14304
- https://processmaker.atlassian.net/browse/FOUR-14305
ci:deploy
ci:next
ci:processmaker:feature/FOUR-13446

FOUR-14293 Add scroll to page drowp down

---

package-lock.json
package.json

update moment and moment-timezone jS. 
ticket
[https://processmaker.atlassian.net/browse/FOUR-13944](FOUR-13944)
ci:next

POC EcoBank - Vulnerable JS

---

src/components/task.vue
tests/e2e/specs/MultiInstanceLoopContext.spec.js
tests/e2e/specs/Task.spec.js

implement a form task autosave feature
Added an autosave draft feature
https://processmaker.atlassian.net/browse/FOUR-14257
https://processmaker.atlassian.net/browse/FOUR-14258
https://processmaker.atlassian.net/browse/FOUR-14259
ci:deploy
ci:next
..

[SPRING] feature/FOUR-14257 autosave

---

src/components/renderer/form-button.vue
src/components/task.vue
src/components/vue-form-renderer.vue
src/mixins/Json2Vue.js
src/mixins/ScreenBase.js

See https://processmaker.atlassian.net/browse/FOUR-14411
- Emit button info as a 3rd parameter in the submit event
- Create an inbox rule, fill form data, and click a submit button. Ensure the correct submit button is shown on the inbox rule config.
- https://processmaker.atlassian.net/browse/FOUR-14411

Send information about what button was clicked when submitting

---

src/components/task.vue

When you have a process with multiple thread levels and interstitial enabled, the interstitial is loaded twice.
- check if the activate event has already arrived.
In order to reproduce the problem you need to add a 2 second sleep to the file
ProcessMaker/Models/ProcessRequest.php
in the notifyProcessUpdated function before sending the event.
In this way a delay is created in the sending of the events.
create a case and then derive it to check that the interstitial is not loaded twice.
- [FOUR-14542](https://processmaker.atlassian.net/browse/FOUR-14542)
[FOUR-14542]: https://processmaker.atlassian.net/browse/FOUR-14542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[36258 ]Interstitial pages load twice

---

src/components/renderer/form-list-table.vue

1. The order of the options
2. The spacing between options
3. The width of the tool tip is much narrower
- https://processmaker.atlassian.net/browse/FOUR-15039
ci:next
ci:deploy
ci:package/dynamic-ui:feature/FOUR-15039

feature/FOUR-15039: The styles of the options in Welcome Screen are not the same as in figma

---

src/components/vue-form-builder.vue

Ticket: [FOUR-14952](https://processmaker.atlassian.net/browse/FOUR-14952)
When opening the Notifications popover, the popover content overflows its container. There are also borders on the tabs and container.
- The styling issues stemmed from screen-builder. Some screen-builder styles that were not scoped were overriding the notification popover styles.
1. Go to branch `observation/FOUR-14952` in `processmaker` and in `screen-builder`.
2. In ProcessMaker, click on the Notifications bell in the top navigation menu.
3. In the popover that appears, the content should be contained within the popover container.
ci:next
[FOUR-14952]: https://processmaker.atlassian.net/browse/FOUR-14952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-14952 | Notification Text Overflows Container

---

src/components/renderer/form-input-masked.vue

Ticket: [FOUR-14904](https://processmaker.atlassian.net/browse/FOUR-14904)
In a Screen that uses Page Navigation and has a Required Input field with Percentage data type, users can submit the Screen without any input in the field.
- In `screen-builder`, there is a bug in `form-input-masked.vue` where backspacing after the decimal does not trigger an input event. The code to handle that bug was no longer working.
- The conditional in the `keyup()` method was not being met, so the code for the bug was not being run.
- Added an `else` statement in the case that the conditional is not met, so that the input event is triggered.
1. Go to branch `observation/FOUR-14904` in `screen-builder`.
2. Go to Designer → Screens → +SCREEN.
3. Create a Screen.
4. Add a Line Input with a Percentage type. Add …

FOUR-14904 | Required Validation Does Not Work With Percentage Input

---

src/components/renderer/card.vue
src/components/renderer/form-new-request.vue

Expand the Start Cases section into two columns in order to remove the Analytics Chart
- The list of new request is showing in two columns
1. Login
2. Go to Home
3. Remove the Analytics Chart
4.The Start Cases section is expanded in Two columns
- [FOUR-16148](https://processmaker.atlassian.net/browse/FOUR-16148)
ci:deploy
ci:next
[FOUR-16148]: https://processmaker.atlassian.net/browse/FOUR-16148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update the new request list

---

src/components/task.vue

- decuple  closeTask 
-  fix Task source behavior
c:next

FOUR-15854: refactor to decouple closeTask

---

src/components/renderer/form-requests.vue

Implement the Open Case for columns **Case #** and **Case Title**
- [FOUR-15763](https://processmaker.atlassian.net/browse/FOUR-15763)
ci:deploy
ci:next
[FOUR-15763]: https://processmaker.atlassian.net/browse/FOUR-15763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-15763:My Cases - Implement the Open Case

---

src/components/task.vue

The user wants to be redirected based on predefined settings, such as the process LaunchPad (of the source process), task list, user homepage dashboard (welcome screen or custom dashboard), a specific dashboard, or an external URL.
[FOUR-15854](https://processmaker.atlassian.net/browse/FOUR-15854)
ci:next
[FOUR-15854]: https://processmaker.atlassian.net/browse/FOUR-15854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-15854 on task completed - override behavior

---

src/components/renderer/form-list-table.vue
src/components/renderer/form-requests.vue

Add the scroll in My Cases
- [FOUR-15764](https://processmaker.atlassian.net/browse/FOUR-15764)
ci:deploy
ci:next
[FOUR-15764]: https://processmaker.atlassian.net/browse/FOUR-15764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUT-15764:My Cases - Implement the scroll in this section

---

src/components/renderer/form-list-table.vue
src/components/renderer/form-requests.vue
src/components/renderer/form-tasks.vue

As a user I want to see a diferent UI in the filters of the Tasks and Cases
- https://processmaker.atlassian.net/browse/FOUR-15535
ci:deploy
ci:next
ci:package-dynamic-ui:feature/FOUR-15535

feature/FOUR-15535: Adjust UI in filters of menues in Tasks and Cases

---

src/components/renderer/form-new-request.vue

Cards in Start a new Case are very close in dashboard list 
- [FOUR-16316](https://processmaker.atlassian.net/browse/FOUR-16315)
ci:deploy
ci:next
[FOUR-16316]: https://processmaker.atlassian.net/browse/FOUR-16316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-16315: Cards in Start a new Case are very close in dashboard list

---

src/components/renderer/file-download.vue

When you upload more than 1 file running a test, you will get a 404 error after submitting the form
- Put the File Preview and File Download controls into a Loop control
- Add a validation to files as an instance of Media
https://github.com/ProcessMaker/processmaker/assets/3604190/ec011df0-aa07-42c1-9442-72cc4fbc2fcd
[FOUR-15485](https://processmaker.atlassian.net/browse/FOUR-15485)
https://github.com/ProcessMaker/package-files/pull/129
ci:next
ci:deploy
ci:package-files:FOUR-15485
[FOUR-15485]: https://processmaker.atlassian.net/browse/FOUR-15485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-15485 37736 - Runing a test case gives 404 error with multiple file upload

---

src/components/task.vue
tests/e2e/specs/MultiInstanceLoopContext.spec.js
tests/e2e/specs/Task.spec.js

ent event must redirect to another process if have this configuration
- add another process redirect feature for end event
https://github.com/ProcessMaker/screen-builder/assets/1401911/9a8f267f-c40b-477c-ae4c-255642272bef
Uploading endEventProcessRedirect.mov…
Uploading endEventProcessRedirect.mov…
- create the process A
- create the process B
- assign to both process the same user to the first task
- in process A create a end event 
- add end event redirection as process
- select the process B
- select the start event B
- run the process
-  https://processmaker.atlassian.net/browse/FOUR-15859
- https://github.com/ProcessMaker/processmaker/pull/6918 
ci:next

FOUR-15859: On Process End - Start a request for another selected process

---

src/components/task.vue

While loading a task the user can modify the data, this can cause the lost of the changes once the task is loaded.
- Screen can be disabled while task is being loaded to avoid data missing
- https://processmaker.atlassian.net/browse/FOUR-15486

FOUR-15486 Screen can be disabled while task is loading

---

src/components/computed-properties.vue
tests/e2e/specs/CalcDragAndDrop.spec.js

As a Designer when I open the Calc options I would like to have a bigger space in the “Formula Field”
https://github.com/ProcessMaker/screen-builder/assets/3604190/046ef0e1-ac8b-45cf-abc9-0fd29c6ac260
[FOUR-13456](https://processmaker.atlassian.net/browse/FOUR-13456)
ci:next
[FOUR-13456]: https://processmaker.atlassian.net/browse/FOUR-13456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-13456 enlarge the source code field in the calcs window

---

src/customLogs.js
src/mixins/computedFields.js
src/mixins/watchers.js
tests/e2e/specs/WatchersDragAndDrop.spec.js

As a Designer I want to have the option where I can see the Logs after the Watchers run
https://github.com/ProcessMaker/screen-builder/assets/3604190/5eb9e209-2af0-4b28-8a47-6bfe31bf3c64
[FOUR-13459](https://processmaker.atlassian.net/browse/FOUR-13459)
ci:develop
[FOUR-13459]: https://processmaker.atlassian.net/browse/FOUR-13459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-13459 logs section for watchers

---

src/components/watchers-form.vue
src/components/watchers-popup.vue
tests/e2e/specs/Watchers.spec.js

As a Designer  when I open a Watcher options I would like to have a bigger space into the “Formula Field”
n/a
- enlarge the modal and the formula field
- https://processmaker.atlassian.net/browse/FOUR-13460

FOUR-13460: Enlarge the source code field in the Watchers window

---

src/components/renderer/form-requests.vue
src/components/renderer/form-tasks.vue

Review Ui Dependencies with Improvements team
- [FOUR-16240](https://processmaker.atlassian.net/browse/FOUR-16240)
ci:next
ci:deploy
[FOUR-16240]: https://processmaker.atlassian.net/browse/FOUR-16240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-16240:Review Ui Dependencies with Improvements team

---

src/components/sortable/sortableList/SortableList.vue
src/components/sortable/sortableList/sortableList.scss
tests/e2e/specs/WatchersDragAndDrop.spec.js

An add button should not appear when doing drag and drop in Calcs and watchers
An add button appears when doing drag and drop in Calcs and watchers
- Hide the plus icon
- Add tooltips to edit and delete buttons
1. Import attached secreen
2. Go to designer tab
3. Search screen and edit
4. First scenario: Calcs
5. Click on Calcs button
6. Drag and drop last Calc(C3) to top
[FOUR-17044](https://processmaker.atlassian.net/browse/FOUR-17044)
ci:next
[FOUR-17044]: https://processmaker.atlassian.net/browse/FOUR-17044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-17044 an add button appears when doing d&d

---

src/components/computed-properties.vue
src/components/sortable/sortableList/SortableList.vue
src/components/sortable/sortableList/sortableList.scss
src/components/watchers-form.vue
src/components/watchers-popup.vue
tests/e2e/specs/Watchers.spec.js

- Create some calc properties
- Create some watchers
- https://processmaker.atlassian.net/browse/FOUR-17054
ci:next

FOUR-17054

---

src/components/computed-properties.vue

A confirmation message should appear before deleting a calcs
- add confirmation message to delete a calc
https://github.com/ProcessMaker/processmaker/assets/1401911/a2a6b39e-d5d3-4aad-bd91-0d94e9254303
Describe how to test that this solution works.
- confirmation message was added
- https://processmaker.atlassian.net/browse/FOUR-17058

FOUR-17058: A confirmation message should appear before deleting a calcs

---

src/components/computed-properties.vue
src/components/sortable/Sortable.vue
src/components/watchers-list.vue
src/stories/Sortable.stories.js

Search must rpovide the list of all calcs with the selected criteria. It also must search with newTotal or newLeave
When writing new, the search selects one of the two calcs despite both starting with “new”. 
- improve filterItem method  to make a clean search in the defined properties
https://github.com/ProcessMaker/screen-builder/assets/1401911/bd64bcba-fa09-4e74-804f-c5a3079907a6
1. Have a set of calcs with names as in the video
2. Write “new”
- https://processmaker.atlassian.net/browse/FOUR-16802

FOUR-16802: Search is Faling When Two Names Are Partially the Same

---

README.md
src/components/computed-properties.vue
src/components/sortable/Sortable.vue
src/components/sortable/sortableList/sortableList.scss
src/components/vue-form-builder.vue
src/components/watchers-list.vue

The distribution of the edit page columns should not be modified, it should look like the image below
The distribution of columns in edit page has been modificated
- add a min-width property to first second column
- remove unused property
1. Login
2. Create screen or import attached screen
3. Search screen and edit
4. Click on menu button
5. Click on See all pages
[FOUR-17142](https://processmaker.atlassian.net/browse/FOUR-17142)
ci:next
ci:deploy
[FOUR-17142]: https://processmaker.atlassian.net/browse/FOUR-17142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-17142 the distribution of columns in edit page has been modified

---

src/DataProvider.js
src/components/inspector/options-list.vue

Please see https://processmaker.atlassian.net/browse/FOUR-15004
To reproduce:
- Create a screen 
- Add an input with a default and name it **user** (you can use your custom example)
- Add a select list of type data connector (you can use the users endpoint)
- Configure Options Variable: response.data
- Type of Value Returned: Object
- Content {{data.username}}
- Data connector: Users
- Endpoint ListAll
- Add a PMQL: **data.username="{{user}}"** (user is the name of the input you added before)
- Go to preview and type some valid user in the input to make the pmql trigger and change the option list of the select
https://github.com/ProcessMaker/processmaker/assets/90727999/2fa1ce60-a5e5-44b8-9d45-4389aa603c6a
- Fix PMQL render and code refactor for dataconnector
- Fix issue …

Bugfix/FOUR-15004: PMQL in record list doesnt work with pm variables

---

src/mixins/ValidationRules.js
tests/e2e/specs/FormInput.spec.js

34947 - The line input control of type integer or currency, with the required validation, does not recognize 0 as an integer
The required field should disappear when entering a zero value, because zero is considered an integer.
You will see that the required field does not disappear
- Improve required logic to support 0 integer
https://github.com/ProcessMaker/screen-builder/assets/1401911/9d2aef5d-e831-45e9-b4a9-8d4fff70d527
1. Create a form type screen (or import the attached file)
2. Go to designer tab
3. Click on the "Screens" option
4. Click on "+Screen" button
5. Fill in the fields: name and description
6. Select "Form" in the Type field
7. Click on save button
8. Create  2 "Line Input" control to modeler
9. Configuring the …

FOUR-7157: 34947 - The line input control of type integer or currency, with the required validation, does not recognize 0 as an integer

---

src/components/renderer/form-list-table.vue

Scroll does not appear with hover in START NEW CASE as in the other dashboards
- [FOUR-16643](https://processmaker.atlassian.net/browse/FOUR-16643)
ci:next
[FOUR-16643]: https://processmaker.atlassian.net/browse/FOUR-16643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-16643:Scroll does not appear with hover in START NEW CASE as in the other dashboards

---

src/mixins/Json2Vue.js

hen the calc has bypass activated, the content of the entire form is not displayed
The content of the screen should be displayed, only the calcs values ​​should not be displayed
When the calc has bypass activated, the content of the entire form is not displayed (For example: New submit Button  is not showed)
- improve isComputedVariable method to support byPass computed property
Detailed in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-17261
c:next

FOUR-17261: When the calc has bypass activated, the content of the entire form is not displayed

---

src/components/task.vue

If we do not have interstitial enabled in the tasks, we should not jump to the next form
As we see, the tasks are shown alone without opening in the Form Task
- Validate interstitial on redirect to the next task
1. Log in 
2. Create a process with a task 
3. Verify that the tasks and the start event are not configured with interstitial
4. Start a new  case
[FOUR-17160](https://processmaker.atlassian.net/browse/FOUR-17160)
[FOUR-17272](https://processmaker.atlassian.net/browse/FOUR-17272)
ci:next
[FOUR-17272]: https://processmaker.atlassian.net/browse/FOUR-17272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-17160]: https://processmaker.atlassian.net/browse/FOUR-17160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

FOUR-17272 tasks in a process without interstitial automatically skip to the next task

---

package.json
src/components/renderer/form-requests.vue
src/components/renderer/form-tasks.vue

It is not possible to resize the columns in MY TASK , MY CASES Dashboards
- [FOUR-16829](https://processmaker.atlassian.net/browse/FOUR-16829)
ci:next
.
[FOUR-16829]: https://processmaker.atlassian.net/browse/FOUR-16829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-16829: It is not possible to resize the columns in MY TASK , MY CASES Dashboards

---

src/components/task.vue

When a webentry is opened, it does not count with request or task, this caused error in the Task component new changes. Also the screen kept disabled because of that.
Also there is a problem in the screens endpoint when selecting an screen.
- Fix the initialization of the Task considering it could not have a request
- Disable the screen at the begining only when a request is present
- Fix screen endpoint and add some tests to validate it.
https://github.com/user-attachments/assets/25661c71-5648-4dde-ba8c-9aa8e2ed7b5c
- Create a process with an anonnymous webentry
- Variations: With interstitial screen
- Variation: Without interstitial screen
- Open the web entry
- Complete the form
- https://processmaker.atlassian.net/browse/FOUR-17258
ci:next

FOUR-17258 Fix Task Initialization in Webentries

---

src/components/task.vue

"Display next task to assignee" option is not redirecting to the next task and the submit button was not submitting to the correct endpoint (node id in the url was wrong)
- `this.nodeId` needs to be set before `loadTask` because webentry needs to load the config with the new nodeId (using the `beforeLoadTask` hook)
See jira issue
- https://processmaker.atlassian.net/browse/FOUR-17438
- Requires: https://github.com/ProcessMaker/screen-builder/pull/1660

Set node id before loading the task for webentry

---

src/components/task.vue

When Task Source (default) is selected, the Task should be opened and displayed on the screen with the Claim message
The next task is not displayed and a loop displays the completed task message 
- Add a session variable to identify when a Task was claimed
https://github.com/user-attachments/assets/96ae4684-0308-4f8d-baf7-77814deb1a5f
See the ticket
[FOUR-17911](https://processmaker.atlassian.net/browse/FOUR-17911)
ci:next
[FOUR-17911]: https://processmaker.atlassian.net/browse/FOUR-17911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-17911 loop created between two tasks with self service

---

src/components/task.vue
tests/e2e/specs/Task.spec.js

Fix Processes that are started with another thread do not display the screen
- Use an specific event to handle the redirection.
Review the steps in ticket: https://processmaker.atlassian.net/browse/FOUR-17581
- https://processmaker.atlassian.net/browse/FOUR-17581
ci:next

FOUR-17581 Fix Processes that are started with another thread do not display the screen

---

src/components/vue-form-builder.vue

The list of components is not displayed correctly when a component is found that does not have the group to which it should be registered defined.
The component list should be displayed normally.
If a component is registered from a package and does not have a group defined, the component listing is blocked.
- Add a default group if the group is not defined.
-  [FOUR-17914](https://processmaker.atlassian.net/browse/FOUR-17914)
ci:next
[FOUR-17914]: https://processmaker.atlassian.net/browse/FOUR-17914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Screen components are not displayed

---

src/components/task.vue

- When redirecting to a new place there is a case when the task is not yet loaded after submitting a web entry to a second task after script tasks. 
- When refreshing a task with a nested screen in web entry SB is not passing the request_id for a validation.
- Add a check to verify if the task was loaded
- Remove the validation of request_id in the web-entry screen endpoint
- Run the Expences Process template.
- Load a receipe
- The scripts are executed
- The expences are loaded
- Refresh the screen
- https://processmaker.atlassian.net/browse/FOUR-18861
ci:next

FOUR-18861 Fix Webentry issue routing to form task

---

src/components/task.vue

The redirect to next task was working only with interstitial enabled
- Enable redirect to next task when the next assigned user is the same of the current task as defined in the PRD
- https://processmaker.atlassian.net/browse/FOUR-18860
ci:next

FOUR-18860 Fix User completes a task and is assigned the next one is not redirected to form the next task

---

src/components/task.vue

- When the endpoint to get the tasks returns before the script execution it causes to emit a close task preview since the next task is not yet assigned, then it redirects to task list.
- The event close task preview is not required anymore, and wait for the new redirect/interstitial handler.
- Import the processes
- Run the process
- Interstitial waits for script conclusion
- Opens the next task screen
- https://processmaker.atlassian.net/browse/FOUR-18858
ci:next

FOUR-18858 Fix The create request doesn’t open the screen

---

src/components/task.vue

The user should be redirected to form of the next task
The user is redirected to next task (TCP43716TC)
- add support for currentTask.elementDestination type equal to null
https://github.com/user-attachments/assets/a1c3eedd-2c78-4ed8-9666-d0eacbafc4bd
ci:next
Described in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-18860

FOUR-18860: User completes a task and is assigned the next one is not redirected to form the next task

---

src/components/renderer/file-upload.vue

1. Login and visit the next URL file-manager/public.
2. Upload the next PDF file
[pdfgarlito.pdf](https://github.com/user-attachments/files/16849360/pdfgarlito.pdf)
3. Open the uploaded file and press over the direct link of the file:
Current Behavior: 
When opening the file a JavaScript alert will be displayed
PDF files with dangerous content should be controlled.
- File upload endpoint (in PM Core) now validates if a PDF file has JavaScript included
- file-upload component in Screen Builder now adds file upload error handling
- When the file upload of a PDF file fails, a message is displayed.
Use the reproduction steps
- Link to any related FOUR tickets, PRDs, or packages
Ticket: https://processmaker.atlassian.net/browse/FOUR-16700
PRs …

FOUR-16700: XSS via PDF File Upload (for 4.10.2)

---

src/components/renderer/file-upload.vue

To reproduce:
Create as screen with a file upload
Use the screen in a process
Upload a PDF with malicious code: 
Current behavior:
The PDF upload returns an error but no additional info is displayed
image-20240905-142801.png
Expected behavior
A more descriptive message should be displayed to users, like when uploading a PDF file in files/public
- File errors handled in screen builder file upload component
https://processmaker.atlassian.net/browse/FOUR-18988

FOUR-18988: Display message if file upload fails (for 4.10.2)

---

src/components/ScreenTemplateCard.vue
src/components/ScreenTemplates.vue
src/components/screen-templates.vue
src/components/vue-form-builder.vue

This PR adds a new section in the screen builder that dynamically populates with templates when the 'Templates' button is selected. It fetches both user-specific and shared templates via API calls and displays the results in the right panel of the screen builder.
- Implemented API calls to retrieve both "My Templates" and "Shared Templates" data from the backend.
- Added a new section in the right panel of the screen builder to display the retrieved templates when the 'Templates' button is clicked.
1. Navigate to the screen builder interface.
2. In the screen builder navigation menu, click the 'Templates' button to trigger the template loading process.
3. Ensure that API calls are made to fetch "My Templates" and "Shared Templates" correctly.
4. Once the templates are retrieved, confirm …

Add Screen Templates Section in Screen Builder

---

src/components/renderer/file-upload.vue

Create a simple process (start event - taskA - taskB - end event)
Run a Case
Upload a file (dangerous PDF) in the file control (single or versioning)
Close the message
Current Behavior:
When a Dangerous PDF file is uploaded an Browser’s alert is displayed.
if user presses cancel or leave options,  an alert is displayed again
The submit button is interrupted and the task list is not displayed.
The Browser’s alerts should not be displayed when  a Dangerous PDF file is uploaded in the file control
The submit button should work correctly without interrupt
- Remove the onload event when a file upload fails
[- ](https://processmaker.atlassian.net/browse/FOUR-19008)
ci:1.4.0+patch-ellucian
ci:deploy

FOUR-19008: Browser's alerts are displayed when a `Dangerous PDF file` is uploaded and submit button is interrupted  (for 4.10.2)

---

src/components/task.vue

Redirect to Summary Screen from End Event with Multiple Tasks Parallel Assigned
Task TCP4-4247-A completed should redirect to Task List
Task TCP4-4247-B completed should redirect to Welcome Screen
Task TCP4-4247-C completed should redirect to Summary Screen
Task TCP4-4247-A completed is not redirected according to the Element Destination configuration
Task TCP4-4247-B completed is not redirected according to the Element Destination configuration 
- Verify if the request is active once the parallel task is completed
https://github.com/user-attachments/assets/38663ece-3443-42d6-b47f-20e777153329
see the ticket
[FOUR-18984](https://processmaker.atlassian.net/browse/FOUR-18984)
ci:next
[FOUR-18984]: …

FOUR-18984 Parallel Task is not redirected according element destination configuration once completed

---

src/components/renderer/file-upload.vue

1. Login and visit the next URL file-manager/public.
2. Upload the next PDF file
[pdfgarlito.pdf](https://github.com/user-attachments/files/16849360/pdfgarlito.pdf)
3. Open the uploaded file and press over the direct link of the file:
Current Behavior: 
When opening the file a JavaScript alert will be displayed
PDF files with dangerous content should be controlled.
- File upload endpoint (in PM Core) now validates if a PDF file has JavaScript included
- file-upload component in Screen Builder now adds file upload error handling
- When the file upload of a PDF file fails, a message is displayed.
Use the reproduction steps
- Resolved tickets:
https://processmaker.atlassian.net/browse/FOUR-16700
https://processmaker.atlassian.net/browse/FOUR-18988 …

FOUR-16700: XSS via PDF File Upload 

---

src/components/task.vue

- When the process run, it ends before the request page is loaded
- The page missed all the redirection events so it stays in white
- Catch when the process ends during the Task component mounting and execute the end event redirection.
- Requires: Core branch FOUR-19102
- Run the processes described in the ticket
- The script could something like:
```
<?php
return [];
```
- Usa nayra executor (runs a bit faster that php executor)
- https://processmaker.atlassian.net/browse/FOUR-19102
ci:next
ci:connector-idp:bugfix/FOUR-19124

FOUR-19102 Fix Redirect when the process ends before load the request

---

src/App.vue
src/components/ScreenTemplates.vue
src/components/ScreenToolbar.vue
src/components/vue-form-builder.vue
tests/e2e/specs/ScreenTemplateSection.js

Ticket: [FOUR-18303](https://processmaker.atlassian.net/browse/FOUR-18303)
This PR introduces comprehensive Cypress tests for the Screen Templates Panel in screen-builder and enhances Screen Templates Panel visibility.
The tests check that:
- The Screen Templates Panel opens when the 'Templates' button is clicked
- The Screen Templates Panel closes when the 'X' button in the Panel is clicked
- The Screen Templates Panel is hidden when a control is clicked and an Inspector Panel should open
This PR also Ensures the 'Templates' button is always visible, even without `package-versions` or `processmaker` integration.
1. Go to branch `task/FOUR-18303` in `screen-builder` and `processmaker`.
2. Go to Designer → Screens. Create a Screen.
3. The 'Templates' button should display in …

FOUR-18303 | Write Tests for Screen Templates Section

---

src/components/ScreenTemplateCard.vue
src/components/ScreenTemplates.vue
src/components/vue-form-builder.vue

Tickets:
[FOUR-18326](https://processmaker.atlassian.net/browse/FOUR-18326)
[FOUR-18328](https://processmaker.atlassian.net/browse/FOUR-18328)
[FOUR-18329](https://processmaker.atlassian.net/browse/FOUR-18329)
This PR introduces logic for Applying Layouts and Fields to Screens via the Screen Templates Panel in `screen-builder`.
When a user chooses to only apply the layout from a template to their screen:
- The layout is added to the bottom of the screen, enabling the user to arrange the existing information as needed.
- When the screen has more than one page, the changes will be added to the bottom of the current page.
When a user applies only the fields:
- The fields are added to the bottom of the screen, providing the user with flexibility to reposition them as required.
- When the …

FOUR-18326 | Implement Layout Application Logic

---

src/components/editor/multi-column.vue
src/components/vue-form-builder.vue
src/mixins/Clipboard.js
src/store/modules/clipboardModule.js
tests/e2e/specs/ClipboardDragPaste.spec.js

- Implement the paste funcionality using the vuedraggable events
- Creates a clone of the clipboard items with new uuids
- Add some elements and controls
- Select each control and add it to the clipboard
- Open a new screen with the same user Or in the same screen
- Open the clipboard section
- Drag and paste the clipboard content into the screen
https://github.com/user-attachments/assets/3505ec69-be8a-43d1-99cd-066cb12b8012
- https://processmaker.atlassian.net/browse/FOUR-13441
ci:next

FOUR-13441 STORY Paste clipboard items where dropped

---

src/DataProvider.js
src/components/task.vue

This PR is part of: https://github.com/ProcessMaker/processmaker/pull/7427
**Current behavior**
- Changes applied on a screen and published are only reflected in new cases. in 4.10 the changes were reflected in new and also ongoing cases
**Expected behavior**
- Change should be reflected in ongoing cases.
- Added a version parameter (screen_version) to screen URLs, generated based on the latest published id of the screen.
- This approach forces the browser to treat each updated published screen as a new resource, preventing the use of outdated cached versions.
- Verify that screen updates generate new URLs with different version parameters, ensuring that changes are correctly fetched.
- Test across different browsers to confirm that old cached versions are not used.
- …

FOUR-19110: [40531] changes on screen are not reflected in ongoing cases

---

src/components/task.vue

The Disabled variable remained set to true after clicking submit.
Links should be clickable
Can't click on links
- Set disabled after load next assigned task
step in ticket
- [FOUR-19407](https://processmaker.atlassian.net/browse/FOUR-19407)
ci:next
ci:deploy
[FOUR-19407]: https://processmaker.atlassian.net/browse/FOUR-19407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[40754] Links added to a Display screen set as a "screen for completed" in Web entries are not working

---

src/App.vue
src/components/TabsBar.vue
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue
src/mixins/Clipboard.js
src/store/modules/ClipboardManager.js
src/store/modules/clipboardModule.js
tests/e2e/specs/ClipboardManager.spec.js

- Open multiple pages and screens
- Add/Select some elements
- Add them to the clipboard
- Paste the items to different pages or screens
https://github.com/user-attachments/assets/1ac558ad-8993-4f6e-a0ae-1f69d0d01f38
- https://processmaker.atlassian.net/browse/FOUR-13443
ci:next

FOUR-13443 Implement Clipboard usage between pages or separate screens

---

src/App.vue
src/components/ScreenToolbar.vue
src/components/TabsBar.vue
src/components/vue-form-builder.vue
src/components/vue-form-renderer.vue
src/mixins/Clipboard.js
src/store/modules/ClipboardManager.js
src/store/modules/clipboardModule.js
tests/e2e/specs/ClipboardManager.spec.js

FOUR-18059 Clipboard Tab

---

src/DataProvider.js
src/components/accordions.js
src/components/inspector/collection-data-source.vue
src/components/inspector/collection-records-list.vue
src/components/inspector/column-setup.vue
src/components/inspector/page-select.vue
src/components/renderer/form-record-list.vue
src/form-builder-controls.js
tests/e2e/specs/Pagination.spec.js

- Login PM4
- Create new Screen
- Drag Record List control
- Choose new option Collection
- Select Collection
- Add columns from collection
- Preview changes
https://processmaker.atlassian.net/browse/FOUR-18109
ci:next

Feature/FOUR-18109: STORY Column Configuration for Collections y Record List

---

src/components/renderer/form-record-list.vue

this branch is based on previous ticket FOUR-18337-b
- Login PM4
- Go to Designer->Screens
- Create New Screen
- Drag Record List control
- Select a Collection
- Set some Columns
- In Data Selection dropdown Choose Multiple Records
- Make tests with different combinations of selected rows
https://processmaker.atlassian.net/browse/FOUR-18338
ci:next

Feature/FOUR-18338: FOUR-18337-b - FOUR-18113- Load same selections when the screen loads

---

src/components/inspector/collection-data-source.vue
src/components/renderer/form-record-list.vue

-Login PM4
-Create new Screen
-Drag Record List control
-Choose new option Collection
-Select Collection
-Add columns from collection
-In Data Selection dropdown select Single Record, Record or Multiple records
-Use a rich text to Use the output Variable Name from record list like {{form_record_list_1.ColumnName}}
-Save Screen and start a new Case
https://processmaker.atlassian.net/browse/FOUR-18337
ci:next

Feature/FOUR-18337-b: FOUR-18113 - Implement logic to insert into screen data

---

src/components/inspector/collection-data-source.vue
src/components/inspector/page-select.vue
src/components/renderer/form-record-list.vue
tests/e2e/specs/Pagination.spec.js

- Login PM4
- Go to Screens and create a new Screen
- Drag Record List control
- Select Collection
- Setup the columns
- In Data Selection dropdown Choose Column of Record, Record or Multiple Records
- Click on Preview and check if Table render wit Radio Buttons or Checkboxes(for multiple records)
https://processmaker.atlassian.net/browse/FOUR-18327
ci:next

Feature/FOUR-18327: FOUR-18113 - UI - checkbox/radio on collection rows

---

src/components/task.vue

See Jira Issue
Unclaimed self-service tasks should not be editable
Thee self -serve task allowed editing before being claimed
- Call setSelfService on mounted
See jira issue
- https://processmaker.atlassian.net/browse/FOUR-19478
ci:next

Set self-service property on mounted

---

src/components/ScreenTemplates.vue
src/components/vue-form-builder.vue
tests/e2e/specs/ScreenTemplateSection.spec.js

This PR updates the filtering of screen templates to ensure that only templates compatible with the current screen type (e.g., FORM, DISPLAY, EMAIL) are visible in the "My Templates" and "Shared Templates" sections of Screen Builder. This helps users by showing only relevant templates based on the type of screen they are working on.
- Added the `screen-type` property to the `screen-templates` component.
- Implemented the `screenType` filter in API requests for both "My Templates" and "Shared Templates".
1. Create Screen Templates
2. Ensure screen templates are available for various screen types such as FORM, DISPLAY, EMAIL, etc.
3. Create or navigate to a screen using a specific screen type (e.g., DISPLAY).
4. Select the "Templates" option in the navigation bar.
5. In the "My Templates" …

Filter Screen Templates Based on Screen Type in Screen Builder

---

package-lock.json
package.json
src/components/renderer/file-upload.vue

This PR consolidates all changes related to conversational form enhancements in the Screen Builder, focusing on file upload functionality and runtime autosaving.
1. File Upload Control Support for Conversational Forms:
- Added full support for the File Upload control in conversational form screens.
- Updated UI elements to align with the rendering requirements of conversational forms.
2. Autosaving During Runtime:
- Implemented the `@update` event listener for `<components>` to enable automatic saving of data as changes occur during conversational form runtime.
[FOUR-18018](https://processmaker.atlassian.net/browse/FOUR-18018)
[Conversational Forms Package PR](https://github.com/ProcessMaker/package-conversational-forms/pull/62)
[Ai Package …

[EPIC FOUR-18018] Conversational Form Updates for Screen Builder

---

src/components/renderer/form-masked-input.vue
src/main.js

https://processmaker.atlassian.net/browse/FOUR-19236

FOUR-19236 Encryption is Not Working in Authenticated Web Entry

---

package-lock.json
package.json
src/components/SelectUserGroup.vue
src/components/accordions.js
src/components/inspector/encrypted-config.vue
src/components/inspector/index.js
src/components/renderer/form-masked-input.vue
src/global-properties.js
src/main.js
vite.config.js

Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).
Implemented new attribute for "line input" fields called "Encrypted"
- Implemented new attribute for "line input" fields called "Encrypted"
- When this new attribute is enabled the designer can assigne users and/or groups
- These users/groups can encrypt/decrypt data
- When the field is rendered a new button will be displayed
- This buttons display the labels "Conceal" or "Reveal" depending the data status
- The first time when the data was not previously conceladed the data is displayed plain
- After click in "Conceal" data is encrypted and an UUID is returned
- This UUID is stored in the request data
- When the data is already concealed the "Reveal" …

FOUR-18064 Encrypted Field in the Screen Builder

---

src/components/renderer/file-upload.vue

- https://processmaker.atlassian.net/browse/FOUR-16701
ci:next

FOUR-16701: Unrestricted File Upload

---

src/form-control-common-properties.js
tests/e2e/specs/Builder.spec.js

A variable with too many nested objects (dots) in the name was causing the screen to freeze. This was because the regex used to validate the string was inefficient.
- Replace the regex with a custom validator function
See jira issue
- https://processmaker.atlassian.net/browse/FOUR-14970
- Requires: https://github.com/ProcessMaker/vue-form-elements/pull/438
ci:next
ci:deploy
ci:vue-form-elements:bugfix/FOUR-14970

FOUR-14970 Replace regex with dot_notation validator

---

src/components/ScreenTemplateCard.vue

Ticket: [FOUR-19658](https://processmaker.atlassian.net/browse/FOUR-19658)
When a user selects an icon in the template details page, the card closes automatically. This interrupts the user flow, preventing them from making additional selections or adjustments. The card should remain open until the user explicitly selects the 'Cancel' button.
- Set checkbox value when icon is selected.
- Stop event propagation when icon is selected.
- Stop event propagation when 'Cancel' button is selected.
1. Go to branch `observation/FOUR-19658` in `screen-builder`.
2. Go to Designer → Screens. Open a Screen to edit.
3. Select 'Templates' from the top menu bar. Select a template card.
4. When the template card opens:
- Select an icon; the corresponding checkbox should be selected. The card should not …

FOUR-19658 | Icon Selection Closes Card Prematurely In Template Details Page

---

src/components/vue-form-builder.vue
tests/e2e/specs/TCP4-4447VerifyUpdateConfigurationClipboard.spec.js

Remove control from clipboard when the related control property is modified
if the user updated a control property the control was not deleted from clipboard
- add a method to manage control config updates and if there are diferences update the uuid
https://github.com/user-attachments/assets/0e299ab3-210f-4b0b-8776-796ce51dd796
detailed in the test
- https://processmaker.atlassian.net/browse/FOUR-19611

FOUR-19611: Remove control from clipboard when the related control property is modified

---

src/components/renderer/form-collection-record-control.vue
src/components/renderer/form-collection-view-control.vue

- Record ID field support mustache syntax
- Login PM4
- Go to Designer->screens
- Select an existing screen or create one in mode FORM
- Drag Collection Record Control
- Select a Collection
- In Record ID field enter {{ id_record }}
- Drag an input field and rename as id_record
- Go to Preview Button, and type some Number in the input field
- The Collections fields must be shown
https://processmaker.atlassian.net/browse/FOUR-19277

Bugfix/FOUR-19277: Collection Record control displays different errors when mustache variable is assigned in the `record ID` field

---

src/components/renderer/file-upload.vue

This PR addresses the issue where error messages were unclear when SVG file uploads failed. The existing error message was not specific enough, making it difficult for users to understand why the file upload was failing.
- Navigate to the file manager
- Upload attached SVG within the ticket.
- The file fails to upload and is unclear why.
- Give a reasonable human readable feedback to the user
- Unclear error message
- Improved error handling for SVG file uploads.
- Updated the error message to provide more specific details about the failure (e.g., unsupported tags).
- Refined validation logic to catch SVG-related issues early and report them more clearly to the user.
- Give feedback in how to resolve the issue to the user.
- ![Screenshot 2024-10-21 at …

Bugfix-FOUR:19706: Improve error message when SVG's fails to upload - Fall

---

src/mixins/Clipboard.js

The Clipboard Pasted Successfully message should be displayed after d&d the Clipboard control according to the Figma
The Clipboard Pasted Successfully message isn’t displayed
- add  window.ProcessMaker.alert to display the message
https://github.com/user-attachments/assets/0868cc45-52b8-4751-8fa3-f633dea8e9b2
described in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-19784

FOUR-19784: Clipboard Pasted Successfully message isn't displayed

---

src/components/vue-form-builder.vue
src/mixins/Clipboard.js
tests/e2e/specs/ClipboardTabClearAll.spec.js

The Clipboard should be cleared according to the PRD
The Clipboard isn’t cleared after adding some controls to the Clipboard page
- Clean clipboard page items after the user press clear all link
https://github.com/user-attachments/assets/22efd489-af43-4464-b947-d3fa9f3c7483
defined in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-19767

FOUR-19767: Clipboard isn't cleared after add a new control

---

src/components/renderer/file-upload.vue

This PR addresses two key issues related to file persistence within File Upload components in Screen Builder:
1. Ensures that uploaded files remain persisted after a page reload.
2. For multiple file uploads, ensures that the initial uploaded file persists after page reload when additional files are uploaded.
The solution introduces a `fetchFile` function, which retrieves uploaded files by their ID on component mount if `this.value` exists, providing consistent file persistence across reloads.
- Implement `fetchFile` logic to retrieve uploaded files by ID when `this.value` is present during component mount.
- Update file handling logic to support both single and multiple file upload configurations.
- Ensure you have `package-versions` installed to utilize the Autosave functionality
- …

[FALL] Fix File Persistence on Page Reload for Single and Multiple File Uploads

---

src/components/editor/loop.vue
src/components/editor/multi-column.vue
src/components/vue-form-builder.vue
tests/e2e/specs/Clipboard.spec.js
tests/e2e/specs/ClipboardTestCases.spec.js

The message “Copied“ should be displayed once a control is added to the Clipboard
The message “Copied“ doesn’t appear when a control is added to the Clipboard
- add Copied badge 
https://github.com/user-attachments/assets/c22be2a9-63f6-467a-b43d-9fc57f956577
defined in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-19756
ci:processmaker:release-2024-fall

FOUR-19756: Message COPIED doesn't appear when a control is added to Clipboard

---

src/components/renderer/form-masked-input.vue
tests/e2e/specs/EncryptedField.spec.js

"readonly" attribute should be considered when a value is revealed/plain
"readonly" attribute is omitted
Keep a copy of the original values in order to restore the correct "readonly" mode
https://processmaker.atlassian.net/browse/FOUR-19778

FOUR-19778 Encrypted field does not have read-only mode

---

src/components/renderer/form-collection-record-control.vue

- When a task with Collection Record Control has data recovered from DRAFT, once Form is submited, only fields displayed in the screen must be updated in Collection's Table.
- Only fields on the collection edit screen are updated, and fields that are not displayed remain unchanged in the database.
-Login PM4
- Go to Designer-> screens
- Create or use previous screens
- Drag Collection Record Control
- Choose a collection that does not show all its fields on screen in Edit Mode and with "Update on submit" checked
- Save and Start a case with that screen
-  Change values from collection fields and wait for auto save as Draft.
- Reload the Screen to recover Draft data
- Submit the form
- Go to Collections and review all Collection Fields remain correct (There should be no …

bugfix/FOUR-19806: Collection columns not selected in Edit Screens are deleted when Draft data is recovered in task using CollectionRecordControl

---

src/components/ScreenTemplateCard.vue

Ticket: [FOUR-19877](https://processmaker.atlassian.net/browse/FOUR-19877)
While there is a character limit on Template names on Screen Template Cards (in the Screen Templates Panel), the name should also be truncated when displayed in the card to prevent size differences between cards. The template description has also been shortened on the template card, so that only two lines of the description are displayed.
- Truncate template name via `truncateText` method.
- Truncate template description more, so that only two lines of text show, similar to the [Figma mockups](https://www.figma.com/design/Jfl3HAOx28TVHMl7cHJNIP/Fall-2024?node-id=522-6369&node-type=canvas&t=mL6S21BBVGuQ66tR-0).
1. Go to branch `observation/FOUR-19877` in `screen-builder`.
2. Go to Designer → Screens.
3. Create a …

FOUR-19877 | Truncate Template Name on Screen Template Cards

---

src/components/inspector/encrypted-config.vue

- Go to screen designer
- Add or edit a line input field
- Enable "encrypted" in "Advanced" section
Should be displayed the label "Users/Groups to View Encrypted Fields"
Is displayed the label "Users/Groups to View"
Update label
https://processmaker.atlassian.net/browse/FOUR-19749

FOUR-19749 Missed label 'Users/Groups to View Encrypted Fields'

---

src/components/inspector/collection-data-source.vue
src/components/inspector/collection-designer-mode.vue
src/components/vue-form-builder.vue

- Column field is reset when Data selection options are changed
- Design option in Inspector shows the respective colors of the selected option in Table Style Dropdown
TEST 1
-Login PM4
- Go to Designer-> screens
- Create or use previous screens
- Drag Collection Record List and change name to "list"
- Select some Collection and create some Columns to display
- In configuration option, Select 'Single field of record' in Data Selection Dropdown
- Select some column in dropdown Column
- Select a Rich Text and wrap in mustache syntax {{list}}
- Click on preview, and select one row. The value of column selected should be displayed on rich text
- Now change Data Selection dropdown to "Single Record" option
- Change Rich Text mustache syntax to {{list.NameOfCollectionColumn}}
- Click on Preview …

Bugfix/FOUR-19847: `column` field is not reset when `single field of record` is changed by `single record`

---

src/components/task.vue
src/main.js
tests/components/TaskWebEntry.vue
tests/e2e/specs/EndEventRedirection.spec.js
tests/e2e/specs/InterstitialRedirect.spec.js
tests/e2e/specs/TaskRedirect.spec.js
tests/e2e/specs/WebEntryEndEventRedirect.spec.js
tests/e2e/support/commands.js

The message "This request is complete" should appear when completing the request
The user is redirected to summary
- add a isWebEntry property to identify if the task is running in web entry mode
https://github.com/user-attachments/assets/0ecc9e44-39ac-4d04-9bc9-be6d91511db8
- https://processmaker.atlassian.net/browse/FOUR-19011

FOUR-19011: Case completed message is not displayed

---

src/components/inspector/collection-records-list.vue

- The required tooltip was added to Collection name dropdown.
- Login PM4
- Go to Designer -> Screens
- Create or open a screen
- Drag Collection Record Control
- Click on Variable section in the inspector, and check the tooltip.
https://processmaker.atlassian.net/browse/FOUR-19681

bugfix/FOUR-19681: Add a message to indicates user that Collections won´t be available for Anonymous Web Entry

---

src/components/renderer/form-collection-record-control.vue

- Collection record Control was fixed when:
* Collection placeholder label restored
* Mode dropdown changes between View and Edit
- Login PM4
- Go to Designer->Screens
- Create Screen or select a previous one created
- Drag Collection Record Control
- Drag Input Field
- In collection control add Input Field variable name in mustache syntax into Record ID field
- Select Mode "View"
- Click on preview
- Insert a number in the Input Field Collection in View mode should be displayed
https://processmaker.atlassian.net/browse/FOUR-20057

bugfix/FOUR-20057: `Select a collection` label is missing when `Record ID` field has a variable

---

src/components/renderer/form-collection-record-control.vue

- Fix was implemented to use draft data only when record id of collection does not change
- Login PM
- Go to Designer->screens
- Create or select a screen
- Drag Collection Record Control and Input Field
- In Collection Record Control name Record ID with Input field variable name in mustache syntax (i.e {{record_id}})
- Choose Edit or View Mode
- Save Screen and assign it to a Process.
- Run a Case with last screen modified
- Enter different Record ID numbers in Input Field, each record Id must shown respective collection data
- Enter an specific Record ID, change some information in the screen and wait for autosave.
- Refresh page. Draft data must be recovered in the screen.
https://processmaker.atlassian.net/browse/FOUR-20097
.

Bugfix/FOUR-20097:`Record ID` field does not work to Collection Record Control

---

src/components/renderer/form-record-list.vue

- All settings for Collections in Recod List Control will cleaned when option "Variable" is selected.
- Login PM
- Create a Record list
select collection option in the Configuration > Source of Record List
Select a collection
Select any option in the Data Selection and select a column
- Press preview button (it works correctly)
- Press Design button
- Edit the Record list
select Variable option in the Configuration > Source of Record List
- Add custom header in the columns accordion
- Press Preview button
https://processmaker.atlassian.net/browse/FOUR-20076

Bugfix/FOUR-20076: Properties are not cleaned when `Source of Record List` field is changed from Collection to variable

---

src/components/renderer/form-list-table.vue
src/components/renderer/form-new-request.vue
src/components/renderer/form-requests.vue

**Steps to reproduced:**
- Select a language
- Log in with an admin user
- Go to the Home tab
- Go to the Admin tab and click Translations
- Go to the Designer tab
- Go to the Tasks tab
- Go to the Cases tab
- Go to the Processes tab
**Current Behavior:**
There are several untranslated fields.
- In Home--No Cases to Show, START NEW CASE
- In translations--Add language, Source String (English), botton translate with AI, the options select all fields, select empty - files, Default Anon language
- In designer--Name, Modified
- In tasks--Drafts, status
- In Cases--My cases, In progress, All cases, my requests, case, Case title, Process, task, participants, status, started completed, No new cases at this moment.
- In processes--Search Categories and processes
- Translate missing texts
Some …

Observation/FOUR-19978: Not all strings are added to the Json file for translation.

---

src/components/screen-renderer.vue
src/components/vue-form-renderer.vue

- Log in 
- Go to admin 
- Click on Log in Auth 
- Click on LDAP
Current Behavior:
When entering the LDAP configuration page, we get an error message in the console.
Added Optional Chaining operator to get the _parent from data.
https://processmaker.atlassian.net/browse/FOUR-20051
ci:release-2024-fall

FOUR-20051: Error in console when entering the LDAP configuration page

---

src/components/inspector/collection-records-list.vue

The open screen of the Collection Record control opens a different screen
When you click on open screen of the collection record control, it should open the screen that is in the collection
As we can see, when clicking on open screen of the collection record screen control, it opens a different screen than the one configured in the collection.
Added a method to obtain the screen id for editing collections
Log in 
Go to Designer
Click on Screens
Create a new form screen
Create a Collection Record Control 
Configure. with collection 
Click on Opone screen 
https://processmaker.atlassian.net/browse/FOUR-20173

observation/FOUR-20173 The open screen of the Collection Record control opens a different screen

---

src/components/editor/loop.vue
src/components/editor/multi-column.vue
src/components/vue-form-builder.vue

The Copy control Icon of controls actually is gray, it should be blue as figma design. 
The Copy control Icon of controls actually is gray
- Update the Copy button to use the primary button class instead of the secondary button class.
- https://processmaker.atlassian.net/browse/FOUR-20206

FOUR-20206: Update the Copy Control icon as figma

---

src/components/inspector/options-list.vue

This PR addresses an issue with the select list component in conversational screens when configured with a data connector, allowing multiple selections and using the object value type. 
Multiple options were selected but only commas were printed instead of the selected values.
---
**Steps to Reproduce:**
1. Log in.
2. Navigate to **Designer**.
3. Click on **Screens**.
4. Create a **Conversational Screen**.
5. Add a **Select List** component.
6. Configure the select list to use a **Data Connector**.
7. Enable the option **Allow Multiple Selection**.
8. Set the **Value Type** to **Object**.
9. Save the screen.
10. Click on **Preview**.
11. Select multiple options from the select list.
**Current Behavior:**
- When multiple options are selected, the output only displays commas, without the …

FOUR-20074: Fix Select List Display Issue for Multiple Selections with Data Connector

---

src/mixins/Clipboard.js
tests/e2e/specs/ClipboardTabClearAll.spec.js

The Clipboard should be cleared according to the PRD
The Clipboard isn’t cleared after adding some controls to the Clipboard page
- clipboard.items lost state reference after clear all, it was fixed
https://github.com/user-attachments/assets/53e26969-86f8-4084-8bbc-367bca39dcd8
the steps are detailed in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-19767
ci:deploy

FOUR-21132: Screen clipboard is not working

---

src/components/renderer/form-collection-record-control.vue

- In Screen Builder, when some screen has Collection Record Control, and user clicks over the control, its settings does not change
- Login PM4
- Go to Designer->Screens
- Create a  FORM type Screen
- Drag Input Field and rename as "list", drag also a Submit button.
- Drag Collection Record Control, select a collection and set {{list}} into Record Id field. Select EDIT mode.
- Save and Publish this new Screen and Assign to some simple Process start-task-end
- Run the process and fill the Form. Submit the process.
- Open the previous Screen in Screen Builder and click on Collection Record Control.
- Save and Publish.
- Run again the process and fill the form.
- When submit button is clicked, no errors should be displayed anda process should be completed normally. …

Bugfix/FOUR-21071: Collection Record Control changes saved settings when the control is clicked in Screen Builder

---

src/components/inspector/collection-select-list.vue
src/components/inspector/options-list.vue
tests/e2e/specs/FormSelectList.spec.js

**Steps to Reproduce:**
- Create a new screen
- Use the Select List component in the screen
- Configure the aria-label in Advanced property
**Current Behavior:**
The same aria-label is repeated for each option in the Select List. This is causing that the screen readers for disabilities reads the label question every time. This behavior is unexpected for the customer.
**Expected Behavior:**
ProcessMaker should allow configure the aria-label for each option in the aria-label property. One for the label and one for each option in the Select List component for the screen readers.
- Added area label option for checkbox renderAs mode, for provide data, request data, data connectors and collections.
- [FOUR-19875](https://processmaker.atlassian.net/browse/FOUR-19875)
- …

Task/FOUR-19875: aria-label property is the same in all options in the select list component generating unexpected behaviors for screen readers

---

.github/workflows/storybook.yml
src/components/vue-form-builder.vue

Navigation button shouldn't have the clipboard page as an option
Navigation button  have the clipboard page as an option
- remove extended config and add  the config to the clipboard so the clipboard was removed
datailed in the ticket
- https://processmaker.atlassian.net/browse/FOUR-21178
.

FOUR-21178 : Navigation button shouldn't have the clipboard page as an option

---

src/components/inspector/options-list.vue
src/form-builder-controls.js

1. Create a screen type form
2. Add select list 
3. Configure Show Control As Radio Check box
4. Add some provide values in the three fields (value, content and aria label)
5. Save the changes 
6. Refresh the page
7. Check the value set in aria label to options in select list
- https://processmaker.atlassian.net/browse/FOUR-21685
ci:deploy

FOUR-21685: The value set in the aria label field of the select list disappears after refreshing the page

---

src/components/inspector/options-list.vue
tests/e2e/specs/FormSelectList.spec.js

1. Create a screen 
2. Add select list 
3. Configure the select list with provide values
4. Set the select list with object type
5. Put some values in the provide values
6. Create a cal to set the select list
7. Click on preview
8. The select is working with calculate properties
9. Refresh the page
10. Click on preview button 
The values set bu calculated properties lost after refresh the page 
The values set bu calculated properties lost after refresh the page
- https://processmaker.atlassian.net/browse/FOUR-21691

FOUR-21691:The values set by calcs in a select list(drop-down) lost after refresh the page

---

src/components/inspector/collection-data-source.vue
src/components/inspector/column-setup.vue

1. Create a screen form 
2. Add record list 
3. Configure the select list with Collection 
4. Add Columns in the record list
5. Publish the changes 
6. Refresh the page 
7. Select the record list
8. Go to column
9. Add a new column 
10. Search for the options in the select list 
The select list disappears after refresh the page Instead it only shows a line input 
The select list with options to record list should remain after the refresh the page 
- https://processmaker.atlassian.net/browse/FOUR-21710

FOUR-21710:The options in the select list disappears to record list with collection configured

---

src/components/vue-form-builder.vue
src/main.js

- On the screen click on the flag and change the language e.g. Spanish
- Add a line input/Select list/ etc
**Actual Behavior:**
The default variables of the components are not displayed.
**Current behavior:** 
As in previous versions, this change of language should not affect the assignment of the default variable of the components of a screen.
- When adding a new control to a screen, now the inspector configuration uses an object without translated attributes
- https://processmaker.atlassian.net/browse/FOUR-22021
ci:release-2025-winter

FOUR-22021: Default variables are not displayed on a screen when using a language other than English

---

src/App.vue
src/components/vue-form-builder.vue

1. Log-in
2. Go to translations and create a non major language like Afrikaans, Gallician, Catalan
3. Generate all the translations of the plataform for the language of step 2.
4. Select as the System language the language selected in step2.
5. Create a PMBlock
The PMBlock configuation tabs are note displayed
A user should be able to create a PM Block with any language
- https://processmaker.atlassian.net/browse/FOUR-21898
The problem was caused by the limited set of translations that the library validator.js supports. We added code to use english as a fallback language.
ci:processmaker:bugfix/FOUR-21898
ci:package-pm-blocks:bugfix/FOUR-21898
ci:vue-form-elements:bugfix/FOUR-21898

Cannot create a pmblock with the language translation Português and Na Vosa Vakaviti (Fijian)

---

src/components/inspector/options-list.vue

Extra information is added to the options information, making the value selection incorrect.
the aria-label field should not be added to the options
Extra information should not be added to the options
- Modify options aria-label
Check options with Dropdown/radio button/checkbox
- [FOUR-21869](https://processmaker.atlassian.net/browse/FOUR-21869)
ci:vue-form-elements:bugfix/FOUR-21869
ci:deploy
[FOUR-21869]: https://processmaker.atlassian.net/browse/FOUR-21869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Aria label field disappears of the Radio check box as field

---

src/components/inspector/collection-display-mode.vue
src/components/inspector/collection-records-list.vue

Collection Record control settings are copied when a selection is inserted
The options should not be copied in the collection record control, Each one should remain its own configuration like in 4.12.2
The options like “Mode: Edit“ are copied in the second collection record when this is selected
Update the collection mode and the collection submit for each collection
See the ticket
[FOUR-22168](https://processmaker.atlassian.net/browse/FOUR-22168)
[FOUR-22168]: https://processmaker.atlassian.net/browse/FOUR-22168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-22168 collection record control settings are copied when selection is inserted

---

src/components/renderer/form-collection-record-control.vue

Collection Record ID is not visible in preview screen
Collection Record ID should be visible in preview
Collection Record ID is not visible in preview
- Add a default collection mode
See the ticket
[FOUR-22166](https://processmaker.atlassian.net/browse/FOUR-22166)
[FOUR-22166]: https://processmaker.atlassian.net/browse/FOUR-22166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FOUR-22166 Collection Record ID is not visible in preview screen

---

src/components/task.vue

- If we have two tasks and each one has a different type of screen, the screens should not change type in execution mode.
- The conversational screen that is in the first task is completed and the controls of the next form screen are being displayed as if they were part of the conversational screen.
- The issue was caused by the logic flow in handleRedirectToTask(), where loadTask() was being used instead of a hard redirect.
- The fix was to force a navigation to the correct task screen using window.location.href
- Follow the reproduction steps from the JIRA ticket.
- [FOUR-21660](https://processmaker.atlassian.net/browse/FOUR-21660)
[FOUR-21660]: https://processmaker.atlassian.net/browse/FOUR-21660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

FOUR-21660: The form screen is shown as conversational when we start a new case

---

src/components/inspector/options-list.vue

Steps to Reproduce
Create Screen form 
Add select list
Configure the select list with data connector 
Enable Radio check box in select list
Change the select list to Collection 
Select one collection
Check the fields 
Fields in a Select list type collection should not be corrupted after changing its Data source
Aria label appears as new field in collection after change the select list of Data connector to Collections as select list as wrong values
Reset the renderAs value when collection is selected

bugfix/FOUR-22187 Fields in a Select list type collection are corrupted after changing its Data source

---

src/components/inspector/collection-select-list.vue
src/components/inspector/options-list.vue

1.Create a rag collection
2.Create some records.
3.Create a screen
4.Add a select list
5 data source add the rag collection
6.Complete the settings
RAG collections should not be displayed for the select list control.
It only displays the record ID option and the record ID and New input values.
Added a filter to the select collection component in the screen builder
https://processmaker.atlassian.net/browse/FOUR-22498

observation/FOUR-22498 The select list control displays Rag Collections

---

src/components/inspector/collection-records-list.vue

- RAG collection are not displayed in the Collection Record Control as they have a different flow and it is not its intended use.
https://processmaker.atlassian.net/browse/FOUR-22483
https://processmaker.atlassian.net/browse/FOUR-22484

FOUR-22483: "Open Edit Screen" shows an Oops! screen

---

src/components/vue-form-builder.vue
tests/e2e/specs/ClipboardTabDuplicate.spec.js

The element clicked should be duplicated within the Clipboard page
The element is NOT duplicated and there is an error displayed in the console
- update duplicateItem method to allow duplicate in the clipboard page
https://github.com/user-attachments/assets/f34ebc2a-c773-4b89-94c4-65a46336fc19
Steps are detailed in the related ticket
- https://processmaker.atlassian.net/browse/FOUR-22882

FOUR-22882: Duplicate controls in the Clipboard page doesn't work

---

src/components/inspector/options-list.vue

1. Create a screen form 
2. Add select list
3. Set some values provide  values
4. Change the select list of Drop-down → Radio Check box 
5. Configure one record in the select list (Arial label), put some value
6. Check the other values aria label in the rest of the records of the select list 
The Aria label filed is repeated in all the records in the select list, when one is set 
The Aria label should be individual in each of the records in the select list of Radio check box type
- https://processmaker.atlassian.net/browse/FOUR-22766

FOUR-22766: Aria label is duplicated in the rest of the records in the select list when one record is set >> Select list Radio check box

---

src/components/task.vue
tests/e2e/specs/Task.spec.js

Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).
added an new param for redirectListener with active tokes to validate the redirection
Steps to Reproduce: 
import the attached process
Assign the users per each task
create a new case for the new process
run the case in parallel thread in the same time (with different users and browsers)
submit the first task
h5. Current Behavior: 
We have two scenarios: 
The task is set to "Task Source (Default)" in the Task Destination. Submitting one thread reloads the other and redirects to the request page (see the attached video on the parallel problem).
The task is set to "Show Next Assigned Task" in the Task Destination. Submitting one thread reloads the other and …

bugfix/FOUR-23723 added an new param for redirectListener

---

src/components/index.js
src/components/renderer/case-progress-bar.vue
src/components/renderer/index.js
src/form-builder-controls.js
tests/e2e/specs/FOUR6788_ScreenPerformanceTests.spec.js

- https://processmaker.atlassian.net/browse/FOUR-24227

FOUR-24227:Add in the display screen a New control - Case Progress Bar

---

src/components/task.vue

Create a simple process (start event - script task/data connector - task - end event) Run a Case
When a script task or data connector has an error, the error screen is not displayed. An error screen is displayed in PM 4.12.0
The error screen should be displayed when a error occurs in a data connector or script and the error should be displayed in the Request
https://processmaker.atlassian.net/browse/FOUR-24945

FOUR-24945 Error screen is not displayed
