- src/components/renderer/form-multi-column.vue
- src/components/vue-form-renderer.vue
Bugfix https://github.com/ProcessMaker/vue-form-builder/issues/25
- Add item in v-model
- add data for preview fill.
> Items in Columns Broken

- src/components/renderer/form-multi-column.vue
- src/components/vue-form-renderer.vue
Add validation "isValid" for form
> Validation Missing

- src/components/renderer/form-button.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
- Add change value in button submit
- value in event click
> add name and value to submit button

- src/App.vue
- src/components/editor/multi-column.vue
- src/components/renderer/form-button.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
Related to #34 
The following default values are sent if the controls are not activated or changed:
- Line input = empty string
- Select = null
- Radio group = null
- Checkbox = false
- Textarea = empty string
- Date picker = null
- Record List = empty array
> Send default values when submit a form. #34

- src/components/vue-form-renderer.vue
> Quick bugfix

- src/components/computed-properties.vue
fixes https://github.com/ProcessMaker/bpm/issues/1316
closes #43
> change label to description

- package-lock.json
- package.json
- src/components/editor/multi-column.vue
- src/components/index.js
- src/components/inspector/image-upload.vue
- src/components/renderer/form-image.vue
- src/components/renderer/form-multi-column.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- tests/unit/FormImage.spec.js
- Add to sidebar a button for Image Component
- Image inspector include: Upload Button, Image Preview, Size (height / width) and id.
- Store the image data as base64 encoded in the JSON object
- Update preview to display image
- Update the live screen display
- Add unit test for the component (`npm test`)
Related to: #45 
In BPM project: https://github.com/ProcessMaker/bpm/issues/1312
> Implements a Image component

- package-lock.json
- package.json
- src/App.vue
- src/components/custom-css.vue
- src/components/vue-form-renderer.vue
- tests/unit/CustomCss.spec.js
Fixes #46 
- Add a custom css property to the form renderer
- Add a configuration modal for the CSS
- Refresh the CSS in preview and live form
- Add unit tests for this feature
> Implements the Custom CSS

- package-lock.json
- package.json
- src/components/computed-properties.vue
- vue.config.js
- Use monaco to edit the formula in the computed property
- Add a button to enable/disable the edition mode (simple/parser)
- If the expression is complex (larger than 64 characters or multiple lines) use the expression parser mode
Implements: #30 
Related to: https://github.com/ProcessMaker/bpm/issues/1315
> Implement javascript parser in formula box.

- src/components/vue-form-builder.vue
Fixes #56 
- Add style for scroll in inspector.
> Inspector Scrolling #56

- src/components/editor/multi-column.vue
- src/components/inspector/container-columns.vue
- src/components/renderer/form-multi-column.vue
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
Fixes #60 
- Enable component multi Column with more of 2 columns.
- add inspector for component.
- component must have at least one column
> Multicolumn - Allow Config of Number Cols (2-12)

- package-lock.json
- package.json
- src/components/inspector/form-multiselect.vue
- src/components/inspector/page-select.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
all inspector selects are now converted to the multi-select library
> Multi-select 

- package.json
- src/components/custom-css.vue
- vue.config.js
bring in monaco editor for custom css
> monaco editor for custom css

- src/components/editor/multi-column.vue
- src/components/inspector/container-columns.vue
- src/components/renderer/form-multi-column.vue
> Fix warnings in form builder - Record List

- src/components/renderer/form-text.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
ability to use name or custom id for styling
> wrapper id for css

- src/components/editor/multi-column.vue
- src/components/inspector/container-columns.vue
- src/components/renderer/form-multi-column.vue
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
Multi columns now has the ability to have custom columns
> multi-colum has config for columns

- package-lock.json
- package.json
- src/components/inspector/form-multiselect.vue
- src/components/inspector/page-select.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
all selects in the inspector have now been replaced with vue-multiselect library
> MultiSelect to replace selects

- src/components/vue-form-builder.vue
> margin added to the bottom of the inspector

- src/components/inspector/page-select.vue
> Fix page selection (Record List and Page Navigation)

- src/components/vue-form-builder.vue
ADDED border line to the inspector
> add border line in control list

- src/components/inspector/image-upload.vue
- src/form-builder-controls.js
- Add a name property to Image Control
> Add name to image control.

- src/App.vue
- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
Fixes #79 
- Add scroll panels
> Scrolling Screwed Up

- src/components/computed-properties.vue
- src/components/inspector/form-multiselect.vue
- src/components/vue-form-renderer.vue
all references to this hack have been refactored. 
closes #100
> refactor to remove that = this

- src/global-properties.js
> Update text on conditional hide inspector

- package.json
- vue.config.js
Reverts ProcessMaker/vue-form-builder#103
> Revert "Make bootstrap an external/peer dependency"

- src/components/editor/multi-column.vue
- src/components/renderer/form-multi-column.vue
Fixes #111 
Add validation to add multicolumn inside multicolumn.
solve https://github.com/ProcessMaker/vue-form-elements/issues/28
> Error adding a multicolumn inside multicolumn

- src/components/computed-properties.vue
- src/components/vue-form-builder.vue
Resolves #116 
- Add confirm modal when you want to delete a page.
> Multi-Page Screen Deletion

- src/components/renderer/form-multi-column.vue
- src/components/renderer/form-text.vue
- src/form-builder-controls.js
Resolves #107 
Vertical alignment property for the the TextBox control has been added. Additionally the Multicolumn was modified to support this alignment.
Example of aligning to bottom:
> Text Align Middle

- src/components/vue-form-builder.vue
- src/form-builder-controls.js
Fixes #108  
This PR includes a inspector of validations issues:
> Add error validations inspector

- package-lock.json
- package.json
- src/form-builder-controls.js
resolves #122 
- Add properties toggle in build controls
> Update form-elements and enable toggle bootstrap style

- src/components/inspector/container-columns.vue
- src/components/renderer/form-record-list.vue
resolves #119 
- add validation in load configuration in component Record list.
> Complex Forms Fail

- src/components/inspector/options-list.vue
- src/components/renderer/form-record-list.vue
- src/form-builder-controls.js
> grammer changes

- .eslintrc.js
- jest.config.js
- package-lock.json
- package.json
- src/App.vue
- src/components/computed-properties.vue
- src/components/editor/multi-column.vue
- src/components/inspector/container-columns.vue
- src/components/inspector/options-list.vue
- src/components/renderer/form-multi-column.vue
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
- tests/unit/.eslintrc.js
- tests/unit/VueFormBuilder.spec.js
- vue.config.js
Fixes #125.
**Important changes:**
* `eslint-plugin-jest` has been added; run `npm ci` or `npm i` before testing.
* New test added; all tests should pass when running `npm test`.
> Add  rich text (wysiwyg) editor

- src/components/inspector/color-select.vue
> fix color pickers being muted

- src/components/vue-form-builder.vue
closes #142 
and reference to: https://github.com/ProcessMaker/spark/issues/1647
> fix non standard modals

- package-lock.json
- package.json
- src/App.vue
- src/components/inspector/color-select.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- Elements are wrapped in a bootstrap `card` class
- `card-header`, `card-body`, `card-footer`  supporting classes are used when possible
**Builder**
**Preview**
Fixes #133, #149
> Redesign Builder

- src/components/inspector/image-upload.vue
Resolves #144 
escape name of the image when it is uploaded in the image component.
> The Image component cannot be hidden

- src/components/renderer/form-record-list.vue
Fixes #160 
Need to check that the user has selected a page to use for add/edit first
> Check that the user selected a page before getting the config

- src/components/inspector/color-select.vue
- src/components/vue-form-builder.vue
> Missing labels

- src/components/renderer/form-button.vue
Do Not Merge Until #162 is merged first 
How to test
- npm run serve
- drag submit button on rendered
Expected
- No console errors
Fixes #175
> Bugfix: button on v-model

- src/components/inspector/options-list.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
Fixes #156, fixes #190.
Screenshots of fix:
> Rename “Field Name” to “Variable Name”

- src/components/vue-form-builder.vue
Fixes #189.
**How to test:**
Follow the steps in the issue report at https://github.com/ProcessMaker/spark-screen-builder/issues/189#issuecomment-494410212, and ensure you cannot reproduce the bug; you should be able to delete any screens you add.
**Related spark PR:**
https://github.com/ProcessMaker/spark/pull/1867
> Fix screen delete bug

- src/components/vue-form-builder.vue
- Inspector configurations will now clear when deleting form-elements
- Removed shadow on button accordion
**Stand-alone**
https://drive.google.com/open?id=1DEFtqdTsmcHq5HExwZRReFxdX4NLCeUw
**Spark Builder**
https://drive.google.com/open?id=1No1SwMpcyg28gY6GzeaASRW6mJhl5adc
Tables (Multi-column) cannot be deleted until PR https://github.com/ProcessMaker/spark-screen-builder/pull/196 is merged
Fixes #201
> Config not clearing when deleteing form element

- package-lock.json
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
Fixes #192, fixes #193, fixes #194, fixes #204, fiex #206.
~~This PR requires updates to `vue-form-elements`; the PR for which is at https://github.com/ProcessMaker/vue-form-elements/pull/40.~~ **merged**
> Update default values

- src/components/vue-form-builder.vue
Fixes #208.
Video of fix:
https://www.dropbox.com/s/dm0qigouzt4ava4/mask_working.mov?dl=0
> Fix mask for unselected elements

- src/App.vue
> Missing Translations

- src/components/renderer/form-multi-column.vue
- src/components/vue-form-renderer.vue
- src/mixins/index.js
- src/mixins/shouldElementBeVisible.js
Fixes #218, fixes #234.
Video of fixes:
* https://www.dropbox.com/s/lgvuxbe8l1mosx5/visibility_working_elements.mov?dl=0
* https://www.dropbox.com/s/9esm104audqtrbz/visibility_working_table.mov?dl=0
When testing, also check rendering with the spark file linked in the related issue: https://github.com/ProcessMaker/spark-screen-builder/issues/234.
> Fix element visibility rendering

- src/form-builder-controls.js
- Fixed error messages that rendered `The undefined field is required`
- Change helper texts that reference `data`
**Spark video demo**
https://drive.google.com/open?id=1y3ZYWu_C-5VJDe7HxVCSYgAGHBl7RYds
Fixes #186
> Fix undefined error message

- src/components/vue-form-builder.vue
- src/form-builder-controls.js
https://drive.google.com/open?id=1pNJPJ_0E00XBat3HLRgZb7z-c9anFBiy
Fixes #158
> Input type icons

- src/form-builder-controls.js
https://drive.google.com/open?id=1YnyNL8KjiExUwzr8djTT5e2TY5bXJha0
Fixes #238
> Add select default value of null

- src/components/vue-form-builder.vue
https://drive.google.com/open?id=1Oxl45COxLT2h--hCeY-x-7EXii09uPTT
Fixes #170
> Add drag here placeholder

- src/form-builder-controls.js
PR from vue-form-elements repo will have to be merged for the fix in spark app.
https://github.com/ProcessMaker/vue-form-elements/pull/46
https://drive.google.com/open?id=1GttGIzOjQm_7Ki-pdrs3lR30mfe4p-CY
Fixes #148
> Add placeholder for datepicker

- src/components/editor/multi-column.vue
- src/components/renderer/form-multi-column.vue
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- src/mixins/getValidPath.js
- src/mixins/index.js
Fixes #252 and #254 for when the elements are inside of tables.
> Fix variable validation and mask element in tables

- src/components/renderer/form-multi-column.vue
Fixes #271.
Video of fix (tested on branch `feature/2025` in `processmaker`):
https://www.dropbox.com/s/mlt1w7ol5szslxc/rich_text_working.mov?dl=0.
> Prevent editing rich text in renderer

- src/components/renderer/form-record-list.vue
- src/components/renderer/index.js
Resolves #273 
This PR removes a redundant dependency between VueFormRenderer and FormRecordList
> Fix redundant dependency

- src/App.vue
- src/components/vue-form-builder.vue
Fixes #269.
Screenshots of fix:
Associated PR on `processmaker`: https://github.com/ProcessMaker/processmaker/pull/2049
> Make columns flush with edges

- src/components/inspector/page-select.vue
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
Fixes #245.
Video of fix: https://www.dropbox.com/s/i1wnwcz4hdyvdrf/page_nav_fixed.mov?dl=0.
> Refactor page nav to filter out current page

- src/App.vue
- src/components/vue-form-builder.vue
**Style Tweaks**
- Removed horizontal scroll bar
- Docked validation drawer
- Remove any double borders
- Change side bar font size to 14px
Fixes #282
> Style tweaks

- src/components/renderer/form-multi-column.vue
Fixes #286.
Video of fix: https://www.dropbox.com/s/jvd9ov4xq45b4ur/textAlign_working.mov?dl=0.
> Fix text align not working correctly inside of table

- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
- vue.config.js
Fixes #139.
This PR re-implements undo/redo as described in the original PR https://github.com/ProcessMaker/screen-builder/pull/146.
Video of fix: https://www.dropbox.com/s/8gyzud247aqesso/undo_redo_working.mov?dl=0.
> Re-add undo/redo functionality

- src/components/editor/multi-column.vue
https://drive.google.com/open?id=1x1uCfJInqhSnJu8JqeLO4I9L_T1VHNnA
Fixes #289
> Focus state for elements inside a table

- src/form-builder-controls.js
Fixes #278 
Related PRs
- https://github.com/ProcessMaker/processmaker/pull/2118
- https://github.com/ProcessMaker/vue-form-elements/pull/55
>  Add toggle to form text area inspector

- src/components/vue-form-builder.vue
Fixes #306.
Video of fix: https://www.dropbox.com/s/zggcr797ee399kq/no_content_hidden.mov?dl=0.
This PR requires the changes in `processmaker` to also be merged: https://github.com/ProcessMaker/processmaker/pull/2202.
> Fix controls overflow

- src/form-builder-controls.js
Fixes #310.
Video of fix: https://www.dropbox.com/s/fd8fhxned43uox7/time_picker_working.mov?dl=0.
> Change date picker type to datetime

- src/App.vue
- src/components/renderer/index.js
- src/components/vue-form-builder.vue
Fixes #308.
Related issue: https://github.com/ProcessMaker/screen-builder/issues/308.
This PR also requires https://github.com/ProcessMaker/vue-form-elements/pull/59 to be merged
> Fix SSR for connector-send-email

- src/components/accordions.js
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- src/form-control-common-properties.js
Fixes #300.
This PR requires the changes in https://github.com/ProcessMaker/processmaker/pull/2254 to be complete.
Video of updated controls: https://www.dropbox.com/s/umcvh1tmngir9rw/300-config-updates.mov?dl=0.
The PR addresses some of the updates that were missed in the previous PR: https://github.com/ProcessMaker/screen-builder/pull/311.
> Update inspector to match spec

- src/VariableDataTypeProperties.js
- src/components/inspector/form-multiselect.vue
Fixes #323.
Video of fix: https://www.dropbox.com/s/7zigvmw95xul70m/data-type-working.mov?dl=0.
> Fix data type select

- src/components/editor/multi-column.vue
Selected state for elements inside multi-column are consistent with the other states.    
https://drive.google.com/open?id=1DyhdKg3_QXhQAREtvnjkEvTT1zfRklix
Fixes #327
> Change frame styling in tables

- src/components/computed-properties.vue
> Fix calculated props footer

- src/components/vue-form-builder.vue
Fixes #336.
Video of fix: https://www.dropbox.com/s/ed7p5t0hvs6fx48/extra-scrollbar-fixed.mov?dl=0
> Prevent container scrollbar from appearing on overflow

- src/components/vue-form-builder.vue
- src/global-properties.js
**Type Form**
**Type Display**
PR in processmaker repo is required to be merge.
https://github.com/ProcessMaker/processmaker/pull/2275
Fixes #344
> Hide toolbar in typeDisplay

- src/App.vue
- src/components/computed-properties.vue
- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
Fixes #302, fixes #305.
**Note:** This PR requires the changes in https://github.com/ProcessMaker/processmaker/pull/2269 to be merged as well.
Video of fix: https://www.dropbox.com/s/eccgo5zotgl2dy2/nested-validation-working.mov?dl=0
> Validate container components with nested form items

- src/components/computed-properties.vue
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- vue.config.js
> Validate page names are required and unique

- src/components/computed-properties.vue
- vue.config.js
Resolves #345 
- Fix style computed property modal
require ProcessMaker/vue-form-elements#64
> Computed Property Modal

- package-lock.json
- package.json
This change is needed to make sure problems introduced in the modeler project are resolved.
> Updated vue-form-elements to latest version.

- src/components/vue-form-builder.vue
- src/form-builder-controls.js
Fix submit - page navigation conflict
> Fix submit - page navigation conflict

- package-lock.json
- src/components/vue-form-builder.vue
Fixes #375. This PR adds null checking for the result of an Array.prototype.find() operation, which is not guaranteed to return a result.
> Added null checking to avoid error when adding a new page.

- src/components/vue-form-renderer.vue
> Remove padding

- src/components/vue-form-builder.vue
Run migration onload an old config
> Run migration onload an old config

- src/components/renderer/form-record-list.vue
- src/components/vue-form-builder.vue
Resolves #403 
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/99
> Fix unresponsive screens

- src/components/accordions.js
- src/components/inspector/column-setup.vue
- src/components/inspector/index.js
- src/components/renderer/form-record-list-static.vue
- src/components/renderer/form-record-list.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- src/mixins/mustacheEvaluation.js
> Record List Improvements

- package.json
- src/components/accordions.js
- src/components/inspector/column-setup.vue
- src/components/inspector/index.js
- src/components/renderer/form-record-list-static.vue
- src/components/renderer/form-record-list.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- src/mixins/mustacheEvaluation.js
Fixes #401 
Needs https://github.com/ProcessMaker/processmaker/pull/2420
This is branched off feature/399 so make sure its merged first
> Fix file uploads in record lists

- src/components/inspector/column-setup.vue
- src/components/inspector/options-list.vue
Changes:
1. Added Moncao JSON editor to the new accordion `column` for `Record Lists`
> Add moncao editor to records list 'column' accordion

- src/components/vue-form-renderer.vue
closes #351 
**Issue:**
Data preview does not display variables with the value of null.
**Fix:**
This PR runs the 'setDefaultValues' method to display the variable's default value in the data preview.
> Set default values for variables

- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- src/form-control-common-properties.js
resolves #412 
- Change key name to Variable name
> Change Key Name

- src/components/renderer/form-multi-column.vue
Resolves #415 
- enable config disable in multi column
> Read-Only Toggle Broken 

- src/components/vue-form-builder.vue
Resolves #430 
- Fix migrate form submit and page navigation
> Editing Navigation Buttons

- src/components/vue-form-renderer.vue
Core issue https://github.com/ProcessMaker/processmaker/issues/2547
Fixes #444
> Run the computed props when the page loads

- src/components/inspector/options-list.vue
- src/form-builder-controls.js
- src/main.js
Resolves #442 
- Needs the Data Sources package
- Adds the option to configure a data source as a source of options for a Select List. 
- Needs this PR from vue-form-elements
processmaker: https://github.com/ProcessMaker/processmaker/pull/2579
vue-form-elements: https://github.com/ProcessMaker/vue-form-elements/pull/122
> Enable dataObject functionality in the SelectList control

- package-lock.json
- package.json
- Bumps vue-form-elements to v0.12.4
Closes #453.
> Bumping vue-form-elements to v0.12.4

- src/components/watchers-form.vue
- src/mixins/formWatchers.js
Closes #456 
- validation of which panel is active.
- validation json
- in processmaker create screen, config watcher then save and reload information.
> Watcher Script Config Not Saving

- src/mixins/formWatchers.js
closes #461 
Add validation in the Check Watcher function, the array is ​​the same
> Watcher continually updating

- src/components/vue-form-renderer.vue
- src/mixins/formWatchers.js
closes #463 
verify changes in the data for the watchers call
> Watchers Running without Variable Interaction

- package-lock.json
- package.json
- Updates vue-form-elements to v0.12.5
Closes #466.
> Update vue-form-elements to v0.12.5

- package-lock.json
- package.json
- vue-form-elements to v0.12.6
Closes #469.
> Updating vue-form-elements to v0.12.6

- jest.config.js
- package-lock.json
- package.json
- src/components/computed-properties.vue
- src/components/inspector/options-list.vue
- src/components/watchers-synchronous.vue
- src/itemProcessingUtils.js
- src/mixins/formWatchers.js
- tests/unit/ConditionalHide.spec.js
- tests/unit/CustomCss.spec.js
This PR fixes a handful of lint errors and fixes the broken unit tests.
Note: There are still two lint errors that I did not resolve as they could cause breaking changes:
```
Expected a 'break' statement before 'case' (no-fallthrough) at src/components/inspector/options-list.vue:299:9
Unexpected side effect in "dataObjectOptions" computed property (vue/no-side-effects-in-computed-properties) at src/components/inspector/options-list.vue:344:9
```
> Fix tests refactor

- src/components/renderer/form-masked-input.vue
Resolves #473 
Fix model binding for non masked inputs.
> Fix v-model binding for non masked input

- package-lock.json
- src/components/renderer/form-multi-column.vue
Fixes #475 
Fixes https://github.com/ProcessMaker/processmaker/issues/2685
Specify the masked input in multicolumn component
> Add masked input to multicolumn

- package-lock.json
- package.json
- vue-form-elements to v0.12.7
Closes #479.
> Bumping vue-form-elements to v0.12.7

- package-lock.json
- src/components/renderer/form-masked-input.vue
- src/form-builder-controls.js
Fixes #437 
Limit to 15 characters for float and int so the numbers aren't too be for those variable types
> Set maximum length for int and float types

- package-lock.json
- package.json
- vue-form-elements to v0.12.8
Closes #484.
> Bump vue-form-elements to v0.12.8

- src/components/vue-form-builder.vue
Resolves: #492 
- Fix dot notation validation in old screens saved with old validation configuration.
> Fix validation of dot notation in variable name

- src/components/inspector/column-setup.vue
- src/components/inspector/options-list.vue
Related https://github.com/ProcessMaker/processmaker/pull/2702
> Use similar translation for CLOSE and css to style

- src/components/renderer/form-masked-input.vue
> Fix date formatting

- package-lock.json
- package.json
- src/itemProcessingUtils.js
This PR, along with https://github.com/ProcessMaker/vue-form-elements/pull/153, fixes https://github.com/ProcessMaker/screen-builder/issues/498.
This PR ensures that the default value for the datepicker is set using the user's timezone, and sets it to the start of the day if the "date" data type for the control is selected.
> Use timezone for setting default date value

- package-lock.json
- package.json
- vue-form-elements to v0.13.1
Closes #503.
> Update vue-form-elements to v0.13.1

- src/components/renderer/form-masked-input.vue
> Add missing datetime format

- src/components/watchers-synchronous.vue
- src/mixins/formWatchers.js
Resolves #514 
- Fix watchers execution
- Add queue to execute watchers in debounce() function
- Add error message to watcher popup
> Fix watchers execution

- package-lock.json
- src/components/VariableNameGenerator.js
- src/components/vue-form-builder.vue
closes #509 
- Add default name generated with field 'editor-control'
> Default Variable Name

- src/App.vue
- src/components/accordions.js
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
- src/form-control-common-properties.js
> Add configurable default values

- src/components/vue-form-renderer.vue
Fixes #522 
Fixes https://github.com/ProcessMaker/processmaker/issues/2789
Allows for components to stay active when switching pages. Fixes the file upload component
> Wrap component in keep-alive tag to prevent destroying on page nav

- src/components/accordions.js
- src/form-builder-controls.js
> Move label inspector field to variable accordion

- src/components/renderer/form-button.vue
- Prevents the navigation button data from displaying in the data preview when clicked.
- Create a Form-type screen with at least 2 pages
- Add a Page Navigation button to one of the pages
- Preview the page and press the nav button
- Navigate to the selected page
- Data does not display in the Data Preview.
https://www.dropbox.com/s/uptlr0jgv4x3uq1/Edit%20Screen%20-%20ProcessMaker%20%281%29.mp4?dl=0
closes #526
> Fix Navigation Button Submitting Forms

- src/components/inspector/options-list.vue
- src/components/watchers-form.vue
Updates configurations for the Data Connector in the inspector that was labeled as Data Sources to Data Connector.
closes [processmaker/#2820](https://github.com/ProcessMaker/processmaker/issues/2820)
> update the data connector config labels

- src/components/watchers-form.vue
- Removes an errant console.log message left in the Watcher component
Closes #541.
> Remove errant console.log

- src/components/renderer/form-nested-screen.vue
Resolves #545  
Resolves https://github.com/ProcessMaker/processmaker/issues/2874
- Load local data when component is mounted (used for nested screens with an owner variable)
> Load local data when mounted

- src/components/renderer/form-button.vue
- src/components/vue-form-renderer.vue
- src/form-builder-controls.js
- src/form-control-common-properties.js
- src/itemProcessingUtils.js
closes #543, 
Resolves https://github.com/ProcessMaker/processmaker/issues/2808
- Add dropdown for button, types submit, script, default submit.
- add default value in button type script.
- button type script need config watcher
- value button type script is only a counter, to verify the data transition.
> Enhance Button with Toggle Value Functionality (option for submit / do nothing) 

- src/components/computed-properties.vue
- src/components/watchers-form.vue
Adds asterisks to required UI fields. Watchers &  Calc Properties modals
ref [processmaker/#2879](https://github.com/ProcessMaker/processmaker/issues/2879)
> Add asterisks to required UI fields

- src/components/renderer/form-record-list.vue
> Update warning modal copy

- package-lock.json
- package.json
- src/components/vue-form-renderer.vue
Fixes #571 
Scrolling happens in containers that are outside vue-form-renderer. Instead of updating everything that uses vue-form-renderer (lots) I found a small script that finds the nearest parent element that can be scrolled and scroll it to the top, all from within vue-form-renderer.
Uses this script https://github.com/olahol/scrollparent.js
> Scroll to the top when navigating pages

- src/components/vue-form-renderer.vue
- Prevent the submit button from validating pages associated with RecordLists
<a href="https://www.loom.com/share/ab90b3fdbcd04658830136ed0cfdff31"> <p>25 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/ab90b3fdbcd04658830136ed0cfdff31-with-play.gif"> </a>
- Prevent empty data from displaying in the Data Preview when pages are associated with RecordLists
<h4>Before</h4>
<h3>After</h3>
- Create an editable Record List and associate a page/form that has a required field. 
- Run a process an add a new record
- Submit the form
The form is submitted and the task is successfully completed.
closes #576
> Fix Submit button Validation On Record List Form 

- src/components/renderer/form-record-list.vue
Reinitialize the Vuetable when fields are updated.
<a href="https://www.loom.com/share/16fa8040ebe445f9b6b704f1413b55ad"> <p>25 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/16fa8040ebe445f9b6b704f1413b55ad-with-play.gif"> </a>
- Import the below process
[Record List Test.json.txt](https://github.com/ProcessMaker/screen-builder/files/4252685/Record.List.Test.json.txt)
- Run the process and add a new record.
- Navigate to the 'contact directory' page and a new record
- Switch between the 'Business & Contact Directories'
Table data & headers update correctly
closes #549
> Fix RecordList Headers

- src/mixins/formWatchers.js
closes #553 
- Validate if exists config watchers
- Create form with multi-screen forms
- execute watcher
> Watchers Broken on Multi-Screen Forms

- src/components/computed-properties.vue
This fixes #594.
Goes hand in hand with PR https://github.com/ProcessMaker/processmaker/pull/2904
> Change copy of "computed properties" to "calculated properties"

- src/components/renderer/form-nested-screen.vue
closes #559 
- Hide submit buttons on nested screen.
> Nested submit button does nothing

- src/components/renderer/form-nested-screen.vue
Resolves #563 
- Add magic variables to nested screens
> Add magic variables to nested screen

- src/mixins/multiselectApi.js
Resolves #560 
- Add debounce to delay the search of screens when typing in the screen list control
> Add debounce to screen listing

- src/components/inspector/screen-selector.vue
Fixes #606 
Uses PMQL to limit available screens to type DISPLAY and type FORM
> Only allow form and display screens for nested screens

- src/components/editor/loop.vue
- src/components/editor/multi-column.vue
- src/components/inspector/column-setup.vue
- src/components/inspector/container-columns.vue
- src/components/inspector/options-list.vue
- src/components/vue-form-builder.vue
closes #558 
- Component Draggable "props" deprecated, migrate to v-bind
> Options props is deprecated

- src/components/renderer/form-record-list.vue
closes #552 
- Clear variable addItem before opern modal and save data in record List
- create screen with recordlist
- add data in the form, the fields must always be empty when adding new data
> Record List Modal Not Clearing

- src/components/renderer/form-record-list.vue
Resolves #548 
- Files are downloaded if the displayed column in the RecordList is associated with an uploaded file.
- To test use a RecordList that isn't embedded within a MultiColum control because there is a separate issue when using RecordLists and MultiColumns.
> Record List File Uploads cannot be downloaded

- src/components/Pagination.vue
- src/components/renderer/form-record-list.vue
closes #602 
- Add Paginate in Record List Control
- create screen
- create record list
- Add data to the list of records of more than 50 items
> Large Records List Limited

- src/components/renderer/form-nested-screen.vue
Fixes #611 
Make API endpoint a configurable property of the nested screen. This is so web entry set its own endpoint.
> Make the api endpoint a configurable prop

- src/components/renderer/form-loop.vue
- src/components/vue-form-renderer.vue
- src/main.js
Fixes #592.
The fix for this is described at https://github.com/ProcessMaker/screen-builder/issues/592#issuecomment-592125989.
> Fix buttons in loops

- src/components/inspector/loop.vue
- src/components/renderer/form-loop.vue
Fixes #614 
Fix to make it work with dot notation nested variables like 'foo.bar'
> Make it work with dot notation variable names

- src/components/renderer/form-record-list.vue
Add `.d-table` class to the Record List table.
<h2>Before</h2>
<h2>After</h2>
> Fix record list table styling

- src/components/inspector/validation-select.vue
- Adds a computed property to replace a conditional that was causing the Validation section to disappear in the inspector panel
Closes #624.
> Add hasRules computed to ValidationSelect to fix error

- package-lock.json
- package.json
- vue-form-elements to v0.13.4
Closes #633.
> Update vue-form-elements to v0.13.4

- src/components/renderer/form-loop.vue
- src/components/renderer/form-record-list.vue
- src/components/vue-form-renderer.vue
Fixes #631
Also requires https://github.com/ProcessMaker/vue-form-elements/pull/167
> Allow access to the _parent variable in record lists and loops

- package-lock.json
- package.json
> Update Vue Form Elements

- src/components/inspector/options-list.vue
Adds inspector configurations to allow users to return a single value or object from a select list or radio buttons.
dep: [vue-form-elements/#168](https://github.com/ProcessMaker/vue-form-elements/pull/168)
closes #619
> Select List return Object

- src/components/renderer/form-loop.vue
> Allow items in loop control to mutate _parent variable

- src/components/editor/multi-column.vue
- src/components/renderer/form-multi-column.vue
Fixes #638 
Fixes loop controls inside multicolumns
> Fix loop control in multicolumns

- src/components/vue-form-renderer.vue
Fixes #571 
Scrolls to top on page navigation when inside embedded web entry
> Allow embedded web entry to scroll to top

- package-lock.json
- package.json
- vue-form-elements
Closes #649.
> Update vue-form-elements to v0.13.6

- src/components/editor/loop.vue
- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
closes #369 
- Change label Duplicate to Copy
> Change Tooltip: Duplicate => Copy

- src/components/inspector/validation-select.vue
Adds new validation rules:
- date
- after:date
- after_or_equal:date
- before:date
- before_or_equal:date
- regex:pattern
dep: https://github.com/ProcessMaker/vue-form-elements/pull/179
closes #654
> Add Validation Rules

- package-lock.json
- package.json
> Updating vue-form-elements to v0.13.8

- src/components/vue-form-renderer.vue
- src/mixins/defaultValues.js
- tests/unit/fixtures/VueFormRendererWrapper.vue
> Fix default values not loading on page load

- src/components/renderer/form-loop.vue
> Add ability to remove loop elements

- src/components/renderer/form-loop.vue
> Don't show delete loop item button if there are no items to delete

- src/components/renderer/form-loop.vue
The delete button had "Add Item" for a tooltip.
> Change tooltip text for deleting loop

- package-lock.json
- package.json
> Update vue-form-elements to v0.14.1

- package-lock.json
- package.json
> Bumping vue-form-elements to v0.14.2

- src/components/renderer/form-record-list.vue
- Improves the wording and styling of the empty record list message
- Requires https://github.com/ProcessMaker/processmaker/pull/3084 to update the language file
Closes #684.
> Update empty record list message

- src/components/renderer/form-loop.vue
- src/components/renderer/form-nested-screen.vue
- src/components/renderer/form-record-list.vue
- src/mixins/defaultValues.js
- tests/unit/DefaultValues.spec.js
> Fix default values in record list

- src/components/renderer/form-record-list.vue
> Fix record list when inside multi column

- src/components/inspector/validation-select.vue
Adds an 'Update' button when editing validations.
closes #691
> Validation Edit Action Button

- src/components/inspector/validation-select.vue
<h2> Changes</h2>
Fix errors when you first add a rule and select the cancel button.
Ref https://github.com/ProcessMaker/screen-builder/issues/691#issuecomment-625400937
> Fix Cancel button errors

- package-lock.json
- package.json
- Fixes inability to build screen-builder by locking lodash and vue-loader version dependencies
Closes #701.
> Lock lodash and vue-loader versions

- package-lock.json
- package.json
- vue-form-elements
Closes #706.
> Bump vue-form-elements

- src/components/renderer/form-record-list.vue
Fixes #713 
Note this only fixes editing a record. Was not able to reproduce when adding (see issue for screencast)
> Fix record list validation when editing a record

- package-lock.json
- package.json
- vue-form-elements
Closes #718.
> Vue Form Elements v0.14.5

- src/components/renderer/form-loop.vue
- src/components/renderer/form-multi-column.vue
- src/components/vue-form-renderer.vue
Fixes #715 
To test, import "Client Setup 5" from 
[FreezingScreen.zip](https://github.com/ProcessMaker/screen-builder/files/4625252/FreezingScreen.zip)
Select business
Click continue
Start typing a business name
If it doesn't freeze anymore it's fixed
> Only set parent data for specific keys that change in loop control

- src/components/inspector/validation-select.vue
Add validation select validation if null
> Validation Edit Missing Action Buttons

- src/components/renderer/form-loop.vue
- src/components/renderer/form-nested-screen.vue
- src/components/vue-form-renderer.vue
> Fix file uploads in loop control

- src/components/renderer/form-masked-input.vue
Reverts ProcessMaker/screen-builder#730
Move to use lodash for the debounce
> Revert "Debounce input change"

- src/components/inspector/options-list.vue
Resolves #726 
Now the Value field is not reset when the the datasource field is changed.
> Select List Value Config Not Saving

- src/components/renderer/form-masked-input.vue
> Remove input debounce

- package-lock.json
- package.json
##Updates\n-Updates Vue Form Elements from v0.14.10 to v0.14.11
> Vue Form Elements v0.14.11

- package-lock.json
- package.json
- Updates Vue Form Elements from v0.14.11 to v0.14.12
> Vue Form Elements v0.14.12

- src/currency.json
JIRA: https://processmaker.atlassian.net/browse/FOUR-1625
> Changed NGN to use a comma instead of a dot.

- src/mixins/defaultValues.js
- Wrap mustache value in an additional curly brace to prevent HTML from escaping. 
https://www.loom.com/share/2024cbe8b18f4cc3bc4aebcacaeb46e8
- Import this process. [Mustache Text.json.txt](https://github.com/ProcessMaker/screen-builder/files/4847934/Mustache.Text.json.txt)
- In the Company Name field use ampersands and apostrophes.
The inputted data should be formatted correctly in the Record List Add modal fields. 
closes #767  and ProcessMaker/processmaker#3220
> Fix mustache formatting issues

- src/components/renderer/form-masked-input.vue
closes #765 
- remove percentage validation
need https://github.com/ProcessMaker/vue-form-elements/pull/201
> Percentage and Validation

- package-lock.json
- package.json
- Updates Vue Form Elements from v0.14.12 to v0.14.13
> Vue Form Elements v0.14.13

- src/factories/ValidatorFactory.js
closes #780 
- Add search for validations in loops.
> Loops preventing form submission

- src/factories/ValidatorFactory.js
issue https://processmaker.atlassian.net/browse/FOUR-1472
- Add data type format to validations for submit.
> Data type format validations

- src/factories/ValidatorFactory.js
Data Types validations were missing validation rules for both percentage and password data types. This made the form invalid and prevent form submissions.
This PR adds the missing data type validation rules for data types. percentage & password
1. Create a Screen
2. Add a Line Input control with Percentage or Password Data Type
3. Open the developer console
4. Go to the preview button, enter a number
5. Press the submit button
The form successfully submits.
**Reference JIRA Ticket**
https://processmaker.atlassian.net/browse/FOUR-1780
> Fix form submissions with percentage & password data types

- src/components/renderer/form-record-list.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-1789
Fixes record list clearing parent form data when adding a record
> [FOUR-1789] Fix record list add clearing parent data

- src/components/inspector/column-setup.vue
Fixed https://processmaker.atlassian.net/browse/FOUR-1943
- Change load options of column setup of record List
> Console error when configuring a second Record List

- src/components/renderer/form-record-list.vue
Resolves FOUR-1966
- Support to upload and download files in record lists has been added
- Now RecordList send an event to all file download/upload controls with a unique identifier of every row.
> FOUR-1966: Documents in Record Lists not saving correctly

- src/components/renderer/form-record-list.vue
Fixed [FOUR-1954](https://processmaker.atlassian.net/browse/FOUR-1954)
- Get formConfig from parent from recordlist
> Modal in Record List not showing in Loop Control

- src/factories/ValidatorFactory.js
Fixed [FOUR-2054](https://processmaker.atlassian.net/browse/FOUR-2054)
- validation rule is array
> Screen gives a JS error when there is a file upload set to required in a loop

- src/components/inspector/options-list.vue
- src/form-builder-controls.js
Resolves [https://processmaker.atlassian.net/browse/FOUR-2041](https://processmaker.atlassian.net/browse/FOUR-2041)
- Prints scaped html in options list
- Remove of default format for select lists
> FOUR-2041 - Select lists with a Collection data source only load first 10 records

- src/components/vue-form-builder.vue
Fixed [FOUR-1927](https://processmaker.atlassian.net/browse/FOUR-1927)
do not overwrite validation in FileUpload component.
> File package problems

- src/components/vue-form-builder.vue
- Fix inspector used to configure Submit Buttons
> Fix inspector for Submit Button

- src/mixins/watchers.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2160
Do not attempt to hide the popup if it does not exist
> Fix watcher error when switching between builder and preview

- src/components/task.vue
- Fixes an infinite loop when loading tasks and the next assigned task.
- Passes screen type for conversational forms
> Add Conversational Forms Support

- package-lock.json
- package.json
> Vue Form Elements v0.16.0

- src/components/vue-form-renderer.vue
Fixed [FOUR-2271](https://processmaker.atlassian.net/browse/FOUR-2271)
- Remove padding screen renderer
> Modeler Inspector Has additional padding

- src/components/vue-form-renderer.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2110
The parsed css was rendering using the wrong component
> Fix custom css not working

- package-lock.json
- package.json
- Fixes an issue where the vue-form-elements peer dependency did not match the dev dependency
> Fix vue-form-elements peer dependency

- src/App.vue
- src/form-builder-controls.js
- Fix to load properly the right form inspector for submit (FOUR-2097)
> Fix FormSubmit loading

- package-lock.json
- package.json
> Vue Form Elements v0.17.1

- src/form-builder-controls.js
Resolves [https://processmaker.atlassian.net/browse/FOUR-2183](https://processmaker.atlassian.net/browse/FOUR-2183)
The variable pmqlQuery was not initialized. This caused that when adding a new select list, the last value of this variable was copied to the new select list.
> FOUR-2183 Cannot get data from a Collection

- package-lock.json
- package.json
- tests/e2e/fixtures/watcher_select_list.json
- tests/e2e/specs/ComplexScreen.spec.js
- tests/e2e/specs/Watchers.spec.js
Fixes: https://github.com/ProcessMaker/vue-form-elements/pull/239
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/239
- Test to verify reactivity of SelectList options with Request variables changed by watchers.
> Reactivity of Select List Options with Request Data and Watchers

- src/components/screen-renderer.vue
- src/components/vue-form-renderer.vue
- src/mixins/ScreenBase.js
This PR fixes: https://processmaker.atlassian.net/browse/FOUR-2077
Fix multiple page printing in PM.
> Fix multiple page printing in PM

- src/components/task.vue
Resolves [https://processmaker.atlassian.net/browse/FOUR-2416](https://processmaker.atlassian.net/browse/FOUR-2416)
- csrf_token variable fixed
- code to support additional screen renderers added
> FOUR-2416: Advanced screen does not display any content even by using the default code

- src/components/renderer/form-nested-screen.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2451
Also needs https://github.com/ProcessMaker/processmaker/pull/3539
Hides the page navigation button in nested screens. Pages in nested screens are not supported.
> Hide page navigate buttons in nested forms

- src/mixins/Json2Vue.js
- src/mixins/extensions/LoadFieldComponents.js
- tests/e2e/specs/RecordList.spec.js
- tests/e2e/support/commands.js
Fixed [FOUR-2463](https://processmaker.atlassian.net/browse/FOUR-2463)
- remove variables from popup forms (record List)
> Record Lists inserting extra data into the root object

- src/App.vue
- src/components/screen-renderer.vue
- Fixes an error where components seem to shift around in screen builder when they are in an error state
Closes https://processmaker.atlassian.net/browse/FOUR-2505
> Remove animation from error form group

- src/components/inspector/screen-selector.vue
- src/components/vue-form-builder.vue
Part of https://processmaker.atlassian.net/browse/FOUR-2504 
Limit the screen select to display screens in the nested screen inspector
> Add support for nested display screens

- src/components/renderer/form-loop.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2523
Loops were breaking if the incoming variable wasn't an array. This resets it to the correct format if it's not correct.
> Make sure incoming loop data is an array

- src/components/renderer/form-record-list.vue
Resolves #871 
- Render images in record lists
> Render images in record lists

- src/components/vue-form-builder.vue
- src/form-builder-controls.js
- tests/e2e/fixtures/nested_screen_with_event_submit.json
- tests/e2e/specs/NestedScreen.spec.js
- tests/e2e/support/commands.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2434
Nested screen control config had accidentally set `event: submit`. Removed that and fixed the element name. Also added a test for it.
> Fix nested screen inspector and add test

- src/components/watchers-list.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2466
Wraps long variable names in list
> Allow wrapping of long variable names in watchers list

- src/components/renderer/file-upload.vue
- tests/e2e/fixtures/record_list_fileupload.json
- tests/e2e/fixtures/record_list_fileupload_required.json
- tests/e2e/specs/RecordList.spec.js
This PR contains:
- Fix display of file upload component in record lists.
- Add required feedback message when the field is required
- Add tests to verify file upload in record lists
> Fix fileupload in record lists

- src/components/inspector/screen-selector.vue
- src/form-builder-controls.js
Fixed [FOUR-2537](https://processmaker.atlassian.net/browse/FOUR-2537)
- validate if the nested form has navigation buttons
> Screens with page navigation are not shown inside a nested screen

- src/components/renderer/form-button.vue
- src/components/renderer/new-form-multi-column.vue
Fixes observations in [https://processmaker.atlassian.net/browse/FOUR-2534](https://processmaker.atlassian.net/browse/FOUR-2534)
Overflow fixed in multicolumns
> FOUR-2534: Controls overlap on top of others

- src/components/renderer/form-button.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-2678](https://processmaker.atlassian.net/browse/FOUR-2678)
> FOUR-2678: The value of the submit button variable is always null

- src/components/watchers-list.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2466?focusedCommentId=208268
> Remove padding from bottom of watchers list

- src/components/inspector/validation-select.vue
- src/mixins/ValidationRules.js
- src/mixins/extensions/ValidationRules.js
Fixed [FOUR-2717](https://processmaker.atlassian.net/browse/FOUR-2717)
- add rule
> The validation rule "same", gives errors in the request

- src/DataProvider.js
- src/components/renderer/form-nested-screen.vue
- src/components/task.vue
- src/form-builder-controls.js
- tests/e2e/specs/Task.spec.js
Requires: https://github.com/ProcessMaker/processmaker/pull/3639
This PR add support for navbuttons in nested screens.
Restored previous method to load nested screens from screen endpoint and task endpoint
> Support navbuttons in nested screens

- src/components/task.vue
Fixed [FOUR-2727](https://processmaker.atlassian.net/browse/FOUR-2727)
- remove immediate attribute due to problems with watchers events
> Intermediate Web Entry triggers a watcher console error, even with no watchers created

- src/components/renderer/form-button.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-2678](https://processmaker.atlassian.net/browse/FOUR-2678)
Improves the solution sending the submit until the first the emit input is finished.
> FOUR-2678: The value of the submit button variable is always null 

- src/components/task.vue
Fix query string used in webentry
> Fix query string used in webentry

- src/components/accordions.js
- src/components/renderer/form-masked-input.vue
- src/global-properties.js
https://processmaker.atlassian.net/browse/FOUR-2740
<h2>Change</h2>
Within the 'Advanced' accordion for a Line Input control, there is now an area to allow custom mask formatting. 
**Video**
https://www.loom.com/share/bd9e8c2e926a4b3c85f810a11c4f12b4
> Add Custom Formatting Support

- src/mixins/ValidationRules.js
[FOUR-2755](https://processmaker.atlassian.net/browse/FOUR-2755)
- validate error messages of rules
> Error message in Console, with the screen preview, with the validation "after or Equal to date"

- src/components/inspector/loop.vue
- src/mixins/LoopControl.js
- tests/e2e/specs/Loop.spec.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2747
> Do not initialize loop variables if configured for existing data

- src/components/renderer/file-download.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2758
> Add missing download control label

- src/components/renderer/form-nested-screen.vue
- src/components/vue-form-renderer.vue
- src/factories/ValidatorFactory.js
- src/main.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2550
- Brings in the changes from https://github.com/ProcessMaker/screen-builder/pull/884 for screen bulder v2
> Fix nested screen validation when submitting from another page

- src/mixins/extensions/Watchers.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2781
> Only trigger watcher if changed value is not undefined

- src/mixins/computedFields.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2789
> If the computed field returns a date, convert it to an iso string

- src/components/screen-renderer.vue
https://processmaker.atlassian.net/browse/FOUR-2800
Adds a fluid class to the parent container for nested screens.
> Fix container margins for nested screen

- src/components/task.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2799
- This only fixes the start event interstitial. The others mentioned in the ticket are from the other tasks not having an assignment rule set
> Fix interstital on start event displayed in core

- src/mixins/computedFields.js
Fixed [FOUR-2797](https://processmaker.atlassian.net/browse/FOUR-2797)
- Add a proxy in calculated properties for variables.
> Screen Freeze with several operations

- src/mixins/watchers.js
**Jira Tickets**
https://processmaker.atlassian.net/browse/FOUR-2809
- Updates how the watcher output variable value is first set when the request data is returned.
**Video**
https://www.loom.com/share/39fd3fc5b9924d3796769b3d1e5fab07
> Fixes Request Data not loading in select lists while using a watcher

- src/components/task.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2773?focusedCommentId=211753
> Check if the request is complete when loading the task

- src/form-control-common-properties.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2805?focusedCommentId=211635
> Validate variable name does not begin or end with a dot

- src/factories/CustomValidationRules.js
https://processmaker.atlassian.net/browse/FOUR-2826
- Registers the missing custom date validation `custom_date` in the ValidatorFactory file. 
**Video**
https://www.loom.com/share/1fa3f667d85b4f82be0382f59715cc0a
> Fix 'date' validation console error

- src/mixins/LoopControl.js
- tests/e2e/specs/Loop.spec.js
Fixes https://processmaker.atlassian.net/browse/FOUR-2747?focusedCommentId=212076
> If the existing loop array is null, set it to an empty array

- src/components/renderer/form-masked-input.vue
https://processmaker.atlassian.net/browse/FOUR-2855
- Add missing VFE `ValidationMixin` file to fix validations running in conversational forms. 
**Video**
https://www.loom.com/share/317d770308084b1b9e7c64ba9228f50c
> Fix validations in Conversational Forms

- src/components/task.vue
https://processmaker.atlassian.net/browse/FOUR-2856
- Load conversational form interstitials in a `custom component` instead of `vue-form-renderer`.
**To Test**
- Create a process: Conform w/ Interstitial enabled > Script task > Conform > End Event
- Run process
Interstitial should display within the conversational form, once the script task is completed, interstitial should be removed and the next form question should be displayed.
**Video**
https://www.loom.com/share/58913164f02847749a05e9e9f3b75071
> Fix loading conversational forms interstitials

- src/components/renderer/file-upload.vue
- src/components/renderer/form-record-list.vue
Resolves [https://processmaker.atlassian.net/browse/FOUR-2808](https://processmaker.atlassian.net/browse/FOUR-2808)
Fixes the additional use case of creating a record in a record list and deleting it. Now the uploaded file associated with the record is deleted too.
> FOUR-2808: It shows all files uploaded by mistake, when completing the task

- src/components/vue-form-builder.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2896
> Do not reset the editor-control if it's a button

- src/components/renderer/file-download.vue
- src/components/task.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2923
> Reset the request id in meta tag if it changes

- src/components/renderer/form-record-list.vue
- src/components/vue-form-renderer.vue
- src/factories/CustomValidationRules.js
- src/mixins/ScreenBase.js
- src/mixins/extensions/ValidationRules.js
- tests/e2e/fixtures/validation_rules.json
- tests/e2e/specs/ComplexScreen.spec.js
- tests/e2e/specs/ValidationRules.js
Fixed [FOUR-2892](https://processmaker.atlassian.net/browse/FOUR-2892)
- Remove custom validation before
> Date entered with the Date Picker cannot be submitted with the Submit button

- src/components/renderer/add-loop-row.vue
- src/components/renderer/file-upload.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-2808](https://processmaker.atlassian.net/browse/FOUR-2808)
In the previous associated PR file removal was implemented just in record lists. This PR adds the same functionality to loops
> FOUR-2808: It shows all files uploaded by mistake, when completing the task 

- src/components/task.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2979
> Queue task load events so they don't run simultaneously

- src/components/inspector/validation-select.vue
Fixed [FOUR-2958](https://processmaker.atlassian.net/browse/FOUR-2958)
- Validate undefined value for rules
> When updating a validation rule on any field then inputting an textarea field on the screen a console errors appear.s

- src/mixins/extensions/DataManager.js
- src/mixins/extensions/ValidationRules.js
Resolves: https://processmaker.atlassian.net/browse/FOUR-2876
Fix path validation when variable name includes dots like `result.name`
> Fix value path validation

- src/components/task.vue
Feature: https://processmaker.atlassian.net/browse/FOUR-3104
Add interstitial for tasks in sub processes.
> Listen interstitial in subprocess

- src/components/watchers-form.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-3111
- Minor label changes
> FOUR-3111: Watcher should say Resource instead of end point

- src/components/task.vue
Develop PR for fix in https://github.com/ProcessMaker/screen-builder/pull/970
> Fix interstitial after advanced screen not showing

- src/components/renderer/form-button.vue
Resolves: https://processmaker.atlassian.net/browse/FOUR-3026
This PR enables the user to execute multiple times a watcher clicking a regular button
> Switch button value on multiple clicks

- package-lock.json
- package.json
- src/components/renderer/form-nested-screen.vue
- src/mixins/ScreenBase.js
- src/mixins/extensions/LoadFieldComponents.js
- src/mixins/extensions/LoopContainer.js
- tests/e2e/fixtures/parent_variable.json
- tests/e2e/specs/ParentVariable.spec.js
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/263
- Fix SelectList reactivity to _parent variable
- Test SelectList using `_parent` from inside a RecordList
- Test SelectList using `_parent` from inside a Loop>NestedScreen
> Fix SelectList reactivity to _parent variable

- src/DataProvider.js
- src/main.js
- src/mixins/watchers.js
- tests/e2e/specs/Watchers.spec.js
See https://github.com/ProcessMaker/processmaker/pull/3772
> Run scripts and data sources in sync mode

- src/components/screen-renderer.vue
- src/mixins/ScreenBase.js
- src/mixins/extensions/PageNavigate.js
Fix issue of initial page in record list popups
> Set initial current page

- package-lock.json
- package.json
- src/components/renderer/form-button.vue
Fixes: https://processmaker.atlassian.net/browse/FOUR-3026
Fix first click a button with empty value
> Fix first click a button with empty value

- src/components/inspector/options-list.vue
Fixed [FOUR-3207](https://processmaker.atlassian.net/browse/FOUR-3207)
- Add select option in select datasources list and endpoint list
> Error 401, when I try to configure my select list with data connector

- src/components/inspector/data-mapping.vue
- src/components/inspector/outbound-config.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-3295](https://processmaker.atlassian.net/browse/FOUR-3295)
> FOUR-3295: Improve watcher outbound configuration helper text 

- src/components/inspector/data-mapping.vue
- src/components/inspector/outbound-config.vue
- src/components/watchers-form.vue
Fixes [https://processmaker.atlassian.net/browse/FOUR-3288](https://processmaker.atlassian.net/browse/FOUR-3288)
As before,  the select list shows all the variables of the current screen but additionally the user can type any string so that he can use any request variable name.
> FOUR-3288: Watchers on Display Screens

- src/components/accordions.js
- src/components/inspector/index.js
- src/components/inspector/tooltip.vue
- src/components/renderer/form-button.vue
- src/form-builder-controls.js
- src/form-control-common-properties.js
Fixed [FOUR-3073](https://processmaker.atlassian.net/browse/FOUR-3073)
- Add property tooltip
- add tooltip to normal button
> Button Tooltip

- src/components/renderer/form-button.vue
Fix trigger watcher with button
> Fix trigger watcher with button

- src/components/renderer/form-record-list.vue
> Fix tracking of current page

- src/components/renderer/form-record-list.vue
- src/mixins/extensions/LoadFieldComponents.js
Fixed [FOUR-3176](https://processmaker.atlassian.net/browse/FOUR-3176)
- Enable watcher in record list
> Watcher on a Record List is not working

- src/components/renderer/form-record-list.vue
- src/mixins/extensions/Watchers.js
- tests/e2e/fixtures/watcher_on_loop_inside_recordlist.json
- tests/e2e/fixtures/watcher_on_loop_new_array.json
- tests/e2e/specs/WatcherOnLoops.js
Fixes: https://processmaker.atlassian.net/browse/FOUR-3419
When a Watcher is added to see a Loop, the watcher is triggered when the screen is loaded.
- Moves the Watcher initialization to the nextTick after all variables are initialized
> Fix: Watcher runs without modifying variable to watch

- src/components/renderer/form-record-list.vue
https://processmaker.atlassian.net/browse/FOUR-3423
- Update the delete modal button label to 'Delete'
> Fix 'Delete' button label

- src/components/inspector/options-list.vue
https://processmaker.atlassian.net/browse/FOUR-3301
- Add validation for the Data Connector and Endpoint select lists when configuring a data source.
https://user-images.githubusercontent.com/52755494/120015405-27499500-bf98-11eb-859f-53838be3ff83.mov
> Add validation messages for the Data Connector and Endpoint Select list

- src/form-control-common-properties.js
Fixes [FOUR-3477](https://processmaker.atlassian.net/browse/FOUR-3477)
- Change regex validation variable name
> It is not possible to create a variables Object with low bar "_"

- src/components/vue-form-builder.vue
- src/mixins/testing.js
Resolves: https://processmaker.atlassian.net/browse/FOUR-3432
This PR implements:
- Helper automation function to add control to the screen
https://user-images.githubusercontent.com/8028650/120506399-e08edd00-c393-11eb-9fcd-345ee7928a97.mp4
> Helper automation function to add control to the screen

- src/components/renderer/form-masked-input.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-3406
> Return null instead of NaN for empty float and int values

- src/components/inspector/screen-selector.vue
- tests/e2e/specs/NestedScreen.spec.js
- Fixes https://processmaker.atlassian.net/browse/FOUR-3445
> Add screen link to nested screens select

- src/mixins/ScreenBase.js
Fixes [FOUR-3426](https://processmaker.atlassian.net/browse/FOUR-3426)
- add data _parent to get validation data
need [vue-form-element](https://github.com/ProcessMaker/vue-form-elements/pull/272)
> _parent not working in loops with Rich text control

- src/components/editor/loop.vue
- src/components/editor/multi-column.vue
- src/components/inspector/color-select.vue
- src/components/inspector/column-setup.vue
- src/components/inspector/container-columns.vue
- src/components/inspector/default-value-editor.vue
- src/components/inspector/validation-select.vue
https://processmaker.atlassian.net/browse/FOUR-2338
> Accessibility updates

- src/components/renderer/file-upload.vue
Fixes https://processmaker.atlassian.net/browse/FOUR-2336
See https://github.com/ProcessMaker/processmaker/pull/3886
> Make file upload button accessible to keyboard commands

- src/App.vue
- src/CountElements.js
- src/components/inspector/default-value-editor.vue
- src/components/vue-form-renderer.vue
- src/components/watchers-form.vue
- src/form-control-common-properties.js
- src/mixins/Json2Vue.js
Add warnings, recommendations and helper text.
> Add warnings, recommendations and helper text

- src/components/inspector/input-variable.vue
- src/components/inspector/validation-select.vue
- src/mixins/ValidationRules.js
- tests/e2e/fixtures/test_parent_in_validations.json
- tests/e2e/fixtures/validation_rules.json
- tests/e2e/specs/ValidationRules.js
Fixes: https://processmaker.atlassian.net/browse/FOUR-3625
http://tickets.pm4overflow.com/tickets/139
- E2E tests for validations rules using reference to `_parent`
- Fix access to `_parent` variables from nested components like loops and record lists
https://user-images.githubusercontent.com/8028650/127360031-fced08ae-98c8-4b17-bc60-736f06dafc4b.mp4
> Fix validation rules (eg. RequiredIf) that uses references to _parent

- src/DataProvider.js
See https://github.com/ProcessMaker/processmaker/pull/3917
> Referenced nested screen by parent if it's a screen version

- package-lock.json
- package.json
https://github.com/ProcessMaker/screen-builder/pull/1031 for develop
> Upgrade inputmask package

- src/mixins/extensions/LoadFieldComponents.js
- tests/e2e/specs/ComputedFieldsReadOnly.spec.js
This PR disables control edition when it is assigned to a calc property
https://user-images.githubusercontent.com/8028650/128442056-430668d2-3e93-4156-badb-53b887a65a5f.mp4
> Disable control edition when assigned to a calc property

- src/main.js
- src/mixins/watchers.js
Fixes: http://tickets.pm4overflow.com/tickets/331
- changes script response notification by  script response event.
- fix the stop listening of events when the screen is destroyed
> Change script execution response notification to script response event

- src/components/task.vue
Fixes [http://tickets.pm4overflow.com/tickets/337](http://tickets.pm4overflow.com/tickets/337)
> ticket 337: Manual Task has Trusted being showed in the variable List

- src/mixins/ValidationRules.js
- tests/e2e/fixtures/validation_rules_name_object.json
- tests/e2e/specs/ValidationRulesNameObject.js
Fixes [Ticket](http://tickets.pm4overflow.com/tickets/333)
[FOUR-3378](https://processmaker.atlassian.net/browse/FOUR-3378)
[FOUR-3408](https://processmaker.atlassian.net/browse/FOUR-3408)
- change data to vdata in validarion rules.
> Object Property Not Validating

- src/components/inspector/data-mapping.vue
Related to: http://tickets.pm4overflow.com/tickets/563
Required by: https://github.com/ProcessMaker/processmaker/pull/3945
Required by: https://github.com/ProcessMaker/package-data-sources/pull/180
This PR changes the Watcher configuration Form Variable to a form input.
> Change request variable to form-input

- src/form-builder-controls.js
- tests/e2e/specs/FileUpload.spec.js
Fixes http://tickets.pm4overflow.com/tickets/562
> Use keyNameProperty for FileUpload

- src/form-builder-controls.js
Fixes http://tickets.pm4overflow.com/tickets/512
> Remove helper text inspector item from images

- src/components/inspector/options-list.vue
- tests/e2e/specs/FormSelectList.spec.js
- tests/e2e/support/commands.js
Fixes [http://tickets.pm4overflow.com/tickets/537](http://tickets.pm4overflow.com/tickets/537)
> ticket 537: JSON On Single Line

- src/components/inspector/options-list.vue
- src/components/inspector/validation-select.vue
Fixes [http://tickets.pm4overflow.com/tickets/599](http://tickets.pm4overflow.com/tickets/599)
> ticket 599: Validation Delete Confirmation UI

- package-lock.json
- package.json
- src/ValidationsFactory.js
- src/components/vue-form-builder.vue
- tests/e2e/fixtures/screen_with_readonly_fields.json
- tests/e2e/specs/ValidationRules.js
- Skips validation if a field is readonly or has been disabled
- https://github.com/ProcessMaker/vue-form-elements/pull/283
- http://tickets.pm4overflow.com/tickets/600
> Ticket #600: Skip validation for readonly fields

- src/DataProvider.js
- src/components/inspector/options-list.vue
- src/components/renderer/file-upload.vue
- src/main.js
- src/mixins/extensions/LoadFieldComponents.js
- src/mixins/watchers.js
- tests/e2e/specs/ComputedFieldsReadOnly.spec.js
- tests/e2e/specs/FormSelectList.spec.js
- tests/e2e/support/commands.js
This batch contains the following screen builder fixes from 4.1 to 4.2
Ticket # | Link
-- | --
190 | http://tickets.pm4overflow.com/tickets/190
322 | http://tickets.pm4overflow.com/tickets/322
595 | http://tickets.pm4overflow.com/tickets/595
537 | http://tickets.pm4overflow.com/tickets/537
331 | http://tickets.pm4overflow.com/tickets/331
> Screen Builder 4.1 to 4.2 batch 1

- src/mixins/ScreenBase.js
- src/mixins/VisibilityRule.js
- src/mixins/extensions/VisibilityRule.js
**Changes:**
Conditions were added to:
- Not validate the hidden elements
- Validate when they are visible
**Fixes**:
- http://tickets.pm4overflow.com/tickets/742
> Ticket #742 Validation in Hidden Elements (for 4.1)

- src/mixins/ScreenBase.js
- src/mixins/VisibilityRule.js
- src/mixins/extensions/VisibilityRule.js
Changes: 
Conditions were added to:
- Not validate the hidden elements
- Validate when they are visible
Fixes:  
- http://tickets.pm4overflow.com/tickets/742
> Ticket #742 Validation in Hidden Elements (for 4.2)

- package-lock.json
- package.json
> Vue Form Elements v0.25.2

- src/form-builder-controls.js
As part of the solution of  [http://tickets.pm4overflow.com/tickets/1033](http://tickets.pm4overflow.com/tickets/1033)
- Adds the ReadOnly property to Select List
- Needs the related PR of Vue form elements
> ticket-1033: [FOUR-471] Implement read-only mode for select lists (for 4.1)

- src/form-builder-controls.js
As part of the solution of  [http://tickets.pm4overflow.com/tickets/1033](http://tickets.pm4overflow.com/tickets/1033)
- Adds the ReadOnly property to Select List
- Needs the related PR of Vue form elements
> ticket-1033: [FOUR-471] Implement read-only mode for select lists (for 4.2)

- src/components/vue-form-builder.vue
- src/undoRedoModule.js
BUGFIX for [http://tickets.pm4overflow.com/tickets/986](http://tickets.pm4overflow.com/tickets/986)
New logic for undoRedoModule
**BEFORE**
https://user-images.githubusercontent.com/90727999/136059895-8ec3748e-935e-4e05-ac3b-35a10b200ac1.mov
**AFTER**
https://user-images.githubusercontent.com/90727999/136060181-878931a9-9768-4fc7-849e-aea4cd80623f.mov
> Ticket 986: Bugfix undo/redo when deleting page (4.2)

- src/components/inspector/options-list.vue
Fixes [http://tickets.pm4overflow.com/tickets/1045](http://tickets.pm4overflow.com/tickets/1045)
Removes read only attribute from the JSON edit area
> ticket-1045:  Select Lists Edit Options as JSON is readonly (for 4.1)

- src/DataProvider.js
- src/main.js
- src/mixins/formWatchers.js
- src/mixins/watchers.js
- tests/e2e/specs/Watchers.spec.js
Fixes [Ticket 1092](http://tickets.pm4overflow.com/tickets/1092)
- change the charge of the watcher
- add timeout watcher
- update test
>  Watcher stops working, after adding record in the record list

- src/mixins/Json2Vue.js
Fixes [FOUR-4248](https://processmaker.atlassian.net/browse/FOUR-4248)
- Add validation exists variable $v
> The error "Cannot read properties of null (reading '$ touch')" increments in the console

- package-lock.json
- package.json
- src/components/inspector/options-list.vue
- tests/e2e/fixtures/select_list_array_data.json
- tests/e2e/fixtures/select_list_mustache.json
- tests/e2e/fixtures/select_list_mustache_custom_key.json
- tests/e2e/fixtures/select_list_mustache_request_data.json
- tests/e2e/specs/LoadComplexData.spec.js
- tests/e2e/specs/SelectListMustache.spec.js
Fixes: http://tickets.pm4overflow.com/tickets/1205
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/293
- Tests to replicate issues with mustache in Select Lists
- Add missing config option "key" for data sources
> Fix mustache replacement in SelectLists

- package-lock.json
- package.json
- tests/e2e/fixtures/select_list_datasource.json
- tests/e2e/specs/SelectListDataSource.spec.js
When a screen with a SelectList is previously filled is loaded, the value is not displayed to the user
1. Create a Screen with a SelectList Object
2. Assign it to two consecutive Task/Process
3. Run the process
4. Select a value in the first task, submit it
5. Open the second task, the value of the SelectList is not selected/displayed 
Fix the mustache render function that returns the value to display.
Follow the Reproduction steps
- Resolves [ticket FOUR-4326](https://processmaker.atlassian.net/browse/FOUR-4326).
- vue-form-elements PR https://github.com/ProcessMaker/vue-form-elements/pull/311
> Test missing value when select list is loaded

- src/mixins/ScreenBase.js
the scenario to replicate is to have a screen with a nested screen plus a loop and to have a require if validation rule.
- have a nested screen
- the nested must have a loop
- the loop must have a rule to hide the controls
- a control must have a validation of the type requireIf
- a circular reference validation had to be done when looking for the parent of the data.
- import process and thread
- run the case until the described form is reached.
https://user-images.githubusercontent.com/1747025/144125704-5122ebd3-83a9-4de9-acba-f6f419a5e57b.mp4
- [FOUR-4366] (https://processmaker.atlassian.net/browse/FOUR-4366)
[FOUR-4366]: https://processmaker.atlassian.net/browse/FOUR-4366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RangeError: Maximum call stack size exceeded

- src/components/task.vue
Interstitials inside a sub process are not routing back to the parent.
To Reproduce:
- Import child.json and parent.json from [processes.zip](https://github.com/ProcessMaker/screen-builder/files/7645410/processes.zip)
- Edit the parent and set the sub processes to the appropriate child start events
- Run the parent start event. The interstitial does not continue after the child task.
- From the child task, we need to listen to the parent events and do a hard redirect to the next available task when it's available.
- Redirect handlers need to be added to core and webentry.
- Run the parent start event. Click on the task and verity the process continues to the end using interstitials
- Copy the web entry link from the web entry start event in the parent and verify it continues to the end …
> Handle interstitial events in a sub process

- src/mixins/ScreenBase.js
the scenario to replicate is to have a screen with a nested screen plus a loop and to have a require if validation rule.
- have a nested screen
- the nested must have a loop
- the loop must have a rule to hide the controls
- a control must have a validation of the type requireIf
- a circular reference validation had to be done when looking for the parent of the data.
- import process and thread
- run the case until the described form is reached.
https://user-images.githubusercontent.com/1747025/144125704-5122ebd3-83a9-4de9-acba-f6f419a5e57b.mp4
- [FOUR-4366] (https://processmaker.atlassian.net/browse/FOUR-4366)
[FOUR-4366]: https://processmaker.atlassian.net/browse/FOUR-4366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [4.2] RangeError: Maximum call stack size exceeded

- package-lock.json
- package.json
- src/mixins/ScreenBase.js
- src/mixins/extensions/DataManager.js
- tests/e2e/fixtures/multiselect_with_string_value.json
- tests/e2e/fixtures/nested_calc_radio_freeze.json
- tests/e2e/fixtures/single_select_with_invalid_value.json
- tests/e2e/specs/ComplexScreen.spec.js
- tests/e2e/specs/MultiselectWithStringValue.spec.js
- tests/e2e/specs/NestedCalcRadioFreeze.spec.js
- tests/e2e/specs/SingleSelectWithInvalidValue.spec.js
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/315
Fix: https://processmaker.atlassian.net/browse/FOUR-4873
Wrong default value for Radio List (an empty array) reacts with Screen mount that sets the default value of a Radio List to null.
The right default values should be:
- Radio List = null
- Check List = []
This PR includes: 
- Test to verify the problem
- Initialize the SelectList control values
How to test:
- Import process, import the screen
- Change the process task to the imported screen
- Update screen-builder and vue-form-elements into core
- npm run dev
- Run the process (normal or webentry)
- Open the task and navigate to the 2dn page of the screen.
[process test freeze.zip](https://github.com/ProcessMaker/screen-builder/files/7720756/process.test.freeze.zip) …
> FIX Screen Freeze with loops and calcs 

- package-lock.json
- package.json
- src/mixins/ScreenBase.js
- src/mixins/extensions/DataManager.js
- tests/e2e/fixtures/multiselect_with_string_value.json
- tests/e2e/fixtures/nested_calc_radio_freeze.json
- tests/e2e/fixtures/single_select_with_invalid_value.json
- tests/e2e/specs/ComplexScreen.spec.js
- tests/e2e/specs/MultiselectWithStringValue.spec.js
- tests/e2e/specs/NestedCalcRadioFreeze.spec.js
- tests/e2e/specs/SingleSelectWithInvalidValue.spec.js
Requires: https://github.com/ProcessMaker/vue-form-elements/pull/315
Fixes:
- https://processmaker.atlassian.net/browse/FOUR-4873
- https://processmaker.atlassian.net/browse/FOUR-4915
Wrong default value for Radio List (an empty array) reacts with Screen mount that sets the default value of a Radio List to null.
The right default values should be:
- Radio List = null
- Check List = []
This PR includes: 
- Test to verify the problem
- Initialize the SelectList control values
How to test:
- Import process, import the screen
- Change the process task to the imported screen
- Update screen-builder and vue-form-elements into core
- npm run dev
- Run the process (normal or webentry)
- Open the task and navigate to the 2dn page of the screen.
[process test …
> [4.2] FIX Screen Freeze with loops and calcs

- src/DataProvider.js
Fixes nested screens not loading in web entry
https://processmaker.atlassian.net/browse/FOUR-4954
> Fix screen caching for web entry

- package-lock.json
- package.json
- src/components/renderer/form-button.vue
- src/components/task.vue
- src/mixins/ScreenBase.js
- src/mixins/ValidationRules.js
- src/mixins/extensions/DataManager.js
- src/mixins/extensions/Submit.js
- src/mixins/extensions/ValidationRules.js
the scenario to replicate, just assign more than one json schema to a task.
- perform merge of the different schemes.
- create a screen
- create a 2 vocabularies
- create process
- assign the screen to the task as well as the 2 vocabularies.
- run case
https://user-images.githubusercontent.com/1747025/146952214-8ba518cc-edb0-4378-a5fa-616ae97bf30e.mp4
- [FOUR-4893] (https://processmaker.atlassian.net/browse/FOUR-4893)
- [] I have extracted this code locally and tested it on my instance, along with the associated packages.
- [] This code adheres to the [ProcessMaker Coding Guidelines] (https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [] This solution fixes the error reported in the original ticket.
- [] This solution does not alter the expected …
> [4.1] the validations in my vocabulary stop working when adding a second vocabulary

- src/mixins/ValidationRules.js
- create a screen with a field with text type validation.
- create a vocabulary with an integer validation field.
- add everything to a process.
- run the process, no error messages are displayed.
Expected behavior: display errors of form
- add messages in form
- add message error type field
https://user-images.githubusercontent.com/1747025/148108471-6fdb1080-d5a7-4b1e-bb1e-0f8da22f41fc.mp4
> [4.2] Add message validation type

- src/form-control-common-properties.js
- tests/e2e/specs/Builder.spec.js
See https://github.com/ProcessMaker/screen-builder/pull/1148
> Do not allow array index in variable name

- tests/e2e/specs/DatePicker.spec.js
Adding e2e tests from this 4.1 PR: https://github.com/ProcessMaker/screen-builder/pull/1153
> Added test cases for date picker minDate

- src/components/renderer/form-record-list.vue
- tests/e2e/fixtures/record_list_single_input.json
- tests/e2e/specs/RecordList.spec.js
Record List, The pagination is lost and the previous records are not visible if you delete all the records of the second page
- Create a record list with an line input
- Open the screen
- Go to preview
- Insert more than five records.
- Delete all the record of the second page
- You will not see the table data
- Update the current page with the correct value.
- You will see the table data
Run e2e test for recordlist
https://user-images.githubusercontent.com/90727999/150192670-0756aefd-8d84-4bf6-8bcf-7fbc67f76294.mov
- [FOUR-5104](https://processmaker.atlassian.net/browse/FOUR-5104)
> Bugfix/FOUR-5104: Record List, The pagination is lost and the previous records are not visible if you delete all the records of the second page (4.2)

- src/components/renderer/form-record-list.vue
- tests/e2e/fixtures/record_list_date_input.json
- tests/e2e/specs/RecordList.spec.js
- Create a screen with only a record list control
- Add one column named input record list
- Create a new page in order to add values to the record list
- Add a line input with input as the variable
- Go to preview and add some data
**- Try with different combinations, changing pages and sorting in different ways. IMPORTANT: The original ticket was reopened because when adding empty records to the record list in the sorting column, it was not sorting and retrieving the correct record.** For texting correctly you can add 2 inputs in the record list (input 1 and input2) and fill them in a pattern to make easy the testing. For example (please note the dashes, that means leave the field empty):
```
Input 1               Input 2
B                     2
A                     1
D …
```
> Bugfix/FOUR-5103_d: Using the sort option in a record list, doesn't update the records when using the edit action

- src/ValidationsFactory.js
Ticket: [FOUR-5630](https://processmaker.atlassian.net/browse/FOUR-5630)
Reproduce:
1. have a screen with a record list
2. inside the record list create a loop
3. inside the loop add a file upload and a FILE PREVIEW
4. relate the screen to a process
5. start a new request
Loops should work in Record Lists with no errors
When loading a page that contains a Record List with a loop, errors appear. 
- Add conditional to ensure the `page` variable is defined before continuing with the `checkForSiblings` logic. 
-
> Fix Record List and Loop error

- src/components/renderer/file-download.vue
- src/components/renderer/file-upload.vue
- src/components/renderer/form-record-list.vue
- tests/e2e/fixtures/record_list_fileupload_loops.json
- tests/e2e/specs/RecordList.spec.js
- tests/e2e/support/commands.js
- The uploaded files nested in a download file inside a loop in record list, should work correctly when editing the record and in the second task.
- The files do not appear and cannot be downloaded.
- The way to get the prefix name inside a RecordList was updated.
1. Log in 
2. Import the [attached process](https://processmaker.atlassian.net/browse/FOUR-5920) 
3. start a new request
4. upload files in the file upload that is inside a loop in a record list
5. submit the form and go to the next task
6. click on edit the record list
- [FOUR-5920](https://processmaker.atlassian.net/browse/FOUR-5920)
https://user-images.githubusercontent.com/90741874/162842007-794c7d76-3c83-4a7d-8842-c4a95a1d919b.mov
> Bugfix 5920 - file download with loop in a record list does not work correctly

- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- Create a process Start Event → Task → End Event
- Add signature controls 
- Assign the screen on the task
- Complete a Request 
- Go to Form tab
- Click on details button
- Check if store exists. Fixed condition
https://user-images.githubusercontent.com/90727999/167010404-ac043198-7c60-4e14-8fe1-3a6be637671a.mov
- [FOUR-6111](https://processmaker.atlassian.net/browse/FOUR-6111)
- [FOUR-6047](https://processmaker.atlassian.net/browse/FOUR-6047)
> Bugfix/FOUR-6111: Console error in Signature

- package-lock.json
- package.json
- src/DataProvider.js
- src/components/renderer/form-button.vue
- src/components/renderer/form-masked-input.vue
- src/components/screen-renderer.vue
- src/components/vue-form-renderer.vue
- src/main.js
- src/mixins/Json2Vue.js
- src/mixins/ScreenBase.js
- tests/e2e/specs/FOUR4849.spec.js
- tests/e2e/specs/Loop.spec.js
- tests/e2e/specs/NestedCalcRadioFreeze.spec.js
- tests/e2e/specs/RecordList.spec.js
- tests/e2e/specs/RecordListWithLoops.js
- tests/e2e/specs/RichText.spec.js
- tests/e2e/specs/ValidationRules.spec.js
- tests/e2e/support/commands.js
Reverts ProcessMaker/screen-builder#1240
https://processmaker.atlassian.net/browse/FOUR-6711
> Revert "FOUR-6098: Implement debounce for Screen text inputs after user stops typing"

- src/components/renderer/form-masked-input.vue
- src/components/renderer/new-form-multi-column.vue
- src/mixins/computedFields.js
- src/mixins/extensions/ComputedFields.js
Reactivity issues with input text
-
-
> FOUR-6789 Fix reactivity issues with input text

- src/mixins/computedFields.js
Fix missing return value in computed fields.
> Fix merge in computed fields

- package-lock.json
- package.json
- src/mixins/DataReference.js
Simplify logic to access parent
> Simplify logic to access parent

- .circleci/config.yml
- .circleci/gh_comment.sh
- .circleci/gh_pull_request.js
- tests/e2e/plugins/index.js
- tests/e2e/specs/FOUR6788_ScreenPerformanceTests.spec.js
- tests/e2e/specs/Metrics.spec.js
- tests/e2e/support/commands.js
Add PR comment with test results.
> Comment on PR

- package-lock.json
- package.json
- src/mixins/ScreenBase.js
- src/mixins/extensions/LoadFieldComponents.js
- tests/e2e/fixtures/select_list_default_value.json
- tests/e2e/fixtures/select_list_dependent.json
- tests/e2e/specs/SelectListDefaultValues.spec.js
- tests/e2e/specs/SelectListDependent.spec.js
- Login
- Create a screen with a select list
- Configure the select list with provide values, for example:
Content: Option 1, value: 1
Content: Option 2, value: 2
- Configure in the select list a default value with some none existing value, example: NONE
- Create a process and use the previous screen in a task
- Run a request and open the form task
Screen should not freeze, instead when a default value does not exist in option list, the value should be configured to null
Screen got freeze
- Emit a reset event instead input event.
Test the steps above. Ensure screen not getting freeze. Ensure dependent fields are working correctly, please see https://processmaker.atlassian.net/browse/FOUR-7124
- https://processmaker.atlassian.net/browse/FOUR-7222
- …
> Bugfix/FOUR-7222: Select list with non existing default value in options freeze the screen

- src/mixins/ScreenBase.js
- Create a process with the next configuration
- Create a Script with the next code:
```
<?php 
$res = "HOlA MUNDO B";
return ["res"=>$res];
```
- Create a screen with the next configuration
- Create a Request
- Wait that the script was executed
**Process:**
[Blank.json.zip](https://github.com/ProcessMaker/screen-builder/files/10500819/Blank.json.zip)
The screen should not be blank after the script is executed.
The screen display displays blank After the script was executed  
- Vue.set need an object. Check if the value we are trying to pass is a primitive value.
https://user-images.githubusercontent.com/90727999/214606595-535b22b2-ebc5-49fc-a8a0-2af418a6ce77.mov
- …
> Bugfix/FOUR-7303: The screen display displays blank

- src/components/renderer/file-download.vue
Per ticket: [FOUR-7270](https://processmaker.atlassian.net/browse/FOUR-7270) and 4EHELP ticket [PM4EH-110](https://processmaker.atlassian.net/jira/software/c/projects/PM4EH/boards/375?modal=detail&selectedIssue=PM4EH-110)
It has been agreed to remove File ID alert errors and display the errors in the console log. 
When a invalid file ID is referenced, surface the errors in the console **NOT** in the UI.
- Remove error alert
- Display error in console
- 
[FOUR-7270]: https://processmaker.atlassian.net/browse/FOUR-7270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM4EH-110]: https://processmaker.atlassian.net/browse/PM4EH-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> FOUR-7270: Revert File ID Error Alert Message

- src/components/renderer/file-upload.vue
Ticket: [FOUR-7162](https://processmaker.atlassian.net/browse/FOUR-7162)
1. Create Screen: The screen should have 2 pages
2. Page 1: Add file upload, with `images/png` as File Accepted and Add Page Navigation
3. Page 2: Add Page Navigation
4. Create a process
5. Assign the screen to the process
6. Create Request
7.  Upload a file `.png` type
8. Click on page navigation 
9. Return to back to the first form
10. Upload a file different to `.png`
The uploaded file should still be displayed after tying to upload an invalid file.
The uploaded file disappears after trying to upload an invalid file.
When navigating between pages the `Uploader` component creates a new instance and does not inherit the previously uploaded files. The solution is to dynamically …
> FOUR-7162 Fix: re-upload stored files to Uploader component

- src/components/renderer/file-download.vue
This fix is part of the epic FOUR-5761
Main PR https://github.com/ProcessMaker/processmaker/pull/4440
[FOUR-5761]: https://processmaker.atlassian.net/browse/FOUR-5761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix/FOUR:6296: Fix download name on collections

- src/components/task.vue
- tests/e2e/specs/Task.spec.js
Reverts ProcessMaker/screen-builder#1305
> Revert "FOUR-6704:Update Task.view with shouldRedirectToParentRequest()"

- src/mixins/extensions/DefaultValues.js
- tests/e2e/specs/DefaultValues.spec.js
when the user type a variable like "person.name" the default value property does not work
the default value property must work for the next cases: "variableName" "variableName.property"
Preview has .js errors.
- default value property was fixed and the error does not appear anymore
- https://processmaker.atlassian.net/browse/FOUR-7546
> FOUR-7546: Default value is not working in select list object type

- src/components/vue-form-builder.vue
This PR is part of the Autosave feature for Screens.
- Emit screen change event
- [FOUR-7336](https://processmaker.atlassian.net/browse/FOUR-7336)
- [Core Pull Request](https://github.com/ProcessMaker/processmaker/pull/4646) 
[FOUR-7336]: https://processmaker.atlassian.net/browse/FOUR-7336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-7336 - Autosave Screen

- src/components/inspector/collection-select-list.vue
- src/components/watchers-form.vue
- tests/e2e/specs/SelectListDependentCollection.spec.js
See: https://github.com/ProcessMaker/package-collections/pull/338
- Remove duplicate labels in select list for https://processmaker.atlassian.net/browse/FOUR-7937
- Fix test
Required PRs
- https://github.com/ProcessMaker/vue-form-elements/pull/391
- https://github.com/ProcessMaker/package-collections/pull/338
> Add setting to remove duplicates in collection select list

- src/components/renderer/file-upload.vue
1. Create Screen
2. Add file upload
3. Configure the file upload to png 
4. Add file upload with multiple files
5. Configure the file upload to pdf
6. Assign the screen in each task
7. Create a request 
8. Upload valid files in each upload
9. Open the second task
10. Upload a wrong format in each files
Expected behavior:
Users should not be able to upload the wrong format
Actual behavior:
The files uploaded were lost after upload wrong format
- We revert the change from [FOUR-8433](https://processmaker.atlassian.net/browse/FOUR-8433) which caused the regression
- We add the `accept` attribute to the upload component to prevent the wrong format from being uploaded in the first place, thereby solving [FOUR-8433](https://processmaker.atlassian.net/browse/FOUR-8433) …
> [FOUR-8458] Add accept attribute to file uploader

- package-lock.json
- https://github.com/ProcessMaker/vue-form-elements/pull/398
- https://processmaker.atlassian.net/browse/FOUR-8510
ci:deploy
ci:vue-form-elements:bugfix/FOUR-8510
> FOUR-8510 Updated moment and moment-timezone to solve some CVE's

- src/App.vue
- src/components/inspector/form-multiselect.vue
- src/components/inspector/validation-select.vue
- src/components/renderer/file-upload.vue
- src/components/renderer/form-masked-input.vue
- src/components/vue-form-renderer.vue
- src/main.js
- src/mixins/ScreenBase.js
- src/mixins/extensions/LoopContainer.js
- src/mixins/extensions/ValidationRules.js
- src/store/modules/globalErrorsModule.js
- tests/e2e/specs/DatePicker.spec.js
- tests/e2e/specs/Loop.spec.js
- tests/e2e/specs/NestedScreenFOUR-7257.spec.js
- tests/e2e/specs/RecordList.spec.js
- tests/e2e/specs/TestValidationWithNestedSideEffects.spec.js
- tests/e2e/specs/ValidationNestedVariable.spec.js
- tests/e2e/specs/ValidationRules.spec.js
- tests/e2e/specs/ValidationRulesAdvanced.spec.js
- tests/e2e/specs/ValidationRulesNameObject.js
- tests/e2e/specs/ValidationShownOnSubmit.spec.js
- tests/e2e/support/commands.js
This feature
- Adds a red required asterisk to required fields.
- Only shows the error message and red outline after the user clicks submit and the validation rules are not met.
- Create form with an element that has required validation
- Verify the red asterisk is always shown
- Verify the message and red outline is only shown after the user clicks submit
- Try with 'required if' and 'require unless' rules. The asterisk should only show if needed.
- Try in different screen setups such as nested screens, loops, pages, etc.
- https://processmaker.atlassian.net/browse/FOUR-8092
- These PRs are for both FOUR-8093 and FOUR-8094
- Required PRs
- https://github.com/ProcessMaker/processmaker/pull/4790
- https://github.com/ProcessMaker/vue-form-elements/pull/397
- …
> Required Field Display Improvements

- src/components/accordions.js
- src/components/inspector/device-visibility.vue
- src/components/inspector/index.js
- src/form-control-common-properties.js
- src/global-properties.js
Implements:
[https://processmaker.atlassian.net/browse/FOUR-7964](https://processmaker.atlassian.net/browse/FOUR-7964)
> FOUR-7964: Screen-size Visibility Rules

- package-lock.json
- package.json
- src/App.vue
- src/components/vue-form-renderer.vue
- src/mixins/DeviceDetector.js
Create a screen with 2 input lines and configure them like this:
Line1-> Select Show For Desktop = true, Show For Mobile = false
Line2-> Select Show For Desktop = false, Show For Mobile = true
got to preview and select desktop/mobile modes. Line 1 should be visible in desktop mode, Line 2 in mobile mode
[https://processmaker.atlassian.net/browse/FOUR-7971](https://processmaker.atlassian.net/browse/FOUR-7971)
> FOUR-7971: Responsive Breakpoint

- package-lock.json
- package.json
- src/components/vue-form-renderer.vue
Implement tests according to [https://processmaker.atlassian.net/browse/FOUR-9093](https://processmaker.atlassian.net/browse/FOUR-9093)
> FOUR-9093: Automatic e2e tests

- src/components/vue-form-renderer.vue
responsive spec must work
respnsvePreview test is not working
- add data-cy 
- npm run open-cypress
- run respnsive-preview.spec.js
-
> fix responsive spec

- .gitignore
- src/App.vue
- src/components/accordions.js
- src/components/inspector/device-visibility.vue
- src/components/inspector/index.js
- src/components/screen-renderer.vue
- src/components/vue-form-renderer.vue
- src/form-control-common-properties.js
- src/global-properties.js
- src/mixins/DeviceDetector.js
- src/mixins/VisibilityRule.js
- src/mixins/extensions/VisibilityRule.js
- tests/e2e/specs/DatePicker.spec.js
- tests/e2e/specs/DatePickerTimezone.spec.js
- tests/e2e/specs/DeviceVisivilityInspector.spec.js
- tests/e2e/specs/MediaQuery.spec.js
- tests/e2e/specs/ResponsivePreview.spec.js
PR with summer sprint.
ci:deploy
ci:screen-builder:summer-2023-3
> Sprint june 26 - july 7 2023

- .npmrc
- src/ValidationsFactory.js
- src/mixins/extensions/VisibilityRule.js
ci:deploy
ci:screen-builder:bugfix/FOUR-9221
Create a screen 
Add line input
Select “Show for Mobile“ in Device visibility
Add the required field in the line input 
Press preview button 
Submit button should not disable with fields that are not visible
Submit button is disabled with required fields are not visible on the web or mobile 
Visibility rules (and device visibility rules) are applied in 2 parts: an evaluation to show/hide an element (VisibilityRule.js) and to add validation rules (ValidationsFactory.js) In this last file we weren't checking the device visibility. 
- Use the reproduction steps.
- Also test when a control is inside a table/column,  nested screen, etc.
[https://processmaker.atlassian.net/browse/FOUR-9221](https://processmaker.at …
> FOUR-9221: It is not possible to submit the form with required fields that are not visible

- tests/e2e/specs/MediaQuery.spec.js
- https://processmaker.atlassian.net/browse/FOUR-9253
> FOUR-9253 Removed the skip and fixed some typos

- src/components/renderer/form-record-list.vue
Create a screen
Add line input control
Add Validation Rules like “Max Length“
Add Submit button 
Press Preview button
Type in line input wrong to validation rule se active 
The validation behavior is specified in https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2935390211/PM4+Required+Field+Display+Improvements#PM4RequiredFieldDisplayImprovements-UserFlow2-RequiredFieldvalidationerrormessagedisplayedOnFormSubmit.
To be compatible with the PRD, as validations should be displayed at the moment of submitting, for Record Lists pressing on the  save button triggers the validation error.
No error is displayed.
[https://processmaker.atlassian.net/browse/FOUR-9129](https://processmaker.atlassian.net/browse/FOUR-9129)
> FOUR-9129: Email-Validation Rule stopped working in a record list.

- src/components/renderer/file-download.vue
Ticket: [FOUR-10343](https://processmaker.atlassian.net/browse/FOUR-10343)
This PR addresses an issue where duplicate file downloads were occurring in single-upload components. Photo/Video control and File Upload
Added conditional logic to prevent redundant file downloads.
Improved efficiency by ensuring files are only downloaded when necessary.
- Manually tested the changes in single-upload components.
- Verified that file downloads now occur only when required.
[FOUR-10343]: https://processmaker.atlassian.net/browse/FOUR-10343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prevent Duplicate File Downloads in Single-Upload Components

- src/components/inspector/analytics-selector.vue
Create a control ANALYTICS CHART(Edited)
- FOUR-9491
ci:next
> FOUR-9491-B: Create a control ANALYTICS CHART(Edited)

- src/components/editor/loop.vue
- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
**Figma**
https://www.figma.com/file/HPlbIAFk5pPLvHX6vyUN3K/Fall-23?type=design&node-id=1-2&mode=design&t=FcADuhMGTJxndieK-0
**PI Planning document**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3150675969/Ai+in+Modeler+-+PI+Document
**Epic**
https://processmaker.atlassian.net/browse/FOUR-9674
**Related PR's**
- [modeler](https://github.com/ProcessMaker/modeler/pull/1682)
- [package-ai](https://github.com/ProcessMaker/package-ai/pull/28)
- [core](https://github.com/ProcessMaker/processmaker/pull/5399)
- [package-versions](https://github.com/ProcessMaker/package-versions/pull/72)
- [screen-builder](https://github.com/ProcessMaker/screen-builder/pull/1449)
ci:next
> Epic/FOUR-9674: AI in modeler

- src/components/renderer/form-requests.vue
- src/components/renderer/form-tasks.vue
- src/mixins/datatable.js
-
- [FOUR-9656](https://processmaker.atlassian.net/browse/FOUR-9656)
[FOUR-9656]: https://processmaker.atlassian.net/browse/FOUR-9656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-9656:Home: Task and Request does not have the order by enable

- src/components/renderer/form-list-table.vue
- src/components/renderer/form-new-request.vue
- src/components/renderer/form-requests.vue
- src/components/renderer/form-tasks.vue
Element "Count" was added to new control List Table
- FOUR-10042
ci:next
> FOUR-10042: HOME: Add in the component "COUNT"

- src/components/renderer/form-requests.vue
- src/components/renderer/form-tasks.vue
-
- [FOUR-9506](https://processmaker.atlassian.net/browse/FOUR-9506)
[FOUR-9506]: https://processmaker.atlassian.net/browse/FOUR-9506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-9506:My task needs to apply the same filter to TASK

- src/components/renderer/form-button.vue
Fix loading submit button with required option
https://processmaker.atlassian.net/browse/FOUR-11025
ci:next
> Fix loading submit button with required option

- src/components/renderer/form-tasks.vue
- vue.config.js
Implement the Preview Pane in the Home Quick access to To-Do list
-  https://processmaker.atlassian.net/browse/FOUR-10857
ci:next
> feature/FOUR-10857: Home: Add functionallity Preview Pane

- src/components/renderer/form-empty-table.vue
- src/components/renderer/form-new-request.vue
- Image per defautl was added to Start New Request
ci:deploy
ci:next
> QA Observation Bugfix/FOUR-11258: Start request is not showing the image per default

- src/components/renderer/form-list-table.vue
- Go to **Welcome Home Participant**
- Check the My Request list
The filters needs to update
- As Requester instead of “Requests Started By Me”
- As Participant insted of “With Me as Participant”
- Go to **Welcome Home Participant**
- Check the My Request list
- Review the Labels
- https://processmaker.atlassian.net/browse/FOUR-11275
ci:deploy
ci:next
> FOUR-11275: Update the Request filter options nams

- src/components/renderer/form-list-table.vue
- Go to **Welcome Home Participant**
- Check the My Request list
The filters needs to update
- As Requester instead of “Requests Started By Me”
- As Participant insted of “With Me as Participant”
- Go to **Welcome Home Participant**
- Check the My Request list
- Review the Labels
- https://processmaker.atlassian.net/browse/FOUR-11275
ci:deploy
ci:next
> FOUR-11275 2

- src/components/renderer/form-requests.vue
- src/components/renderer/form-tasks.vue
- Both dropdowns in Tasks and Requests list All initial results
ci:deploy
ci:next
> QA Observation Bugfix/FOUR-11264: The initial filters does not list all

- src/components/renderer/form-analytics-chart.vue
- src/components/renderer/form-list-table.vue
- src/form-builder-controls.js
- Correct styles in Analytics Control and List Table were applied
ci:deploy
ci:next
> QA Observation Bugfix/FOUR-11321: Start New Request and Analytics Chart Style in Welcome Screen

- src/components/renderer/form-list-table.vue
> FOUR-11300:Reload After Search is not working

- src/components/renderer/avatar-dropdown.vue
- src/components/renderer/form-tasks.vue
- Fixes in Task filters applied
ci:deploy
ci:next
> QA Observation - Bugfix/FOUR-11301

- src/components/renderer/form-analytics-chart.vue
- Welcome Screen participant: Add an icon that can re direct to the Analytics option
ci:deploy
ci:next
> QA Observation bugfix/FOUR-11391: Welcome Screen participant: Add an icon that can re direct to the Analytics option

- src/mixins/extensions/ValidationRules.js
- tests/e2e/specs/ValidationShownOnSubmit.spec.js
Clone of #1478 for next branch.
ci:next
> [FOUR-11286] for Next Branch

- src/components/renderer/form-tasks.vue
- The filter Task of List Table was modified with the approval of Product Owner
https://processmaker.atlassian.net/browse/FOUR-11396
ci:deploy
ci:next
> bugfix/FOUR-11396: Welcome Screen participant: The filters does not work very well

- src/components/renderer/card.vue
- src/components/renderer/form-new-request.vue
-
- [FOUR-11556](https://processmaker.atlassian.net/browse/FOUR-11556)
ci:deploy
ci:next
[FOUR-11556]: https://processmaker.atlassian.net/browse/FOUR-11556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-11556:The start of request, it does not go to Task when we start from Home

- src/components/renderer/card.vue
- src/components/renderer/form-new-request.vue
- Have a list of processes to start a request
- Go to the Designer Welcome Screen
- Go to the section START NEW REQUEST
- Review the styles for use the same with
- [FOUR-12355](https://processmaker.atlassian.net/browse/FOUR-12355)
ci:deploy
ci:package-dynamic-ui:bugfix/FOUR-12355
[FOUR-12355]: https://processmaker.atlassian.net/browse/FOUR-12355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-12355:Alingment and Box Dimensions is not Uniform

- src/components/renderer/form-list-table.vue
- The reported issue was fixed.
ci:deploy
> QA Observation bugfix/FOUR-12423: Welcome Screen Task Search Changes the Names of Tasks After Search. Task List Not Reliable

- tests/e2e/specs/Builder.spec.js
- tests/e2e/specs/ComputedFields.spec.js
- tests/e2e/specs/ComputedFieldsReadOnly.spec.js
- tests/e2e/specs/CustomCss.spec.js
- tests/e2e/specs/DatePicker.spec.js
- tests/e2e/specs/DatePickerTimezone.spec.js
- tests/e2e/specs/DefaultValues.spec.js
- tests/e2e/specs/DeviceVisivilityInspector.spec.js
- tests/e2e/specs/FileUpload.spec.js
- tests/e2e/specs/FormImage.spec.js
- tests/e2e/specs/FormInput.spec.js
- tests/e2e/specs/FormSelectList.spec.js
- tests/e2e/specs/FormTextArea.spec.js
- tests/e2e/specs/Loop.spec.js
- tests/e2e/specs/MediaQuery.spec.js
- tests/e2e/specs/MultiColumn.spec.js
- tests/e2e/specs/MultiInstanceLoopContext.spec.js
- tests/e2e/specs/NestedScreen.spec.js
- tests/e2e/specs/Pages.spec.js
- tests/e2e/specs/Pagination.spec.js
- tests/e2e/specs/ResponsivePreview.spec.js
- tests/e2e/specs/RichText.spec.js
- tests/e2e/specs/ScreenWarnings.spec.js
- tests/e2e/specs/SelectListDependentCollection.spec.js
- tests/e2e/specs/UndoRedo.spec.js
- tests/e2e/specs/VariableNames.js
- tests/e2e/specs/VisibilityRule.spec.js
- tests/e2e/specs/WrongConfigurationErrors.js
- tests/e2e/support/commands.js
fix some test cases in order to open the acordeon
> add openAcordeon method and update tests

- package-lock.json
- package.json
- https://processmaker.atlassian.net/browse/FOUR-13020
> FOUR-13020 Changed the engines to be equal or greater than 16

- package-lock.json
- package.json
- tests/e2e/specs/RecordList.spec.js
- tests/e2e/support/commands.js
> Vue Form Elements v0.50.1

- vue.config.js
> Do not run linter on npm run serve

- package-lock.json
> FOUR-13021 Upgraded dependencies to solve some security issues

- package.json
- src/components/index.js
* Expanded the files to be exported
> Added new exports for the form-control-common-properties

- src/components/renderer/card.vue
- src/components/renderer/form-list-table.vue
- src/components/renderer/form-new-request.vue
The Section “Start a New Request” doesn’t have the same sizes  of the other sections. Also the design and the colors are not the same as Figma.
- Update the styles according figma
Go to Home page
- [FOUR-13374](https://processmaker.atlassian.net/browse/FOUR-13374)
ci:deploy
ci:next
[FOUR-13374]: https://processmaker.atlassian.net/browse/FOUR-13374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-13374: The Design of "Start a New Request" Section does not have the same size of figma design

- tests/e2e/specs/DatePicker.spec.js
- tests/e2e/specs/MultipleUpload.spec.js
- tests/e2e/specs/RecordList.spec.js
> Skipping flaky tests

- .github/workflows/ci.yml
- .github/workflows/sonarqube.yml
- sonar-project.properties
> Reusing the sonarqube workflow and getting the coverage to be sent to sonarqube

- src/bootstrap.js
- src/components/TabsBar.vue
- src/components/vue-form-builder.vue
- src/stories/PageTabs.stories.js
- Create tabs component to Open pages in Tabs
- Create some pages
- Use the drop down to open or select a page
- Change from page using the opened tabs
- When multiple pages are opened you can use the (<) (>) buttons to scroll the tabs
- https://processmaker.atlassian.net/browse/FOUR-13448
ci:next
> FOUR-13448 Create tabs component to Open pages in Tabs

- package.json
- src/components/task.vue
- src/mixins/Json2Vue.js
- tests/e2e/specs/DatePickerTimezone.spec.js
Allow editing completed task to re-use data
ci:next
..
> Allow editing completed task to re-use data

- package-lock.json
- package.json
> Vue Form Elements v0.52.1

- src/components/renderer/form-input-masked.vue
- src/currency.json
The INR (Indian Rupee) currency is formatted incorrectly.
1. Create an screen.
2. Add new field
3. Configure Data Type Currency
4. Configure Currency Format INR
Expected behavior:
The INR currency should be formatted correctly.
Actual behavior:
The format currency (INR) is incorrect
- Implement the special input mask available for the Indian-specific numbering system.
Run through the replication steps
- [FOUR-14759](https://processmaker.atlassian.net/browse/FOUR-14759)
[FOUR-14759]: https://processmaker.atlassian.net/browse/FOUR-14759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-14759: Currency formatting for the Indian Rupee

- src/components/TabsBar.vue
- src/components/vue-form-builder.vue
Create a Display, Conversational, Email Screen.
- https://processmaker.atlassian.net/browse/FOUR-15069
ci:next
> FOUR-15069 Fix It is not possible open page in Screen (Display, Conversational, Email), If it is closed

- src/DataProvider.js
- src/components/renderer/file-upload.vue
See Core PR https://github.com/ProcessMaker/processmaker/pull/6780
ci:next
ci:processmaker:bugfix/FOUR-15242
ci:package-files:bugfix/FOUR-15242
.
> Handle files in task drafts

- src/components/renderer/form-list-table.vue
Change Request to Cases
- [FOUR-15760](https://processmaker.atlassian.net/browse/FOUR-15760)
ci:deploy
ci:next
[FOUR-15760]: https://processmaker.atlassian.net/browse/FOUR-15760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15760:Rename My Request to My Cases

- src/components/renderer/form-requests.vue
- Update the columns with the width requiered
- [FOUR-15761](https://processmaker.atlassian.net/browse/FOUR-15761)
ci:deploy
ci:next
[FOUR-15761]: https://processmaker.atlassian.net/browse/FOUR-15761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15761:[20:My Cases - Update the columns to show cases

- src/components/renderer/form-list-table.vue
Update the counters
- [FOUR-16235](https://processmaker.atlassian.net/browse/FOUR-16235)
ci:deploy
ci:next
[FOUR-16235]: https://processmaker.atlassian.net/browse/FOUR-16235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-16235:Implement the new UI counters

- src/components/renderer/form-tasks.vue
Show the scroll when is hover
- [FOUR-15769](https://processmaker.atlassian.net/browse/FOUR-15769)
ci:deploy
ci:next
[FOUR-15769]: https://processmaker.atlassian.net/browse/FOUR-15769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15769:My Task - Implement the scroll in this list

- src/components/renderer/form-tasks.vue
Add the Tag Draft in My tasks
- [FOUR-15775](https://processmaker.atlassian.net/browse/FOUR-15775)
ci:deploy
ci:next
[FOUR-15775]: https://processmaker.atlassian.net/browse/FOUR-15775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15775:Add Tag Draft when the request has defined the draft

- src/components/renderer/form-tasks.vue
Add the functionality to priority column
- [FOUR-15771](https://processmaker.atlassian.net/browse/FOUR-15771)
ci:deploy
ci:next
[FOUR-15771]: https://processmaker.atlassian.net/browse/FOUR-15771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15771:Add the functionality to Priority column

- src/components/renderer/form-tasks.vue
redirect for cases in task table
- https://processmaker.atlassian.net/browse/FOUR-16316
ci:deploy
ci:next
> feature/FOUR-16316:  My Task - Implement the Open links for columns Task and Case Title

- src/components/renderer/form-tasks.vue
adding self-service filter
- https://processmaker.atlassian.net/browse/FOUR-15772
ci:deploy
ci:next
> feature/FOUR-15535: Update filters in Tasks

- src/components/renderer/form-tasks.vue
Add the hover for preview
- [FOUR-15779](https://processmaker.atlassian.net/browse/FOUR-15779)
[FOUR-15779]: https://processmaker.atlassian.net/browse/FOUR-15779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15537:Review the Hover action preview buton Tasks

- src/components/index.js
- src/components/inspector/index.js
- src/components/inspector/input-url-link.vue
- src/components/renderer/index.js
- src/components/renderer/link-button.vue
- src/form-builder-controls.js
- src/form-control-common-properties.js
Create a new control link like a button button in the Email Screen
- [FOUR-15820](https://processmaker.atlassian.net/browse/FOUR-15820)
ci:next
[FOUR-15820]: https://processmaker.atlassian.net/browse/FOUR-15820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-15820:create a new control link

- src/mixins/ScreenBase.js
- tests/e2e/fixtures/FOUR-16958_watchers.json
- tests/e2e/specs/FOUR-16958_watchers.spec.js
The watcher and script to clean data should clean/update the data successfully without returning the old values.
Watchers that are used to clean the data of fields using script tasks are not working anymore when running the watcher is cleaning the data but when you try to type a different one in the field it returns the old data, this happens in text area, input fields.
- clean debouncedValuesQueue because this array acts like a cache
https://github.com/ProcessMaker/screen-builder/assets/1401911/96247730-6019-4500-9079-975073be3c60
1. Import the following screen Reset this page.json 
2. Preview it or create a case
3. Use the button to clear the fields
4. Try to type again in the fields
5. At this point, you will see that the old …
> FOUR-16958: Regression - Watchers running scripts to clean data stops working and keeps the data

- src/components/renderer/form-tasks.vue
View All in MY TASKS Dashboard filter task Completed in Welcome Screen
The sum of cases in View All should match the sum of the other tasks in the categories (Self Service, In progress, due date). Like as this worked in the previous version
The sum of cases in View All does not match the sum of the other tasks in the categories (Self Service, In progress, due date)
Because View All also lists completed tasks
- [FOUR-16634](https://processmaker.atlassian.net/browse/FOUR-16634)
ci:deploy
ci:next
[FOUR-16634]: https://processmaker.atlassian.net/browse/FOUR-16634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-16634:View All in MY TASKS Dashboard filter task Completed 

- src/components/renderer/form-list-table.vue
Required screen builder changes for
- https://processmaker.atlassian.net/browse/FOUR-13467
- https://processmaker.atlassian.net/browse/FOUR-13466
ci:next
> Support recommendations in the dashboard tables

- src/form-builder-controls.js
Create a screen email
Check in CONTENT FIELDS
Hover on “Link URL”
Check the tool tip help for this control 
- update the tooltip
review the tooltip
- https://processmaker.atlassian.net/browse/FOUR-17007
ci:next
> FOUR-17007: Tool tip to "Link URL" should be different that submit button in Email screen

- src/components/renderer/form-requests.vue
- src/components/renderer/form-tasks.vue
The "Case Title" column is cut off in the "MY CASES" Dashboard
- [FOUR-16321](https://processmaker.atlassian.net/browse/FOUR-16321)
ci:next
[FOUR-16321]: https://processmaker.atlassian.net/browse/FOUR-16321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FOUR-16321:The "Case Title" column is cut off in the "MY CASES" Dashboard

- src/components/task.vue
https://processmaker.atlassian.net/browse/FOUR-18851
Requires https://github.com/ProcessMaker/processmaker/pull/7283
ci:next
> Set nodeId for redirect events for webentry

- src/components/task.vue
The user should be redirected to the welcome screen
The user is redirected to form the second task form
- complete missed logic to redirect
https://github.com/user-attachments/assets/794ea1b0-aa6d-4547-b4f5-7b60a1ab6df3
- https://processmaker.atlassian.net/browse/FOUR-18823
> FOUR-18823: Welcome screen in element destination is not working

- src/components/renderer/file-upload.vue
This PR is part of [FOUR-18298](https://processmaker.atlassian.net/browse/FOUR-18298) and introduces support for the FileUpload control within conversational forms, along with UI updates specific to this functionality. The changes ensure that users can interact with file uploads seamlessly within conversational forms, adhering to the new design specifications.
- Implemented the rendering of the "Add File/Photo" button specifically for file uploads in conversational forms.
- Added logic to render the list of uploaded files within conversational forms.
- Applied specific CSS for the proper rendering and styling of file upload components in conversational forms.
Refer to the [PR](https://github.com/ProcessMaker/package-conversational-forms/pull/57) for Conversational Forms for detailed …
> Add Support for FileUpload Control in Conversational Forms

- src/components/accordions.js
- src/components/inspector/encrypted-config.vue
- src/components/inspector/index.js
- src/global-properties.js
- vite.config.js
https://processmaker.atlassian.net/browse/FOUR-18067
ci:next
> FOUR-18067 STORY Add Encrypted Toggle in the Input Field

- src/components/SelectUserGroup.vue
- src/components/inspector/encrypted-config.vue
- src/main.js
https://processmaker.atlassian.net/browse/FOUR-18068
ci:next
> FOUR-18068 STORY Configure Access for Groups/Users

- package-lock.json
- package.json
- src/components/renderer/form-masked-input.vue
- src/main.js
https://processmaker.atlassian.net/browse/FOUR-18070
ci:next
> FOUR-18070 STORY Reveal/Conceal Content in Form Preview

- package-lock.json
- package.json
- src/components/ClipboardButton.vue
- src/components/editor/loop.vue
- src/components/editor/multi-column.vue
- src/components/index.js
- src/components/vue-form-builder.vue
- src/main.js
- src/mixins/Clipboard.js
- src/mixins/index.js
- src/store/modules/clipboardModule.js
- src/store/modules/undoRedoModule.js
- src/stories/ClipboardButton.stories.js
- tests/e2e/specs/Clipboard.spec.js
- tests/e2e/specs/ClipboardControl.spec.js
- tests/e2e/support/commands.js
As a Designer, I want the copy icon to add content to the clipboard when selected.
- add ClipboardButton component 
https://github.com/user-attachments/assets/0a193596-6ae3-4b70-972e-2f110083e283
- https://processmaker.atlassian.net/browse/FOUR-13438
> FOUR-13438: STORY Copy icon now adds to clipboard

- src/components/renderer/file-upload.vue
This PR adds functionality for multiple file uploads within conversational form type screens. It also includes UI updates and refactors to enhance the usability and styling of the file upload component for conversational forms.
- Implemented support for uploading multiple files in conversational forms.
- Added a "Skip Upload" button, which will be visible when the file upload control is not a required field, allowing users to skip the file upload process.
- Refactored the file upload component specifically for conversational forms to improve code organization and maintainability.
- Updated styling of the file upload control to align with the conversational forms' design and improve user interaction.
See testing steps in [Conversational Forms …
> Support for Multiple File Uploads in Conversational Forms

- src/App.vue
- src/VariableDataTypeProperties.js
- src/components/vue-form-builder.vue
- src/components/vue-form-renderer.vue
- src/mixins/Clipboard.js
- src/store/modules/clipboardModule.js
As a Designer, I want the copy icon to add more than one piece of content to the clipboard when selected.
- adding clipb
https://github.com/user-attachments/assets/28e52d60-e908-4162-bc0f-066d95003e89
oard basic CRUD
- https://processmaker.atlassian.net/browse/FOUR-13439
> FOUR-13439: STORY Adding multiple content to the clipboard

- src/components/renderer/form-masked-input.vue
https://processmaker.atlassian.net/browse/FOUR-18069
ci:next
> FOUR-18069 STORY Reveal/Conceal Content in Form

- src/components/CssIcon.vue
- src/components/ScreenTemplateCard.vue
- src/components/ScreenTemplates.vue
- src/components/vue-form-builder.vue
Ticket: [FOUR-19136](https://processmaker.atlassian.net/browse/FOUR-19136)
This PR adds updated styling to Screen Template Cards in the Screen Templates Panel. Updates include:
- Adds a b-collapse to ScreenTemplateCards.vue that reveals 'Apply Options' when a card is clicked.
- Adds icons and checkboxes for 'Apply Options' (Css, Fields, Layout).
- Adds 'Apply' and 'Cancel' button to each Screen Template Card.
1. Go to branch `observation/FOUR-19136` in `screen-builder` and `processmaker`.
2. Open a Screen in the Screen Builder.
3. Select 'Templates' from the top menu.
- Screen Template Cards should appear for the templates in your environment.
4. Select a Screen Template Card.
- The card should expand and the contents of the card should match the [Figma …
> FOUR-19136 | CSS Updates for Screen Templates Panel

- src/components/editor/loop.vue
- src/components/editor/multi-column.vue
- src/components/vue-form-builder.vue
- src/mixins/Clipboard.js
- src/store/modules/clipboardModule.js
- tests/e2e/specs/Clipboard.spec.js
- Implement remove element from clipboard
Add and remove elements from clipboard
https://github.com/user-attachments/assets/e5c7d507-9a1a-4b75-8da8-1e16b89a9990
- https://processmaker.atlassian.net/browse/FOUR-13440
- [] I have pulled this code locally and tested it on my instance, along with any associated packages.
ci:next
> FOUR-13440 Implement remove element from clipboard

- src/components/TabsBar.vue
- src/components/editor/pagesDropdown.vue
- src/components/vue-form-builder.vue
- src/mixins/Clipboard.js
- src/stories/PagesDropdown.stories.js
- Implement Clear Clipboard
- Add some items to the clipboard
- Drag and Paste
- Go to Clear Clipboard
- Back to the page
- Try to drag and paste, now is empty
- https://processmaker.atlassian.net/browse/FOUR-13442
ci:next
> FOUR-13442 Implement Clear clipboard

- src/DataProvider.js
- src/components/inspector/collection-data-source.vue
- src/components/inspector/collection-records-list.vue
- src/components/inspector/index.js
- src/components/renderer/form-record-list.vue
- src/components/vue-form-builder.vue
- src/form-builder-controls.js
-Login PM4
- Go to Screens and create a new Screen
- Select Record List control
- Go to Configuration and select Source Of Record List "Collection"
- Choose a collection pre loaded
- add PMQL criteria (optional)
- Click on Preview
https://processmaker.atlassian.net/browse/FOUR-18108
ci:next
> Feature/FOUR-18108 STORY Collection Data Source for Record Lists

- src/components/task.vue
This PR introduces the `@update` listener to the `<components>` component, enabling the AutoSave feature for conversational forms. The AutoSave functionality triggers automatically when changes are made to the conversational form, ensuring that data is saved without requiring manual intervention.
- Added the `@update` listener to the `<components>` component to detect and handle data changes for AutoSave.
1. Create a process using a conversational form.
2. Run the process and open the conversational form.
3. Make changes to the form data (e.g., filling out fields, selecting options).
4. Verify that the AutoSave feature is triggered upon data changes without requiring manual saving.
5. Ensure that the changes are persisted by checking the form state after navigation or reloading the …
> Add AutoSave Feature Support for Conversational Forms

- src/components/renderer/file-upload.vue
This PR addresses the issue of the file uploader list covering the chat history in conversational forms when multiple files are uploaded. It adds a max height to the file uploader list and enables auto scroll functionality, allowing users to view all uploaded files without obstructing the chat history.
- Added a max-height to the file uploader list `.cf-file-uploader` for multiple file uploads in conversational forms.
- Enabled auto scroll functionality when the file uploader list exceeds the max height.
1. Create a conversational form screen using the File Upload control.
2. Enable the "Multiple uploads" option for the File Upload control.
3. Create and run a process using the conversational form.
4. Upload at least 5 files.
5. Ensure the file uploader list enforces the max height and …
> Add Max Height and Auto Scroll to File Uploader List for Multiple File Uploads in Conversational Forms

- src/components/index.js
- src/components/inspector/collection-records-list.vue
- src/components/renderer/form-collection-view-control.vue
- src/components/renderer/index.js
- src/form-builder-controls.js
- Login PM4
- Go to Designer->Screens
- Create new Screen in mode DISPLAY
- Drag new Collection View Control
- Select a Collection
- Insert a number of record
- Click on Preview
https://processmaker.atlassian.net/browse/FOUR-18116
> Feature/FOUR-18116: STORY Add Collection View Control in Display Screens

- src/components/renderer/form-masked-input.vue
https://processmaker.atlassian.net/browse/FOUR-19233
> FOUR-19233 Buttons Conceal and Reveal are not the Same as in Figma

- src/components/renderer/file-upload.vue
- https://processmaker.atlassian.net/browse/FOUR-16701
ci:next
> FOUR-16701: [FALL] Unrestricted File Upload

- src/form-control-common-properties.js
- tests/e2e/specs/Builder.spec.js
> FOUR-14970 Replace regex with dot_notation validator

- .github/workflows/ci.yml
- package-lock.json
- package.json
Use 0.60.1 of vue form elements
..
> Set new vue-form-elements version

- .github/workflows/ci.yml
- src/components/renderer/file-upload.vue
This PR addresses the issue where error messages were unclear when SVG file uploads failed. The existing error message was not specific enough, making it difficult for users to understand why the file upload was failing.
- Navigate to the file manager
- Upload attached SVG within the ticket.
- The file fails to upload and is unclear why.
- Give a reasonable human readable feedback to the user
- Unclear error message
- Improved error handling for SVG file uploads.
- Updated the error message to provide more specific details about the failure (e.g., unsupported tags).
- Refined validation logic to catch SVG-related issues early and report them more clearly to the user.
- Give feedback in how to resolve the issue to the user.
- ![Screenshot 2024-10-21 at …
> Bugfix/four 19706Bugfix-FOUR:19706: Improve error message when SVG's fails to upload

- src/form-builder-controls.js
Record list is affected by another record list configuration
Current Behavior:
Configuration in the first record list is affected by the second one. 
Configuration should not be affected by another records lists
https://processmaker.atlassian.net/browse/FOUR-20073
.
> FOUR-20073 Record list is affected by another record list configuration

- .github/workflows/storybook.yml
- src/components/screen-renderer.vue
- src/components/task.vue
- src/components/vue-form-renderer.vue
- src/mixins/extensions/PageNavigate.js
1. Import the attached screen file.
2. Preview the screen.
3. Navigate to the second page of the screen.
**Current Behavior:**
When the customer builds a button in a form that navigates to a new screen, the following page opens at the same point where the previous page was left off. This means the subsequent page opens about halfway down.
**Expected Behavior:**
The new page should open from the top, not at the same point where the previous page was left off.
- https://processmaker.atlassian.net/browse/FOUR-17551
ci:processmaker:release-2025-winter
> FOUR-17551: Scrollbar Position Issue When Navigating to Next Page

- src/form-builder-controls.js
> Applying fix to Collection Record Control

- src/components/renderer/case-progress-bar.vue
Update the API using the new
- https://processmaker.atlassian.net/browse/FOUR-24448
> FOUR-24448: Consider use cases for return Default Stages per Case and case_number not required
